export const ARTIST_SEARCH_PLATFORMS = [
  {
    id: 'spotify-artist',
    name: 'Spotify Artist',
    icon: 'spotify',
    searchMode: true,
    provider: 'spotify' as const,
  },
] as const;

export type ArtistSearchProvider =
  (typeof ARTIST_SEARCH_PLATFORMS)[number]['provider'];

export type PlatformCategory = 'music' | 'social' | 'video' | 'other';

export const PLATFORM_OPTIONS = [
  {
    id: 'spotify',
    name: 'Spotify',
    icon: 'spotify',
    prefill: 'https://open.spotify.com/artist/',
    hint: 'artist link',
    category: 'music' as PlatformCategory,
    popular: true,
  },
  {
    id: 'apple-music',
    name: 'Apple Music',
    icon: 'applemusic',
    prefill: 'https://music.apple.com/artist/',
    hint: 'artist link',
    category: 'music' as PlatformCategory,
    popular: true,
  },
  {
    id: 'youtube-music',
    name: 'YouTube Music',
    icon: 'youtube',
    prefill: 'https://music.youtube.com/channel/',
    hint: 'channel link',
    category: 'music' as PlatformCategory,
    popular: false,
  },
  {
    id: 'instagram',
    name: 'Instagram',
    icon: 'instagram',
    prefill: 'https://instagram.com/',
    hint: '@username',
    category: 'social' as PlatformCategory,
    popular: true,
  },
  {
    id: 'tiktok',
    name: 'TikTok',
    icon: 'tiktok',
    prefill: 'https://www.tiktok.com/@',
    hint: '@username',
    category: 'social' as PlatformCategory,
    popular: true,
  },
  {
    id: 'youtube',
    name: 'YouTube',
    icon: 'youtube',
    prefill: 'https://www.youtube.com/@',
    hint: '@channel',
    category: 'video' as PlatformCategory,
    popular: true,
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    icon: 'x',
    prefill: 'https://x.com/',
    hint: '@handle',
    category: 'social' as PlatformCategory,
    popular: true,
  },
  {
    id: 'facebook',
    name: 'Facebook',
    icon: 'facebook',
    prefill: 'https://facebook.com/',
    hint: '/page',
    category: 'social' as PlatformCategory,
    popular: false,
  },
  {
    id: 'soundcloud',
    name: 'SoundCloud',
    icon: 'soundcloud',
    prefill: 'https://soundcloud.com/',
    hint: '/artist',
    category: 'music' as PlatformCategory,
    popular: false,
  },
  {
    id: 'twitch',
    name: 'Twitch',
    icon: 'twitch',
    prefill: 'https://twitch.tv/',
    hint: '/channel',
    category: 'video' as PlatformCategory,
    popular: false,
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: 'linkedin',
    prefill: 'https://linkedin.com/in/',
    hint: '/profile',
    category: 'social' as PlatformCategory,
    popular: false,
  },
  {
    id: 'venmo',
    name: 'Venmo',
    icon: 'venmo',
    prefill: 'https://venmo.com/',
    hint: '@username',
    category: 'other' as PlatformCategory,
    popular: false,
  },
  {
    id: 'discord',
    name: 'Discord',
    icon: 'discord',
    prefill: 'https://discord.gg/',
    hint: 'invite code',
    category: 'social' as PlatformCategory,
    popular: false,
  },
  {
    id: 'threads',
    name: 'Threads',
    icon: 'threads',
    prefill: 'https://threads.net/@',
    hint: '@username',
    category: 'social' as PlatformCategory,
    popular: false,
  },
  {
    id: 'telegram',
    name: 'Telegram',
    icon: 'telegram',
    prefill: 'https://t.me/',
    hint: '@username',
    category: 'social' as PlatformCategory,
    popular: false,
  },
  {
    id: 'snapchat',
    name: 'Snapchat',
    icon: 'snapchat',
    prefill: 'https://snapchat.com/add/',
    hint: 'username',
    category: 'social' as PlatformCategory,
    popular: false,
  },
  {
    id: 'website',
    name: 'Website',
    icon: 'globe',
    prefill: 'https://',
    hint: 'your URL',
    category: 'other' as PlatformCategory,
    popular: true,
  },
] as const;

export const CATEGORY_LABELS: Record<PlatformCategory, string> = {
  music: 'Music',
  social: 'Social',
  video: 'Video',
  other: 'Other',
};

export const CATEGORY_ORDER: PlatformCategory[] = [
  'social',
  'music',
  'video',
  'other',
];
