/**
 * Audience Unsubscribe API
 *
 * GET /api/audience/unsubscribe?token=...
 * One-click unsubscribe from tip thank-you emails.
 *
 * The token is a signed payload containing the fan's email address,
 * generated by generateUnsubscribeToken(). This prevents unauthorized
 * unsubscribes while allowing one-click action from the email footer.
 */

import { eq } from 'drizzle-orm';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { tipAudience } from '@/lib/db/schema/tip-audience';
import { verifyUnsubscribeToken } from '@/lib/email/unsubscribe-token';
import { captureError } from '@/lib/error-tracking';
import { logger } from '@/lib/utils/logger';

export const runtime = 'nodejs';

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const token = searchParams.get('token');

    if (!token) {
      return new NextResponse(
        buildHtmlPage(
          'Invalid Link',
          'This unsubscribe link is invalid or expired.'
        ),
        {
          status: 400,
          headers: { 'Content-Type': 'text/html; charset=utf-8' },
        }
      );
    }

    // Verify the token and extract the email
    const email = verifyUnsubscribeToken(token);

    if (!email) {
      return new NextResponse(
        buildHtmlPage(
          'Invalid Link',
          'This unsubscribe link is invalid or expired.'
        ),
        {
          status: 400,
          headers: { 'Content-Type': 'text/html; charset=utf-8' },
        }
      );
    }

    // Update all tip_audience records for this email to unsubscribed
    const updated = await db
      .update(tipAudience)
      .set({
        unsubscribed: true,
        updatedAt: new Date(),
      })
      .where(eq(tipAudience.email, email))
      .returning({ id: tipAudience.id });

    logger.info('Tip audience unsubscribed', {
      emailDomain: email.split('@')[1],
      recordsUpdated: updated.length,
    });

    return new NextResponse(
      buildHtmlPage(
        "You've been unsubscribed",
        "You won't receive any more tip-related emails. If you change your mind, you can re-subscribe from any artist's profile page."
      ),
      {
        status: 200,
        headers: { 'Content-Type': 'text/html; charset=utf-8' },
      }
    );
  } catch (error) {
    captureError('[audience] unsubscribe error', error);
    return new NextResponse(
      buildHtmlPage(
        'Something went wrong',
        'We could not process your unsubscribe request. Please try again later.'
      ),
      {
        status: 500,
        headers: { 'Content-Type': 'text/html; charset=utf-8' },
      }
    );
  }
}

function buildHtmlPage(title: string, message: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; background: #f5f5f5; color: #333; }
    .card { background: #fff; padding: 48px; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); max-width: 400px; text-align: center; }
    h1 { font-size: 24px; margin: 0 0 12px; }
    p { font-size: 16px; line-height: 1.5; color: #666; margin: 0; }
  </style>
</head>
<body>
  <div class="card">
    <h1>${title}</h1>
    <p>${message}</p>
  </div>
</body>
</html>`;
}
