name: 'Fast Lane Eligibility Check'
description: 'Determines if changes are eligible for fast lane auto-promotion to production'

outputs:
  eligible:
    description: 'Whether changes are eligible for fast lane (true/false)'
    value: ${{ steps.check.outputs.eligible }}
  blockers:
    description: 'JSON array of blocking reasons (migration, auth, core-flow, payments)'
    value: ${{ steps.check.outputs.blockers }}
  has_statsig_gate:
    description: 'Whether changed files use Statsig feature gates'
    value: ${{ steps.check.outputs.has_statsig_gate }}

runs:
  using: 'composite'
  steps:
    - name: Get changed files (main vs production)
      id: files
      shell: bash
      run: |
        # Fetch production branch to compare against
        git fetch origin production --depth=1 2>/dev/null || {
          echo "Warning: Could not fetch production branch"
          echo "files=" >> $GITHUB_OUTPUT
          exit 0
        }

        # Get list of changed files between production and current HEAD
        CHANGED=$(git diff --name-only origin/production...HEAD 2>/dev/null || echo "")

        echo "Changed files:"
        echo "$CHANGED"

        # Output as multiline
        echo "files<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGED" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Check for blocking path patterns
      id: check
      shell: bash
      run: |
        BLOCKERS=()
        FILES="${{ steps.files.outputs.files }}"

        if [ -z "$FILES" ]; then
          echo "No files changed, eligible for fast lane"
          echo "blockers=[]" >> $GITHUB_OUTPUT
          echo "eligible=true" >> $GITHUB_OUTPUT
          echo "has_statsig_gate=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # --- Migration Detection ---
        # Any changes to drizzle/migrations/ or schema files
        if echo "$FILES" | grep -qE '^drizzle/migrations/'; then
          echo "BLOCKED: Database migrations detected"
          BLOCKERS+=("migration")
        fi

        # --- Auth/Clerk Detection ---
        # Changes to auth routes, lib/auth, middleware, or Clerk-related files
        if echo "$FILES" | grep -qE '^(app/\(auth\)/|lib/auth/|middleware\.ts)'; then
          echo "BLOCKED: Auth/Clerk changes detected"
          BLOCKERS+=("auth")
        fi
        # Also check for Clerk in any path
        if echo "$FILES" | grep -qiE 'clerk'; then
          if [[ ! " ${BLOCKERS[*]} " =~ " auth " ]]; then
            echo "BLOCKED: Clerk-related files detected"
            BLOCKERS+=("auth")
          fi
        fi

        # --- Core Flow Detection ---
        # Onboarding, subscribe, signin, signup flows
        if echo "$FILES" | grep -qE '^(app/onboarding/|app/\[username\]/subscribe/|components/onboarding/|app/\(auth\)/signin/|app/\(auth\)/signup/)'; then
          echo "BLOCKED: Core flow changes detected (onboarding/subscribe/auth)"
          BLOCKERS+=("core-flow")
        fi

        # --- Payment Detection ---
        # Billing, pricing, Stripe-related files
        if echo "$FILES" | grep -qE '^(app/billing/|app/\(marketing\)/pricing/|app/api/stripe/|lib/stripe/)'; then
          echo "BLOCKED: Payment/billing changes detected"
          BLOCKERS+=("payments")
        fi
        # Also check for payment-related keywords in paths
        if echo "$FILES" | grep -qiE '(payment|checkout|subscription)'; then
          if [[ ! " ${BLOCKERS[*]} " =~ " payments " ]]; then
            echo "BLOCKED: Payment-related files detected"
            BLOCKERS+=("payments")
          fi
        fi

        # --- Statsig Gate Detection ---
        # Scan changed .ts/.tsx files for gate usage
        HAS_GATE="false"
        GATE_PATTERNS="checkGate|useGate|STATSIG_FLAGS\."

        for file in $(echo "$FILES" | grep -E '\.(ts|tsx)$'); do
          if [ -f "$file" ]; then
            if grep -qE "$GATE_PATTERNS" "$file" 2>/dev/null; then
              echo "Feature gate detected in: $file"
              HAS_GATE="true"
              break
            fi
          fi
        done

        echo "has_statsig_gate=$HAS_GATE" >> $GITHUB_OUTPUT

        # --- Output Results ---
        if [ ${#BLOCKERS[@]} -eq 0 ]; then
          echo ""
          echo "ELIGIBLE for fast lane - no blocking patterns detected"
          echo "blockers=[]" >> $GITHUB_OUTPUT
          echo "eligible=true" >> $GITHUB_OUTPUT
        else
          echo ""
          echo "NOT ELIGIBLE for fast lane - blockers: ${BLOCKERS[*]}"
          # Convert bash array to JSON array
          BLOCKERS_JSON=$(printf '%s\n' "${BLOCKERS[@]}" | jq -R . | jq -s -c .)
          echo "blockers=$BLOCKERS_JSON" >> $GITHUB_OUTPUT
          echo "eligible=false" >> $GITHUB_OUTPUT
        fi
