/**
 * Popular cities for the LocationPicker component.
 * Top entries are music-industry hubs, followed by US and international cities sorted alphabetically.
 */

export const POPULAR_CITIES: { label: string; value: string }[] = [
  // --- Music-industry hubs (top 10) ---
  { label: 'Los Angeles, CA', value: 'los angeles, ca' },
  { label: 'Nashville, TN', value: 'nashville, tn' },
  { label: 'New York, NY', value: 'new york, ny' },
  { label: 'Atlanta, GA', value: 'atlanta, ga' },
  { label: 'London, UK', value: 'london, uk' },
  { label: 'Miami, FL', value: 'miami, fl' },
  { label: 'Chicago, IL', value: 'chicago, il' },
  { label: 'Austin, TX', value: 'austin, tx' },
  { label: 'Detroit, MI', value: 'detroit, mi' },
  { label: 'Memphis, TN', value: 'memphis, tn' },

  // --- US cities (alphabetical) ---
  { label: 'Albuquerque, NM', value: 'albuquerque, nm' },
  { label: 'Baltimore, MD', value: 'baltimore, md' },
  { label: 'Birmingham, AL', value: 'birmingham, al' },
  { label: 'Boston, MA', value: 'boston, ma' },
  { label: 'Charlotte, NC', value: 'charlotte, nc' },
  { label: 'Cincinnati, OH', value: 'cincinnati, oh' },
  { label: 'Cleveland, OH', value: 'cleveland, oh' },
  { label: 'Columbus, OH', value: 'columbus, oh' },
  { label: 'Dallas, TX', value: 'dallas, tx' },
  { label: 'Denver, CO', value: 'denver, co' },
  { label: 'El Paso, TX', value: 'el paso, tx' },
  { label: 'Fort Worth, TX', value: 'fort worth, tx' },
  { label: 'Fresno, CA', value: 'fresno, ca' },
  { label: 'Honolulu, HI', value: 'honolulu, hi' },
  { label: 'Houston, TX', value: 'houston, tx' },
  { label: 'Indianapolis, IN', value: 'indianapolis, in' },
  { label: 'Jacksonville, FL', value: 'jacksonville, fl' },
  { label: 'Kansas City, MO', value: 'kansas city, mo' },
  { label: 'Las Vegas, NV', value: 'las vegas, nv' },
  { label: 'Louisville, KY', value: 'louisville, ky' },
  { label: 'Milwaukee, WI', value: 'milwaukee, wi' },
  { label: 'Minneapolis, MN', value: 'minneapolis, mn' },
  { label: 'New Orleans, LA', value: 'new orleans, la' },
  { label: 'Oakland, CA', value: 'oakland, ca' },
  { label: 'Oklahoma City, OK', value: 'oklahoma city, ok' },
  { label: 'Orlando, FL', value: 'orlando, fl' },
  { label: 'Philadelphia, PA', value: 'philadelphia, pa' },
  { label: 'Phoenix, AZ', value: 'phoenix, az' },
  { label: 'Pittsburgh, PA', value: 'pittsburgh, pa' },
  { label: 'Portland, OR', value: 'portland, or' },
  { label: 'Raleigh, NC', value: 'raleigh, nc' },
  { label: 'Richmond, VA', value: 'richmond, va' },
  { label: 'Sacramento, CA', value: 'sacramento, ca' },
  { label: 'Salt Lake City, UT', value: 'salt lake city, ut' },
  { label: 'San Antonio, TX', value: 'san antonio, tx' },
  { label: 'San Diego, CA', value: 'san diego, ca' },
  { label: 'San Francisco, CA', value: 'san francisco, ca' },
  { label: 'San Jose, CA', value: 'san jose, ca' },
  { label: 'Seattle, WA', value: 'seattle, wa' },
  { label: 'St. Louis, MO', value: 'st. louis, mo' },
  { label: 'Tampa, FL', value: 'tampa, fl' },
  { label: 'Tucson, AZ', value: 'tucson, az' },
  { label: 'Virginia Beach, VA', value: 'virginia beach, va' },
  { label: 'Washington, DC', value: 'washington, dc' },

  // --- International cities (alphabetical) ---
  { label: 'Accra, Ghana', value: 'accra, ghana' },
  { label: 'Amsterdam, Netherlands', value: 'amsterdam, netherlands' },
  { label: 'Bangkok, Thailand', value: 'bangkok, thailand' },
  { label: 'Barcelona, Spain', value: 'barcelona, spain' },
  { label: 'Berlin, Germany', value: 'berlin, germany' },
  { label: 'Bogota, Colombia', value: 'bogota, colombia' },
  { label: 'Buenos Aires, Argentina', value: 'buenos aires, argentina' },
  { label: 'Cape Town, South Africa', value: 'cape town, south africa' },
  { label: 'Dublin, Ireland', value: 'dublin, ireland' },
  { label: 'Glasgow, Scotland', value: 'glasgow, scotland' },
  { label: 'Hamburg, Germany', value: 'hamburg, germany' },
  { label: 'Ibiza, Spain', value: 'ibiza, spain' },
  { label: 'Istanbul, Turkey', value: 'istanbul, turkey' },
  { label: 'Jakarta, Indonesia', value: 'jakarta, indonesia' },
  { label: 'Kingston, Jamaica', value: 'kingston, jamaica' },
  { label: 'Lagos, Nigeria', value: 'lagos, nigeria' },
  { label: 'Lima, Peru', value: 'lima, peru' },
  { label: 'Lisbon, Portugal', value: 'lisbon, portugal' },
  { label: 'Manchester, UK', value: 'manchester, uk' },
  { label: 'Manila, Philippines', value: 'manila, philippines' },
  { label: 'Melbourne, Australia', value: 'melbourne, australia' },
  { label: 'Mexico City, Mexico', value: 'mexico city, mexico' },
  { label: 'Montreal, Canada', value: 'montreal, canada' },
  { label: 'Mumbai, India', value: 'mumbai, india' },
  { label: 'Nairobi, Kenya', value: 'nairobi, kenya' },
  { label: 'Paris, France', value: 'paris, france' },
  { label: 'Rio de Janeiro, Brazil', value: 'rio de janeiro, brazil' },
  { label: 'Sao Paulo, Brazil', value: 'sao paulo, brazil' },
  { label: 'Seoul, South Korea', value: 'seoul, south korea' },
  { label: 'Stockholm, Sweden', value: 'stockholm, sweden' },
  { label: 'Sydney, Australia', value: 'sydney, australia' },
  { label: 'Tokyo, Japan', value: 'tokyo, japan' },
  { label: 'Toronto, Canada', value: 'toronto, canada' },
  { label: 'Vancouver, Canada', value: 'vancouver, canada' },
];
