/**
 * Curated genre taxonomy for the GenrePicker component.
 * All lowercase, sorted alphabetically.
 */

export const GENRE_TAXONOMY: string[] = [
  'acid house',
  'afrobeats',
  'afropop',
  'alternative',
  'alternative r&b',
  'ambient',
  'amapiano',
  'americana',
  'bedroom pop',
  'blues',
  'bossa nova',
  'breakbeat',
  'britpop',
  'classical',
  'country',
  'dancehall',
  'dark pop',
  'deep house',
  'disco',
  'downtempo',
  'dream pop',
  'drill',
  'drum and bass',
  'dub',
  'dubstep',
  'edm',
  'electro',
  'electronic',
  'emo',
  'experimental',
  'folk',
  'funk',
  'garage rock',
  'grime',
  'grunge',
  'gospel',
  'hard rock',
  'hardcore',
  'hip hop',
  'house',
  'hyperpop',
  'indie',
  'indie folk',
  'indie pop',
  'indie rock',
  'j-pop',
  'jazz',
  'k-pop',
  'latin',
  'latin pop',
  'lo-fi',
  'metal',
  'metalcore',
  'neo-soul',
  'new wave',
  'noise',
  'pop',
  'pop punk',
  'pop rock',
  'post-punk',
  'progressive rock',
  'psychedelic rock',
  'punk',
  'r&b',
  'reggae',
  'reggaeton',
  'rock',
  'shoegaze',
  'singer-songwriter',
  'ska',
  'soul',
  'synthpop',
  'synthwave',
  'techno',
  'trance',
  'trap',
  'trip hop',
  'uk garage',
  'world',
];
