/**
 * @deprecated Import from @/components/organisms/table instead
 * Re-exports from organisms/table for backwards compatibility
 */
export {
  AudienceActionsCell,
  type AudienceActionsCellProps,
  AudienceCountryCell,
  type AudienceCountryCellProps,
  AudienceCreatedAtCell,
  type AudienceCreatedAtCellProps,
  AudienceDeviceCell,
  type AudienceDeviceCellProps,
  AudienceIdentificationIndicator,
  type AudienceIdentificationIndicatorProps,
  AudienceIntentScoreCell,
  type AudienceIntentScoreCellProps,
  AudienceLastActionCell,
  type AudienceLastActionCellProps,
  AudienceLastSeenCell,
  type AudienceLastSeenCellProps,
  AudienceLocationCell,
  type AudienceLocationCellProps,
  AudienceLtvCell,
  type AudienceLtvCellProps,
  AudienceMobileCard,
  type AudienceMobileCardProps,
  AudienceQuickActionsCell,
  type AudienceQuickActionsCellProps,
  AudienceReturningCell,
  type AudienceReturningCellProps,
  AudienceRowSelectionCell,
  type AudienceRowSelectionCellProps,
  AudienceSourceCell,
  type AudienceSourceCellProps,
  AudienceTouringBadge,
  type AudienceTouringBadgeProps,
  AudienceTypeBadge,
  type AudienceTypeBadgeProps,
  AudienceUserCell,
  type AudienceUserCellProps,
  AudienceVisitsCell,
  type AudienceVisitsCellProps,
} from '@/components/organisms/table';
