/**
 * Versioned public path for email-signature social icon PNGs.
 *
 * The PNGs are generated by `scripts/generate-email-signature-icons.ts` into
 * `public${EMAIL_SIGNATURE_ICON_BASE_PATH}/` and served as immutable static
 * assets at `${BASE_URL}${EMAIL_SIGNATURE_ICON_BASE_PATH}/<key>.png`.
 *
 * Kept dependency-free so both the runtime builder and the generator script
 * can import it without pulling env config.
 */

export const EMAIL_SIGNATURE_ICON_VERSION = 'v1';

export const EMAIL_SIGNATURE_ICON_BASE_PATH = `/email-signature/social-icons/generated/${EMAIL_SIGNATURE_ICON_VERSION}`;
