# CodeRabbit Configuration for Jovie
# See: https://docs.coderabbit.ai/reference/configuration

language: en-US
early_access: true

reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  collapse_walkthrough: true

  tools:
    biome:
      enabled: true
    eslint:
      enabled: false
    shellcheck:
      enabled: true
    actionlint:
      enabled: true

  auto_review:
    enabled: true
    drafts: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "[skip ci]"

  suggested_labels: true
  auto_apply_labels: true
  labeling_instructions:
    - label: "schema:drizzle"
      instructions: "Apply when the PR contains changes to drizzle/migrations/ directory. This indicates database migration changes that require careful review."
    - label: "schema:core"
      instructions: "Apply when the PR modifies lib/db/schema.ts. This is the core schema definition file."
    - label: "schema:migration-journal"
      instructions: "Apply when the PR modifies drizzle/migrations/meta/_journal.json. This is the migration tracking journal."
    - label: "area:cron"
      instructions: "Apply when the PR contains changes to app/api/cron/ directory. This affects scheduled background jobs."
    - label: "area:auth"
      instructions: "Apply when the PR modifies authentication-related files in app/(auth)/ or lib/auth/. This is security-sensitive code."
    - label: "area:env"
      instructions: "Apply when the PR modifies turbo.json build.env array, .env.example, or environment variable configuration. This affects deployment and configuration."

  path_instructions:
    # === DRIZZLE MIGRATION RULES (Enhanced) ===
    - path: "drizzle/migrations/**"
      instructions: |
        CRITICAL: Database migrations are IMMUTABLE. Review with extreme care.

        **BLOCKING Issues (must fix):**
        - CONCURRENTLY keyword is FORBIDDEN (Drizzle doesn't support it)
        - Missing IF NOT EXISTS for CREATE TABLE/INDEX
        - Missing IF EXISTS for DROP operations
        - Migration not registered in drizzle/migrations/_journal.json
        - Destructive operations (DROP TABLE, DROP COLUMN) without data backup plan
        - Renaming columns/tables (use add+migrate+drop pattern instead)

        **Required Patterns:**
        - All CREATE TABLE must use `IF NOT EXISTS`
        - All CREATE INDEX must use `IF NOT EXISTS`
        - Column additions should have DEFAULT values for non-nullable columns
        - Enum changes must use proper migration pattern (create new, migrate, drop old)

        **Naming Convention:**
        - File format: NNNN_description.sql (4-digit prefix)
        - Description should be kebab-case, max 50 chars

        **Journal Check:**
        - Verify _journal.json includes this migration with correct hash
        - Migrations must be append-only, never modify existing entries

    - path: "drizzle/migrations/_journal.json"
      instructions: |
        Migration journal is the source of truth.
        - Entries must be append-only - NEVER modify or remove existing entries
        - Each entry needs: idx, version, when, tag, breakpoints
        - Hash in 'tag' must match the actual migration file content
        - Indices must be sequential with no gaps

    - path: "lib/db/schema.ts"
      instructions: |
        Schema changes trigger blocking migration review.
        - Verify corresponding migrations exist
        - Check for proper types (jsonb over json, text over varchar)
        - Ensure RLS-compatible patterns are followed

    # === SECURITY RULES ===
    - path: "**/*.ts"
      instructions: |
        Security review checklist:

        **Hardcoded Secrets (BLOCKING):**
        - No API keys, tokens, or passwords in code
        - No hardcoded URLs with credentials
        - Environment variables must use process.env or publicEnv/serverEnv wrappers

        **Input Validation:**
        - User input must be validated before use
        - SQL queries must use parameterized queries (Drizzle handles this)
        - File paths from user input must be sanitized

        **Auth Checks:**
        - API routes must verify authentication
        - Server actions must check user permissions
        - Sensitive operations should have rate limiting

    - path: "app/api/**"
      instructions: |
        API Route Security:

        **Authentication (BLOCKING if missing):**
        - Must call auth() or getAuth() at route start
        - Must verify userId exists before processing
        - Must return 401/403 for unauthorized access

        **Input Handling:**
        - Validate request body with zod schema
        - Check Content-Type header for POST/PUT/PATCH
        - Sanitize any user-provided strings used in responses

        **Error Handling:**
        - Never expose internal error details to clients
        - Log errors with context but return generic messages
        - Use try/catch for async operations

    - path: "lib/db/**"
      instructions: |
        Database Security:

        **Query Safety:**
        - Never use raw SQL with string interpolation
        - Use Drizzle's query builder for all queries
        - Avoid sql.raw() unless absolutely necessary

        **Connection Security:**
        - Database URLs must come from environment variables
        - Never log connection strings or credentials

    # === AUTH/CLERK RULES ===
    - path: "app/(auth)/**"
      instructions: |
        Authentication code is high-risk.
        - Verify Clerk integration follows best practices
        - Check for proper session handling
        - Ensure no hardcoded credentials or tokens

    # === PAYMENT RULES ===
    - path: "app/api/stripe/**"
      instructions: |
        Payment code is high-risk.
        - Verify webhook signature validation
        - Check for proper error handling and idempotency
        - Confirm Node runtime (not Edge)

    # === MIDDLEWARE ===
    - path: "middleware.ts"
      instructions: |
        Middleware affects all routes.
        - Verify route matching is correct
        - Check for performance implications
        - Ensure proper Clerk middleware usage

    # === CORE FLOWS ===
    - path: "app/onboarding/**"
      instructions: |
        Onboarding is a core user flow.
        - Ensure flow completeness (name -> handle -> done)
        - Verify proper error states and validation
        - Check for proper Clerk user sync

    # === CI/CD ===
    - path: ".github/workflows/**"
      instructions: |
        CI/CD changes can break the deployment pipeline.
        - Verify job dependencies are correct
        - Check for proper secret handling
        - Ensure timeout values are appropriate
        - Validate concurrency settings

chat:
  auto_reply: true

# NOTE: Auto-labeling restored using correct schema (2025-12-24)
# Previous attempt used deprecated keys: 'auto_labeling', 'label_instructions'
# Correct keys are: 'suggested_labels', 'auto_apply_labels', 'labeling_instructions'
# See: https://docs.coderabbit.ai/reference/configuration

code_generation:
  unit_tests:
    enabled: true
    path_instructions:
      - path: "**/*.ts"
        instructions: |
          Use vitest for testing framework.
          Follow existing patterns in tests/ directory.
          Use @testing-library/react for React component tests.
          Mock external services with vi.mock().
          Include edge cases and error scenarios.
          Place tests in tests/ mirroring the source structure.
      - path: "app/api/**"
        instructions: |
          Test API routes with proper request/response mocking.
          Include auth scenarios (authenticated, unauthenticated, wrong user).
          Test error handling and edge cases.
      - path: "lib/db/**"
        instructions: |
          Mock database with vi.mock() for unit tests.
          Test query builders and business logic separately.

# Issue Planner: auto-generate code plans for Sentry issues
# When a GitHub issue with the "sentry" label is created (by Sentry alert rules),
# CodeRabbit will automatically analyze the codebase and generate an implementation plan.
# This plan is then picked up by .github/workflows/sentry-autofix.yml to trigger Claude.
issue_enrichment:
  auto_enrich:
    enabled: true

  planning:
    enabled: true
    auto_planning:
      enabled: true
      labels: ['sentry']

  labeling:
    auto_apply_labels: true
    labeling_instructions:
      - label: "sentry"
        instructions: "Apply to issues automatically created by Sentry alert rules. These contain production error reports with stack traces."
      - label: "ai:auto-fix"
        instructions: "Apply to Sentry issues that appear to be straightforward bugs fixable by an AI agent (null checks, missing imports, type errors, boundary violations)."
      - label: "ai:opt-out"
        instructions: "Apply to issues that touch high-risk areas (auth, payments, database migrations, middleware) and should NOT be auto-fixed."
