# CodeRabbit Configuration for Jovie
# See: https://docs.coderabbit.ai/reference/configuration

language: en-US
early_access: true

reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  collapse_walkthrough: true

  tools:
    biome:
      enabled: true
    eslint:
      enabled: false
    shellcheck:
      enabled: true
    actionlint:
      enabled: true

  auto_review:
    enabled: true
    drafts: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "[skip ci]"

  path_instructions:
    # === DRIZZLE MIGRATION RULES (Enhanced) ===
    - path: "drizzle/migrations/**"
      instructions: |
        CRITICAL: Database migrations are IMMUTABLE. Review with extreme care.

        **BLOCKING Issues (must fix):**
        - CONCURRENTLY keyword is FORBIDDEN (Drizzle doesn't support it)
        - Missing IF NOT EXISTS for CREATE TABLE/INDEX
        - Missing IF EXISTS for DROP operations
        - Migration not registered in drizzle/migrations/_journal.json
        - Destructive operations (DROP TABLE, DROP COLUMN) without data backup plan
        - Renaming columns/tables (use add+migrate+drop pattern instead)

        **Required Patterns:**
        - All CREATE TABLE must use `IF NOT EXISTS`
        - All CREATE INDEX must use `IF NOT EXISTS`
        - Column additions should have DEFAULT values for non-nullable columns
        - Enum changes must use proper migration pattern (create new, migrate, drop old)

        **Naming Convention:**
        - File format: NNNN_description.sql (4-digit prefix)
        - Description should be kebab-case, max 50 chars

        **Journal Check:**
        - Verify _journal.json includes this migration with correct hash
        - Migrations must be append-only, never modify existing entries

    - path: "drizzle/migrations/_journal.json"
      instructions: |
        Migration journal is the source of truth.
        - Entries must be append-only - NEVER modify or remove existing entries
        - Each entry needs: idx, version, when, tag, breakpoints
        - Hash in 'tag' must match the actual migration file content
        - Indices must be sequential with no gaps

    - path: "lib/db/schema.ts"
      instructions: |
        Schema changes trigger blocking migration review.
        - Verify corresponding migrations exist
        - Check for proper types (jsonb over json, text over varchar)
        - Ensure RLS-compatible patterns are followed

    # === SECURITY RULES ===
    - path: "**/*.ts"
      instructions: |
        Security review checklist:

        **Hardcoded Secrets (BLOCKING):**
        - No API keys, tokens, or passwords in code
        - No hardcoded URLs with credentials
        - Environment variables must use process.env or publicEnv/serverEnv wrappers

        **Input Validation:**
        - User input must be validated before use
        - SQL queries must use parameterized queries (Drizzle handles this)
        - File paths from user input must be sanitized

        **Auth Checks:**
        - API routes must verify authentication
        - Server actions must check user permissions
        - Sensitive operations should have rate limiting

    - path: "app/api/**"
      instructions: |
        API Route Security:

        **Authentication (BLOCKING if missing):**
        - Must call auth() or getAuth() at route start
        - Must verify userId exists before processing
        - Must return 401/403 for unauthorized access

        **Input Handling:**
        - Validate request body with zod schema
        - Check Content-Type header for POST/PUT/PATCH
        - Sanitize any user-provided strings used in responses

        **Error Handling:**
        - Never expose internal error details to clients
        - Log errors with context but return generic messages
        - Use try/catch for async operations

    - path: "lib/db/**"
      instructions: |
        Database Security:

        **Query Safety:**
        - Never use raw SQL with string interpolation
        - Use Drizzle's query builder for all queries
        - Avoid sql.raw() unless absolutely necessary

        **Connection Security:**
        - Database URLs must come from environment variables
        - Never log connection strings or credentials

    # === AUTH/CLERK RULES ===
    - path: "app/(auth)/**"
      instructions: |
        Authentication code is high-risk.
        - Verify Clerk integration follows best practices
        - Check for proper session handling
        - Ensure no hardcoded credentials or tokens

    # === PAYMENT RULES ===
    - path: "app/api/stripe/**"
      instructions: |
        Payment code is high-risk.
        - Verify webhook signature validation
        - Check for proper error handling and idempotency
        - Confirm Node runtime (not Edge)

    # === MIDDLEWARE ===
    - path: "middleware.ts"
      instructions: |
        Middleware affects all routes.
        - Verify route matching is correct
        - Check for performance implications
        - Ensure proper Clerk middleware usage

    # === CORE FLOWS ===
    - path: "app/onboarding/**"
      instructions: |
        Onboarding is a core user flow.
        - Ensure flow completeness (name -> handle -> done)
        - Verify proper error states and validation
        - Check for proper Clerk user sync

    # === CI/CD ===
    - path: ".github/workflows/**"
      instructions: |
        CI/CD changes can break the deployment pipeline.
        - Verify job dependencies are correct
        - Check for proper secret handling
        - Ensure timeout values are appropriate
        - Validate concurrency settings

chat:
  auto_reply: true

# === AI AUTOMATION LABELS ===
# Auto-label PRs based on review findings to trigger GitHub Actions workflows
auto_labeling:
  # Auto-fix candidates (safe, mechanical fixes)
  - condition: "review.issues.severity in ['info', 'style'] and review.issues.count < 10"
    labels: ["ai:auto-fix"]
    comment: "ðŸ¤– This PR has minor review findings that can be auto-fixed. Adding `ai:auto-fix` label to trigger automatic fixes."

  # Needs manual review (complex issues)
  - condition: "review.issues.severity in ['warning', 'error']"
    labels: ["ai:needs-review"]
    comment: "âš ï¸ This PR has important review findings that need human attention."

  # Protected paths - no auto-fix (migrations, auth, payments)
  - condition: "files.any(f => f.path.startsWith('drizzle/migrations/') || f.path.includes('auth') || f.path.includes('payment') || f.path.includes('billing'))"
    labels: ["ai:opt-out"]
    comment: "ðŸ”’ This PR modifies protected paths (migrations/auth/payments). AI automation disabled for safety."

  # Clean PRs eligible for auto-merge
  - condition: "pull_request.user.login in ['dependabot[bot]', 'github-actions[bot]'] || (review.issues.count == 0 && !files.any(f => f.path.startsWith('drizzle/migrations/')))"
    labels: ["automerge"]
    comment: "âœ… PR eligible for auto-merge. Will merge once all checks pass."

# Label-specific instructions for AI agents
label_instructions:
  "ai:auto-fix":
    instructions: |
      Focus on safe, mechanical fixes ONLY. These changes should be zero-risk:

      **ALLOWED AUTO-FIXES:**
      - Code formatting (Biome/Prettier)
      - Linting issues (ESLint rules)
      - Simple type errors (TypeScript)
      - Import organization and unused imports
      - Unused variable removal
      - Missing return types
      - Consistent quote styles

      **NEVER AUTO-FIX:**
      - Logic errors or algorithmic changes
      - Security issues (flag for human review)
      - Database migrations
      - Authentication/authorization code
      - Payment processing code
      - API contracts (breaking changes)
      - Performance optimizations requiring testing

      **VERIFICATION REQUIRED:**
      - Run full typecheck after fixes
      - Run linting after fixes
      - Run affected unit tests
      - Verify no new CodeRabbit issues introduced

  "ai:needs-review":
    instructions: |
      Provide detailed review focusing on correctness and safety:

      **REVIEW CHECKLIST:**
      - Logic correctness and edge cases
      - Security vulnerabilities (OWASP Top 10)
      - Performance implications (N+1 queries, memory leaks)
      - Error handling completeness
      - Test coverage gaps
      - Breaking changes and migration paths
      - Accessibility compliance (WCAG)

      **HIGHLIGHT:**
      - Any suspicious patterns
      - Missing validation
      - Potential race conditions
      - Unclear naming or documentation needs

  "ai:opt-out":
    instructions: |
      This PR touches protected code paths that require expert human review.

      **NO AUTOMATION ALLOWED:**
      - Do not attempt auto-fixes
      - Do not auto-merge
      - Escalate complex issues to senior developers

      **EXTRA SCRUTINY:**
      - Database migrations must follow strict patterns
      - Auth changes must maintain security guarantees
      - Payment code must preserve idempotency
      - All changes must have explicit human approval

# On-demand unit test generation
# Usage: Comment "@coderabbitai generate unit tests" on any PR
code_generation:
  unit_tests:
    enabled: true
    path_instructions:
      - path: "**/*.ts"
        instructions: |
          Use vitest for testing framework.
          Follow existing patterns in tests/ directory.
          Use @testing-library/react for React component tests.
          Mock external services with vi.mock().
          Include edge cases and error scenarios.
          Place tests in tests/ mirroring the source structure.
      - path: "app/api/**"
        instructions: |
          Test API routes with proper request/response mocking.
          Include auth scenarios (authenticated, unauthenticated, wrong user).
          Test error handling and edge cases.
      - path: "lib/db/**"
        instructions: |
          Mock database with vi.mock() for unit tests.
          Test query builders and business logic separately.
