// AUTO-GENERATED by apps/web/scripts/generate-audio-transcription-swift.ts.
// Run: pnpm --filter @jovie/web audio:transcription:swift
// Do not edit by hand.

import Foundation

enum AudioTranscriptionStatus: String, CaseIterable, Codable, Sendable {
  case idle = "idle"
  case requestingPermission = "requesting-permission"
  case listening = "listening"
  case partial = "partial"
  case processing = "processing"
  case completed = "completed"
  case empty = "empty"
  case cancelled = "cancelled"
  case failed = "failed"
  case unsupported = "unsupported"
}

enum AudioTranscriptionEvent: String, CaseIterable, Codable, Sendable {
  case permissionRequested = "permission-requested"
  case captureStarted = "capture-started"
  case partialResult = "partial-result"
  case captureStopped = "capture-stopped"
  case finalResult = "final-result"
  case emptyResult = "empty-result"
  case cancel = "cancel"
  case fail = "fail"
  case unsupported = "unsupported"
  case reset = "reset"
}

enum AudioTranscriptionSource: String, CaseIterable, Codable, Sendable {
  case provided = "provided"
  case captions = "captions"
  case speechRecognition = "speech-recognition"
  case none = "none"
}

enum AudioTranscriptionExecution: String, CaseIterable, Codable, Sendable {
  case provided = "provided"
  case onDevice = "on-device"
  case network = "network"
  case providerManaged = "provider-managed"
  case unavailable = "unavailable"
}

enum AudioTranscriptionErrorCode: String, CaseIterable, Codable, Sendable {
  case permissionDenied = "permission-denied"
  case serviceNotAllowed = "service-not-allowed"
  case audioCapture = "audio-capture"
  case noSpeech = "no-speech"
  case network = "network"
  case aborted = "aborted"
  case unavailable = "unavailable"
  case emptyTranscript = "empty-transcript"
  case unknown = "unknown"
}

enum AudioTranscriptionProviderID: String, CaseIterable, Codable, Sendable {
  case user = "user"
  case youtubeCaptions = "youtube-captions"
  case webSpeech = "web-speech"
  case appleSpeech = "apple-speech"
  case serverAsr = "server-asr"
  case none = "none"
}

func nextAudioTranscriptionStatus(
  _ current: AudioTranscriptionStatus,
  event: AudioTranscriptionEvent
) -> AudioTranscriptionStatus {
  switch (current, event) {
  case (.idle, .permissionRequested):
    return .requestingPermission
  case (.idle, .captureStarted):
    return .listening
  case (.idle, .unsupported):
    return .unsupported
  case (.requestingPermission, .captureStarted):
    return .listening
  case (.requestingPermission, .cancel):
    return .cancelled
  case (.requestingPermission, .fail):
    return .failed
  case (.requestingPermission, .unsupported):
    return .unsupported
  case (.requestingPermission, .reset):
    return .idle
  case (.listening, .partialResult):
    return .partial
  case (.listening, .captureStopped):
    return .processing
  case (.listening, .finalResult):
    return .completed
  case (.listening, .emptyResult):
    return .empty
  case (.listening, .cancel):
    return .cancelled
  case (.listening, .fail):
    return .failed
  case (.listening, .reset):
    return .idle
  case (.partial, .captureStopped):
    return .processing
  case (.partial, .finalResult):
    return .completed
  case (.partial, .emptyResult):
    return .empty
  case (.partial, .cancel):
    return .cancelled
  case (.partial, .fail):
    return .failed
  case (.partial, .reset):
    return .idle
  case (.processing, .finalResult):
    return .completed
  case (.processing, .emptyResult):
    return .empty
  case (.processing, .cancel):
    return .cancelled
  case (.processing, .fail):
    return .failed
  case (.processing, .reset):
    return .idle
  case (.completed, .reset):
    return .idle
  case (.empty, .reset):
    return .idle
  case (.cancelled, .reset):
    return .idle
  case (.failed, .reset):
    return .idle
  case (.unsupported, .reset):
    return .idle
  default:
    return current
  }
}

struct AudioTranscriptionProvenance: Equatable, Codable, Sendable {
  let source: AudioTranscriptionSource
  let provider: AudioTranscriptionProviderID
  let execution: AudioTranscriptionExecution
  let locale: String?
  let modelID: String?
}
