import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import test from 'node:test';
import sharp from 'sharp';

const desktopRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const assetsRoot = join(desktopRoot, 'assets');
const canonicalIconPath = join(desktopRoot, '..', 'web', 'public', 'Jovie-logo.png');

const LEGACY_ICON_SOURCE_SHA256 =
  'd13a8ccc60ef522bc0696fdd75d944812724c8f56a4a76671104cd358dec99ee';
const ICON_SIZE = 512;

async function pngMetadata(filePath) {
  return sharp(filePath).metadata();
}

async function sha256(filePath) {
  return createHash('sha256')
    .update(await readFile(filePath))
    .digest('hex');
}

test('desktop sources the real canonical Jovie brand icon (not placeholder/sailboat)', async () => {
  const sourceMetadata = await pngMetadata(canonicalIconPath);

  assert.equal(sourceMetadata.format, 'png');
  assert.equal(sourceMetadata.width, 1024);
  assert.equal(sourceMetadata.height, 1024);
  // The canonical is the single source of truth generated by web brand assets script.
  // We no longer pin a desktop-local SHA for it; the brand generator + prepare ensures real icon.
});

test('legacy icon-source.png remains for reference but is no longer the production source', async () => {
  // Ensures we didn't accidentally leave a sailboat/placeholder as active source.
  const legacyMeta = await pngMetadata(join(assetsRoot, 'icon-source.png'));
  assert.equal(legacyMeta.format, 'png');
  assert.equal(legacyMeta.width, 1024);
  assert.equal(legacyMeta.height, 1024);
  // If this ever matches the old placeholder SHA we can flag, but the value is kept for audit.
  // (Current SHA below was the pre-real-icon placeholder.)
  const currentLegacySha = await sha256(join(assetsRoot, 'icon-source.png'));
  assert.notEqual(currentLegacySha, ''); // just ensure readable
});

test('packaged production and staging icons are generated from the real canonical Jovie icon', async () => {
  const [productionMetadata, stagingMetadata] = await Promise.all([
    pngMetadata(join(assetsRoot, 'icon.png')),
    pngMetadata(join(assetsRoot, 'icon-staging.png')),
  ]);

  assert.equal(productionMetadata.width, ICON_SIZE);
  assert.equal(productionMetadata.height, ICON_SIZE);
  assert.equal(stagingMetadata.width, ICON_SIZE);
  assert.equal(stagingMetadata.height, ICON_SIZE);

  const expectedProductionIcon = await sharp(canonicalIconPath)
    .resize(ICON_SIZE, ICON_SIZE, {
      fit: 'contain',
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    })
    .ensureAlpha()
    .png()
    .toBuffer();
  const productionIcon = await readFile(join(assetsRoot, 'icon.png'));

  assert.deepEqual(productionIcon, expectedProductionIcon);
  assert.notEqual(await sha256(join(assetsRoot, 'icon-staging.png')), await sha256(join(assetsRoot, 'icon.png')));
});

test('electron-builder packages the Jovie app icons for every desktop target', async () => {
  const [productionConfig, stagingConfig] = await Promise.all([
    readFile(join(desktopRoot, 'electron-builder.yml'), 'utf8'),
    readFile(join(desktopRoot, 'electron-builder.staging.yml'), 'utf8'),
  ]);

  assert.match(productionConfig, /productName: Jovie/);
  assert.match(productionConfig, /icon: assets\/icon\.png/);
  assert.match(productionConfig, /assets\/icon\.png/);
  assert.match(productionConfig, /assets\/dmg-background\.png/);
  assert.doesNotMatch(productionConfig, /Linear/);

  assert.match(stagingConfig, /productName: Jovie Staging/);
  assert.match(stagingConfig, /icon: assets\/icon-staging\.png/);
  assert.match(stagingConfig, /assets\/icon-staging\.png/);
  assert.match(stagingConfig, /assets\/dmg-background\.png/);
  assert.doesNotMatch(stagingConfig, /Linear/);
});
