#!/usr/bin/env node
/**
 * Bakes APP_ENV into the TypeScript source at build time so that
 * the value is a compile-time constant in the packaged binary.
 *
 * Usage (called automatically via pre* npm hooks):
 *   node scripts/write-env.mjs
 *
 * Reads:  ELECTRON_ENV env var (defaults to 'production' if absent/invalid)
 *         ELECTRON_APP_URL for local development (loopback only)
 * Writes: src/env.generated.ts
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const raw = process.env.ELECTRON_ENV;
const appEnv = raw === 'staging' || raw === 'local' ? raw : 'production';

function resolveAppUrl(env) {
  if (env === 'staging') {
    return 'https://staging.jov.ie';
  }

  if (env === 'local') {
    const localUrl = process.env.ELECTRON_APP_URL || 'http://localhost:3112';
    let parsed;
    try {
      parsed = new URL(localUrl);
    } catch {
      throw new Error(
        'ELECTRON_APP_URL for ELECTRON_ENV=local must be an http loopback URL.'
      );
    }
    // WHATWG URL keeps the brackets on IPv6 hostnames ('[::1]').
    const hostname = parsed.hostname.replace(/^\[|\]$/g, '');
    const isLoopback =
      hostname === 'localhost' ||
      hostname === '127.0.0.1' ||
      hostname === '::1';

    if (parsed.protocol !== 'http:' || !isLoopback) {
      throw new Error(
        'ELECTRON_APP_URL for ELECTRON_ENV=local must be an http loopback URL.'
      );
    }

    return parsed.origin;
  }

  return 'https://jov.ie';
}

const appUrl = resolveAppUrl(appEnv);

const content = `// AUTO-GENERATED by scripts/write-env.mjs — do not edit by hand.
// Re-generated on every \`predev\`, \`prebuild:staging\`, and \`prebuild:production\` run.
export const APP_ENV: 'production' | 'staging' | 'local' = '${appEnv}';
export const APP_URL = '${appUrl}';
`;

const outPath = join(__dirname, '..', 'src', 'env.generated.ts');
writeFileSync(outPath, content, 'utf8');
console.log(
  `[write-env] Wrote APP_ENV='${appEnv}' APP_URL='${appUrl}' to src/env.generated.ts`
);
