#!/usr/bin/env node
/**
 * Bakes APP_ENV into the TypeScript source at build time so that
 * the value is a compile-time constant in the packaged binary.
 *
 * Usage (called automatically via pre* npm hooks):
 *   node scripts/write-env.mjs
 *
 * Reads:  ELECTRON_ENV env var (defaults to 'production' if absent/invalid)
 * Writes: src/env.generated.ts
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const raw = process.env.ELECTRON_ENV;
const appEnv = raw === 'staging' ? 'staging' : 'production';

const content = `// AUTO-GENERATED by scripts/write-env.mjs — do not edit by hand.
// Re-generated on every \`predev\`, \`prebuild:staging\`, and \`prebuild:production\` run.
export const APP_ENV: 'production' | 'staging' = '${appEnv}';
`;

const outPath = join(__dirname, '..', 'src', 'env.generated.ts');
writeFileSync(outPath, content, 'utf8');
console.log(`[write-env] Wrote APP_ENV='${appEnv}' to src/env.generated.ts`);
