// design-sync CSS builder for the homepage surface.
//
// The homepage uses the same Tailwind v4 token system as the rest of apps/web:
// tokens live in apps/web/styles/design-system.css + theme.css (both @imported
// by globals.css), utilities are generated by Tailwind, and the homepage's own
// layout classes (.homepage-*, .home-*, .system-b-mounted-*) live in
// apps/web/app/(home)/home.css (plain CSS, no Tailwind directives).
//
// This script reproduces that compile into ONE static stylesheet for Claude
// Design so previews render with the real Jovie dark (carbon) styling:
//
// 1. Compile globals.css with the app's own @tailwindcss/postcss (resolved from
//    apps/web/node_modules via createRequire). Tailwind v4 inlines the @imported
//    design-system.css / theme.css token sheets itself.
// 2. Scope utility generation with `@import "tailwindcss" source(none)` + explicit
//    @source dirs for the homepage component trees (paths are relative to
//    globals.css at apps/web/app/, so `../components/...`). Also scans
//    .design-sync/previews so authored-preview utility classes are generated.
// 3. Append the raw home.css so the homepage's custom layout classes ship.
// 4. Rewrite :root.dark -> :root:root so the carbon dark look is the preview
//    default (cards render as bare HTML, not <html class="dark">).
// 5. Define --font-inter / --font-satoshi statically (next/font injects these at
//    runtime in the app; @font-face rules are in fonts.css via cfg.extraFonts).
//
// Output: apps/web/.ds-design-sync-home.css (gitignored; regenerated on every
// sync). Referenced by cfg.cssEntry. Re-run via cfg.buildCmd.

import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const requireWeb = createRequire(path.join(root, 'apps/web/package.json'));
const postcss = requireWeb('postcss');
const tailwind = requireWeb('@tailwindcss/postcss');

const globals = path.join(root, 'apps/web/app/globals.css');
const homeCss = path.join(root, 'apps/web/app/(home)/home.css');
const out = path.join(root, 'apps/web/.ds-design-sync-home.css');

// Scope source detection to the homepage trees: replace `@import "tailwindcss"`
// with the source(none) variant so Tailwind only emits utilities for classes in
// the dirs we name (not the full app). Paths are relative to globals.css's own
// location (apps/web/app/).
let css = fs
  .readFileSync(globals, 'utf8')
  .replace(
    /@import\s+"tailwindcss"\s*;/,
    '@import "tailwindcss" source(none);'
  );

css += '\n@source "../components/homepage";\n';
css += '@source "../components/features/home";\n';
css += '@source "../components/marketing";\n';
css += '@source "../app/(home)";\n';
// Authored design-sync previews (so utility classes used in preview cards are
// generated). Relative to apps/web/app/ -> repo-root/.design-sync/previews.
css += '@source "../../../.design-sync/previews";\n';

const result = await postcss([tailwind()]).process(css, {
  from: globals,
  to: out,
});

// Flip dark to default: :root.dark -> :root:root (same specificity trick the
// marketing sync uses). Preview cards render with the carbon dark identity.
let s = result.css.replace(/:root\.dark/g, ':root:root');

// Append the homepage's own layout stylesheet (plain CSS, no Tailwind syntax).
const home = fs.readFileSync(homeCss, 'utf8');
s += `\n/* === apps/web/app/(home)/home.css === */\n${home}\n`;

// Define font CSS variables statically (next/font injects these at runtime in
// the app; @font-face rules ship via cfg.extraFonts / fonts.css).
s +=
  '\n/* design-sync: next/font vars defined statically for preview rendering */\n' +
  ":root:root{--font-inter:'Inter',system-ui,sans-serif;--font-satoshi:'Satoshi',system-ui,sans-serif;}\n";

fs.writeFileSync(out, s);
console.log(
  `wrote ${path.relative(root, out)} (${(s.length / 1024).toFixed(0)} KB)`
);
