// Generate self-contained data-URI thumbnails for the image-dependent homepage
// previews (hero command center, workspace, artist-profiles carousel).
//
// Why data URIs: preview cards render in a sandboxed browser (local render check
// + claude.ai/design) where external image URLs (jov.ie/product-screenshots/…)
// do not reliably load. Inlining downscaled webp thumbnails makes every preview
// fully self-contained — the design-sync principle. Source PNGs are the repo's
// own committed marketing screenshots (apps/web/public/product-screenshots/).
//
// Output: .design-sync/previews/_images.ts (gitignored; regenerated by buildCmd
// before each converter build, so a fresh clone reproduces it from the assets).

import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const requireWeb = createRequire(path.join(root, 'apps/web/package.json'));
const sharp = requireWeb('sharp');

const SHOTS = path.join(root, 'apps/web/public/product-screenshots');
const out = path.join(root, '.design-sync/previews/_images.ts');

// key → { file, alt, width (downscale target) }. Desktop shots → 520w, phones → 280w.
const MAP = {
  library: { file: 'shell-v1-library.png', alt: 'Library workspace', w: 520 },
  releases: {
    file: 'shell-v1-releases.png',
    alt: 'Releases workspace',
    w: 520,
  },
  release: { file: 'release-deep-end-phone.png', alt: 'Release page', w: 280 },
  profilePay: {
    file: 'tim-white-profile-pay-phone.png',
    alt: 'Get paid — artist profile',
    w: 280,
  },
  profileListen: {
    file: 'tim-white-profile-listen-phone.png',
    alt: 'Drive streams — artist profile',
    w: 280,
  },
  profileSubscribe: {
    file: 'tim-white-profile-subscribe-phone.png',
    alt: 'Capture fans — artist profile',
    w: 280,
  },
  profileTour: {
    file: 'tim-white-profile-tour-phone.png',
    alt: 'Sell out — artist profile',
    w: 280,
  },
  profilePresave: {
    file: 'tim-white-profile-presave-phone.png',
    alt: 'Drop music — artist profile',
    w: 280,
  },
};

const entries = {};
for (const [key, { file, alt, w }] of Object.entries(MAP)) {
  const src = path.join(SHOTS, file);
  const pipeline = sharp(src).resize({ width: w, withoutEnlargement: true });
  const buf = await pipeline.webp({ quality: 72 }).toBuffer();
  const meta = await sharp(buf).metadata();
  entries[key] = {
    publicUrl: `data:image/webp;base64,${buf.toString('base64')}`,
    width: meta.width,
    height: meta.height,
    alt,
  };
}

// Public-asset map: components that render `<Image src="/public/path">` (e.g. the
// Black Hole label logo) can't load that path in the preview sandbox. gen emits a
// data-URI map; prebuild injects it as globalThis.__DS_PUBLIC_ASSETS and the
// next/image stub resolves srcs through it.
const PUBLIC_ASSETS = {
  '/brand-logos/black-hole-recordings.png': {
    file: 'brand-logos/black-hole-recordings.png',
    w: 200,
  },
};
const publicMap = {};
for (const [url, { file, w }] of Object.entries(PUBLIC_ASSETS)) {
  const buf = await sharp(path.join(root, 'apps/web/public', file))
    .resize({ width: w, withoutEnlargement: true })
    .webp({ quality: 80 })
    .toBuffer();
  publicMap[url] = `data:image/webp;base64,${buf.toString('base64')}`;
}
fs.mkdirSync(path.join(root, '.design-sync/dist'), { recursive: true });
fs.writeFileSync(
  path.join(root, '.design-sync/dist/public-assets.json'),
  JSON.stringify(publicMap)
);

const body = `// AUTO-GENERATED by .design-sync/gen-images.mjs — do not edit.
// Downscaled webp data-URI thumbnails of the repo's marketing screenshots, so
// image-dependent homepage previews render self-contained (no network).
export interface PreviewImage {
  readonly publicUrl: string;
  readonly width: number;
  readonly height: number;
  readonly alt: string;
}

export const IMG: Record<${Object.keys(MAP)
  .map(k => `'${k}'`)
  .join(' | ')}, PreviewImage> = ${JSON.stringify(entries, null, 2)};
`;

fs.writeFileSync(out, body);
const kb = (body.length / 1024).toFixed(0);
console.log(
  `gen-images: wrote .design-sync/previews/_images.ts (${kb} KB, ${Object.keys(entries).length} images)`
);
