import type { ScreenshotScenario } from './types';

export const SCREENSHOT_VIEWPORTS = {
  desktop: { width: 1440, height: 900 },
  mobile: { width: 390, height: 844 },
} as const;

export const SCREENSHOT_SCENARIOS: readonly ScreenshotScenario[] = [
  {
    id: 'marketing-home-desktop',
    title: 'Homepage',
    group: 'marketing',
    groupLabel: 'Marketing',
    route: '/',
    waitFor: 'main',
    viewport: 'desktop',
    theme: 'dark',
    consumers: ['admin', 'investor-ready'],
    fullPage: false,
  },
  {
    id: 'dashboard-releases-desktop',
    title: 'Releases Dashboard',
    group: 'dashboard',
    groupLabel: 'Dashboard',
    route: '/demo',
    waitFor: '[data-testid="releases-matrix"]',
    viewport: 'desktop',
    theme: 'dark',
    consumers: ['admin', 'marketing-export', 'investor-ready'],
    fullPage: false,
    publicExportPath: 'releases-dashboard-full.png',
  },
  {
    id: 'dashboard-releases-sidebar-desktop',
    title: 'Releases With Sidebar',
    group: 'dashboard',
    groupLabel: 'Dashboard',
    route: '/demo',
    waitFor: '[data-testid="release-sidebar"]',
    viewport: 'desktop',
    theme: 'dark',
    consumers: ['admin', 'marketing-export', 'investor-ready'],
    fullPage: false,
    interaction: 'open-first-release',
    publicExportPath: 'releases-dashboard-sidebar.png',
  },
  {
    id: 'dashboard-release-sidebar-detail-desktop',
    title: 'Release Sidebar Detail',
    group: 'dashboard',
    groupLabel: 'Dashboard',
    route: '/demo',
    waitFor: '[data-testid="release-sidebar"]',
    viewport: 'desktop',
    theme: 'dark',
    consumers: ['admin', 'marketing-export', 'investor-ready'],
    fullPage: false,
    captureTarget: 'locator',
    captureSelector: '[data-testid="release-sidebar"]',
    interaction: 'open-first-release',
    publicExportPath: 'release-sidebar-detail.png',
  },
  {
    id: 'dashboard-audience-desktop',
    title: 'Audience CRM',
    group: 'dashboard',
    groupLabel: 'Dashboard',
    route: '/demo/audience',
    waitFor: 'table, [role="grid"], [data-testid="unified-table"]',
    viewport: 'desktop',
    theme: 'dark',
    consumers: ['admin', 'marketing-export', 'investor-ready'],
    fullPage: false,
    publicExportPath: 'audience-crm.png',
  },
  {
    id: 'dashboard-analytics-desktop',
    title: 'Analytics Overview',
    group: 'dashboard',
    groupLabel: 'Dashboard',
    route: '/demo/showcase/analytics',
    waitFor: '[data-testid="demo-showcase-analytics"]',
    viewport: 'desktop',
    theme: 'dark',
    consumers: ['admin', 'investor-ready'],
    fullPage: false,
  },
  {
    id: 'dashboard-earnings-desktop',
    title: 'Earnings Overview',
    group: 'dashboard',
    groupLabel: 'Dashboard',
    route: '/demo/showcase/earnings',
    waitFor: '[data-testid="demo-showcase-earnings"]',
    viewport: 'desktop',
    theme: 'dark',
    consumers: ['admin', 'investor-ready'],
    fullPage: false,
  },
  {
    id: 'settings-profile-desktop',
    title: 'Artist Profile Settings',
    group: 'settings',
    groupLabel: 'Settings',
    route: '/demo/showcase/settings',
    waitFor: '[data-testid="demo-showcase-settings"]',
    viewport: 'desktop',
    theme: 'dark',
    consumers: ['admin'],
    fullPage: false,
  },
  {
    id: 'settings-links-desktop',
    title: 'Links Manager',
    group: 'settings',
    groupLabel: 'Settings',
    route: '/demo/showcase/links',
    waitFor: '[data-testid="demo-showcase-links"]',
    viewport: 'desktop',
    theme: 'dark',
    consumers: ['admin', 'investor-ready'],
    fullPage: false,
  },
  {
    id: 'onboarding-handle-desktop',
    title: 'Onboarding Handle Step',
    group: 'onboarding',
    groupLabel: 'Onboarding',
    route: '/demo/showcase/onboarding-handle',
    waitFor: '#handle-input',
    viewport: 'desktop',
    theme: 'dark',
    consumers: ['admin', 'investor-ready'],
    fullPage: false,
  },
  {
    id: 'onboarding-dsp-desktop',
    title: 'Onboarding DSP Step',
    group: 'onboarding',
    groupLabel: 'Onboarding',
    route: '/demo/showcase/onboarding-dsp',
    waitFor: 'input[placeholder*="Spotify link"]',
    viewport: 'desktop',
    theme: 'dark',
    consumers: ['admin', 'investor-ready'],
    fullPage: false,
  },
  {
    id: 'onboarding-profile-review-desktop',
    title: 'Onboarding Profile Review',
    group: 'onboarding',
    groupLabel: 'Onboarding',
    route: '/demo/showcase/onboarding-profile-review',
    waitFor: 'text=Continue to Dashboard',
    viewport: 'desktop',
    theme: 'dark',
    consumers: ['admin', 'investor-ready'],
    fullPage: false,
  },
  {
    id: 'public-profile-desktop',
    title: 'Public Profile',
    group: 'public-profile',
    groupLabel: 'Public Profile',
    route: '/e2e-test-user',
    waitFor: '[data-testid="profile-header"], h1, main img[alt]:visible',
    viewport: 'desktop',
    theme: 'dark',
    consumers: ['admin', 'marketing-export', 'investor-ready'],
    fullPage: false,
    publicExportPath: 'profile-desktop.png',
  },
  {
    id: 'public-profile-mobile',
    title: 'Public Profile Mobile',
    group: 'public-profile',
    groupLabel: 'Public Profile',
    route: '/e2e-test-user',
    waitFor: '[data-testid="profile-header"], h1, main img[alt]:visible',
    viewport: 'mobile',
    theme: 'dark',
    consumers: ['admin', 'marketing-export', 'investor-ready'],
    fullPage: false,
    publicExportPath: 'profile-phone.png',
  },
] as const;

export const SCREENSHOT_SCENARIO_IDS = new Set(
  SCREENSHOT_SCENARIOS.map(scenario => scenario.id)
);

export function getScreenshotScenario(id: string): ScreenshotScenario | null {
  return SCREENSHOT_SCENARIOS.find(scenario => scenario.id === id) ?? null;
}
