import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  AUDIO_TRANSCRIPTION_ERROR_CODES,
  AUDIO_TRANSCRIPTION_EVENTS,
  AUDIO_TRANSCRIPTION_EXECUTIONS,
  AUDIO_TRANSCRIPTION_PROVIDER_IDS,
  AUDIO_TRANSCRIPTION_SOURCES,
  AUDIO_TRANSCRIPTION_STATUSES,
  getNextAudioTranscriptionStatus,
} from '@jovie/audio-contracts';

const outputPath = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../../ios/Jovie/Core/AudioTranscriptionContract.generated.swift'
);

function swiftCase(value: string) {
  return value.replace(/-([a-z])/g, (_, character: string) =>
    character.toUpperCase()
  );
}

function renderEnum(name: string, values: readonly string[]) {
  const cases = values
    .map(value => `  case ${swiftCase(value)} = "${value}"`)
    .join('\n');
  return `enum ${name}: String, CaseIterable, Codable, Sendable {\n${cases}\n}`;
}

function renderTransitionFunction() {
  const transitions = AUDIO_TRANSCRIPTION_STATUSES.flatMap(status =>
    AUDIO_TRANSCRIPTION_EVENTS.flatMap(event => {
      const next = getNextAudioTranscriptionStatus(status, event);
      return next === status
        ? []
        : [
            `  case (.${swiftCase(status)}, .${swiftCase(event)}):\n    return .${swiftCase(next)}`,
          ];
    })
  ).join('\n');

  return `func nextAudioTranscriptionStatus(
  _ current: AudioTranscriptionStatus,
  event: AudioTranscriptionEvent
) -> AudioTranscriptionStatus {
  switch (current, event) {
${transitions}
  default:
    return current
  }
}`;
}

export function renderSwiftTranscriptionContract() {
  return `// AUTO-GENERATED by apps/web/scripts/generate-audio-transcription-swift.ts.
// Run: pnpm --filter @jovie/web audio:transcription:swift
// Do not edit by hand.

import Foundation

${renderEnum('AudioTranscriptionStatus', AUDIO_TRANSCRIPTION_STATUSES)}

${renderEnum('AudioTranscriptionEvent', AUDIO_TRANSCRIPTION_EVENTS)}

${renderEnum('AudioTranscriptionSource', AUDIO_TRANSCRIPTION_SOURCES)}

${renderEnum('AudioTranscriptionExecution', AUDIO_TRANSCRIPTION_EXECUTIONS)}

${renderEnum('AudioTranscriptionErrorCode', AUDIO_TRANSCRIPTION_ERROR_CODES)}

${renderEnum('AudioTranscriptionProviderID', AUDIO_TRANSCRIPTION_PROVIDER_IDS)}

${renderTransitionFunction()}

struct AudioTranscriptionProvenance: Equatable, Codable, Sendable {
  let source: AudioTranscriptionSource
  let provider: AudioTranscriptionProviderID
  let execution: AudioTranscriptionExecution
  let locale: String?
  let modelID: String?
}
`;
}

function runCli() {
  const rendered = renderSwiftTranscriptionContract();
  if (process.argv.includes('--check')) {
    const current = readFileSync(outputPath, 'utf8');
    if (current !== rendered) {
      throw new Error(
        'Swift transcription contract is stale. Run pnpm --filter @jovie/web audio:transcription:swift'
      );
    }
    return;
  }
  writeFileSync(outputPath, rendered);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runCli();
}
