import {
  HOME_RELEASE_DESTINATION_LIVE_MOCK,
  HOME_RELEASE_DESTINATION_PRESAVE_MOCK,
} from '@/features/home/home-surface-seed';
import type {
  ProfileShowcaseState,
  ProfileShowcaseStateId,
} from '@/features/profile/contracts';
import { TIM_WHITE_PROFILE } from '@/lib/tim-white';
import type { TourDateViewModel } from '@/lib/tour-dates/types';
import type { PublicContact } from '@/types/contacts';
import type { Artist, LegacySocialLink } from '@/types/db';

const CREATED_AT = '2026-01-10T00:00:00.000Z';

export const HOMEPAGE_PROFILE_PREVIEW_ARTIST: Artist = {
  id: 'homepage-preview-artist',
  owner_user_id: 'homepage-preview-owner',
  handle: TIM_WHITE_PROFILE.handle,
  spotify_id: TIM_WHITE_PROFILE.spotifyArtistId,
  name: TIM_WHITE_PROFILE.name,
  image_url: TIM_WHITE_PROFILE.avatarSrc,
  tagline: 'Producer, songwriter, and after-hours romantic.',
  settings: {},
  theme: {},
  spotify_url: TIM_WHITE_PROFILE.spotifyUrl,
  apple_music_url: 'https://music.apple.com/us/artist/tim-white/123456789',
  youtube_url: 'https://www.youtube.com/@timwhite',
  deezer_id: 'tim-white-deezer',
  tidal_id: 'tim-white-tidal',
  soundcloud_id: 'tim-white-soundcloud',
  venmo_handle: '@timwhite',
  location: 'Los Angeles, CA',
  hometown: 'Vancouver, BC',
  active_since_year: 2014,
  genres: ['Melodic House', 'Progressive', 'Electronic'],
  career_highlights:
    'Support from Cosmic Gate, SiriusXM, and A State of Trance.',
  target_playlists: ['Mint', 'Dance Rising'],
  published: true,
  is_verified: true,
  is_featured: true,
  marketing_opt_out: false,
  created_at: CREATED_AT,
};

export const HOMEPAGE_PROFILE_PREVIEW_SOCIAL_LINKS: readonly LegacySocialLink[] =
  [
    {
      id: 'homepage-preview-spotify',
      artist_id: HOMEPAGE_PROFILE_PREVIEW_ARTIST.id,
      platform: 'spotify',
      url: HOMEPAGE_PROFILE_PREVIEW_ARTIST.spotify_url ?? 'https://spotify.com',
      clicks: 1820,
      created_at: CREATED_AT,
      is_visible: true,
    },
    {
      id: 'homepage-preview-instagram',
      artist_id: HOMEPAGE_PROFILE_PREVIEW_ARTIST.id,
      platform: 'instagram',
      url: 'https://instagram.com/timwhitemusic',
      clicks: 910,
      created_at: CREATED_AT,
      is_visible: true,
    },
    {
      id: 'homepage-preview-youtube',
      artist_id: HOMEPAGE_PROFILE_PREVIEW_ARTIST.id,
      platform: 'youtube',
      url: 'https://www.youtube.com/@timwhite',
      clicks: 522,
      created_at: CREATED_AT,
      is_visible: true,
    },
    {
      id: 'homepage-preview-venmo',
      artist_id: HOMEPAGE_PROFILE_PREVIEW_ARTIST.id,
      platform: 'venmo',
      url: 'https://venmo.com/u/timwhite',
      clicks: 302,
      created_at: CREATED_AT,
      is_visible: true,
    },
  ] as const;

export const HOMEPAGE_PROFILE_PREVIEW_CONTACTS: readonly PublicContact[] = [
  {
    id: 'homepage-contact-booking',
    role: 'bookings',
    roleLabel: 'Booking',
    territorySummary: 'North America +1',
    territoryCount: 2,
    territories: ['North America', 'Europe'],
    companyLabel: 'Nightshift Touring',
    contactName: 'Lina Park',
    secondaryLabel: 'Nightshift Touring',
    primaryContactLabel: 'Lina Park',
    channels: [
      {
        type: 'email',
        encoded: 'mailto:booking@timwhite.com',
        preferred: true,
      },
    ],
  },
  {
    id: 'homepage-contact-management',
    role: 'management',
    roleLabel: 'Management',
    territorySummary: 'Worldwide',
    territoryCount: 1,
    territories: ['Worldwide'],
    companyLabel: 'Northstar Management',
    contactName: 'Mason Clarke',
    secondaryLabel: 'Northstar Management',
    primaryContactLabel: 'Mason Clarke',
    channels: [
      {
        type: 'email',
        encoded: 'mailto:management@timwhite.com',
        preferred: true,
      },
    ],
  },
  {
    id: 'homepage-contact-press',
    role: 'press_pr',
    roleLabel: 'Press',
    territorySummary: 'United States +1',
    territoryCount: 2,
    territories: ['United States', 'United Kingdom'],
    companyLabel: 'Daylight PR',
    contactName: 'Avery Quinn',
    secondaryLabel: 'Daylight PR',
    primaryContactLabel: 'Avery Quinn',
    channels: [
      {
        type: 'email',
        encoded: 'mailto:press@timwhite.com',
        preferred: true,
      },
    ],
  },
  {
    id: 'homepage-contact-brand',
    role: 'brand_partnerships',
    roleLabel: 'Brand Partnerships',
    territorySummary: 'Worldwide',
    territoryCount: 1,
    territories: ['Worldwide'],
    companyLabel: 'Jovie Partnerships',
    contactName: 'Aria Bennett',
    secondaryLabel: 'Jovie Partnerships',
    primaryContactLabel: 'Aria Bennett',
    channels: [
      {
        type: 'email',
        encoded: 'mailto:brands@timwhite.com',
        preferred: true,
      },
    ],
  },
] as const;

export const HOMEPAGE_PROFILE_PREVIEW_TOUR_DATES: readonly TourDateViewModel[] =
  [
    {
      id: 'homepage-tour-1',
      profileId: HOMEPAGE_PROFILE_PREVIEW_ARTIST.id,
      externalId: 'tour-1',
      provider: 'manual',
      title: 'Afterglow Tour',
      startDate: '2026-05-18T03:00:00.000Z',
      startTime: '20:00',
      timezone: 'America/Los_Angeles',
      venueName: 'The Novo',
      city: 'Los Angeles',
      region: 'CA',
      country: 'US',
      latitude: 34.043,
      longitude: -118.267,
      ticketUrl: 'https://tickets.example.com/the-novo',
      ticketStatus: 'available',
      lastSyncedAt: CREATED_AT,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    {
      id: 'homepage-tour-2',
      profileId: HOMEPAGE_PROFILE_PREVIEW_ARTIST.id,
      externalId: 'tour-2',
      provider: 'manual',
      title: 'Afterglow Tour',
      startDate: '2026-05-24T03:00:00.000Z',
      startTime: '21:00',
      timezone: 'America/Chicago',
      venueName: 'Radius',
      city: 'Chicago',
      region: 'IL',
      country: 'US',
      latitude: 41.852,
      longitude: -87.619,
      ticketUrl: 'https://tickets.example.com/radius',
      ticketStatus: 'available',
      lastSyncedAt: CREATED_AT,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
  ] as const;

export const HOMEPAGE_PROFILE_PREVIEW_RELEASES = {
  presave: {
    title: HOME_RELEASE_DESTINATION_PRESAVE_MOCK.title,
    slug: 'the-deep-end',
    artworkUrl: '/img/releases/the-deep-end.jpg',
    releaseDate: '2026-05-01T07:00:00.000Z',
    revealDate: '2026-04-18T07:00:00.000Z',
    releaseType: 'single',
    metadata: {
      artistNames: ['Tim White', 'Erica Gibson'],
    },
  },
  live: {
    title: HOME_RELEASE_DESTINATION_LIVE_MOCK.title,
    slug: 'take-me-over',
    artworkUrl: '/img/releases/take-me-over.jpg',
    releaseDate: '2024-10-01T07:00:00.000Z',
    releaseType: 'single',
    metadata: {
      artistNames: ['Tim White', 'Erica Gibson'],
    },
  },
} as const;

export const HOMEPAGE_PROFILE_SHOWCASE_STATES: Readonly<
  Record<ProfileShowcaseStateId, ProfileShowcaseState>
> = {
  'streams-latest': {
    id: 'streams-latest',
    drawerView: null,
    latestReleaseKey: 'live',
    releaseActionLabel: 'Listen',
    notifications: {
      kind: 'button',
      tone: 'quiet',
      label: 'Latest release live',
      helper: 'The newest song stays one tap away.',
    },
    showSubscriptionConfirmedBanner: false,
    previewOverlay: null,
  },
  'streams-presave': {
    id: 'streams-presave',
    drawerView: null,
    latestReleaseKey: 'presave',
    notifications: {
      kind: 'button',
      tone: 'quiet',
      label: 'Presave is live',
      helper: 'The same link now leads to the countdown.',
    },
    showSubscriptionConfirmedBanner: false,
    previewOverlay: null,
  },
  'streams-release-day': {
    id: 'streams-release-day',
    drawerView: null,
    latestReleaseKey: 'live',
    releaseActionLabel: 'Listen',
    notifications: {
      kind: 'button',
      tone: 'success',
      label: 'Release day live',
      helper: 'The newest release is now the thing fans see first.',
    },
    showSubscriptionConfirmedBanner: false,
    previewOverlay: {
      kind: 'email-preview',
      title: 'Out now: Take Me Over',
      body: 'Take Me Over is live now. Listen in one tap.',
      accentLabel: 'Release alert',
    },
  },
  'streams-video': {
    id: 'streams-video',
    drawerView: null,
    latestReleaseKey: 'live',
    releaseActionLabel: 'Watch',
    notifications: {
      kind: 'button',
      tone: 'quiet',
      label: 'Video live',
      helper: 'The same profile now leads with the video.',
    },
    showSubscriptionConfirmedBanner: false,
    previewOverlay: {
      kind: 'email-preview',
      title: 'Watch: This Is Love',
      body: 'This Is Love is live now. Watch from the same link.',
      accentLabel: 'Video alert',
    },
  },
  'fans-opt-in': {
    id: 'fans-opt-in',
    drawerView: null,
    latestReleaseKey: 'live',
    notifications: {
      kind: 'input',
      tone: 'compose',
      label: 'Turn on notifications',
      helper:
        'Fans turn on notifications once. After that, Jovie keeps working.',
      value: 'fan@example.com',
    },
    showSubscriptionConfirmedBanner: false,
    previewOverlay: null,
  },
  'fans-confirmed': {
    id: 'fans-confirmed',
    drawerView: null,
    latestReleaseKey: 'live',
    notifications: {
      kind: 'status',
      tone: 'success',
      label: 'Notifications on',
      helper: 'Every new song, video, or show reaches them automatically.',
      value: 'fan@example.com',
    },
    showSubscriptionConfirmedBanner: true,
    previewOverlay: null,
  },
  'fans-song-alert': {
    id: 'fans-song-alert',
    drawerView: null,
    latestReleaseKey: 'live',
    releaseActionLabel: 'Listen',
    notifications: {
      kind: 'status',
      tone: 'success',
      label: 'Notifications on',
      helper: 'New music reaches the same fans automatically.',
    },
    showSubscriptionConfirmedBanner: true,
    previewOverlay: {
      kind: 'email-preview',
      title: 'New music from Tim White',
      body: 'Take Me Over is live now. Listen from the same link.',
      accentLabel: 'Inbox',
    },
  },
  'fans-show-alert': {
    id: 'fans-show-alert',
    drawerView: null,
    latestReleaseKey: 'none',
    notifications: {
      kind: 'status',
      tone: 'success',
      label: 'Notifications on',
      helper: 'Shows reach the same fans without another signup.',
    },
    showSubscriptionConfirmedBanner: true,
    previewOverlay: {
      kind: 'email-preview',
      title: 'Playing Los Angeles this Friday',
      body: 'The next local show reaches the fans already following along.',
      accentLabel: 'Show alert',
    },
  },
  tour: {
    id: 'tour',
    drawerView: 'tour',
    latestReleaseKey: 'none',
    notifications: {
      kind: 'button',
      tone: 'quiet',
      label: 'Next date live',
      helper: 'Lead with the next date and open the full run from there.',
    },
    showSubscriptionConfirmedBanner: false,
    previewOverlay: null,
  },
  'tips-open': {
    id: 'tips-open',
    drawerView: 'pay',
    latestReleaseKey: 'none',
    notifications: {
      kind: 'button',
      tone: 'quiet',
      label: 'Get paid',
      helper: 'Take payment in one tap.',
    },
    showSubscriptionConfirmedBanner: false,
    previewOverlay: null,
  },
  'tips-apple-pay': {
    id: 'tips-apple-pay',
    drawerView: 'pay',
    latestReleaseKey: 'none',
    notifications: {
      kind: 'button',
      tone: 'quiet',
      label: 'Apple Pay ready',
      helper: 'Apple Pay keeps the moment moving.',
    },
    showSubscriptionConfirmedBanner: false,
    previewOverlay: {
      kind: 'apple-pay',
      title: 'Apple Pay',
      body: 'Tip Tim White $10',
      accentLabel: 'Double-click to pay',
    },
  },
  'tips-thank-you': {
    id: 'tips-thank-you',
    drawerView: null,
    latestReleaseKey: 'live',
    releaseActionLabel: 'Listen',
    notifications: {
      kind: 'button',
      tone: 'success',
      label: 'Say thanks',
      helper: 'Turn support into a listener.',
    },
    showSubscriptionConfirmedBanner: false,
    previewOverlay: {
      kind: 'thank-you',
      title: 'Thanks for the tip',
      body: "Here's my latest song.",
      accentLabel: 'Say thanks',
    },
  },
  'tips-followup': {
    id: 'tips-followup',
    drawerView: null,
    latestReleaseKey: 'live',
    releaseActionLabel: 'Listen',
    notifications: {
      kind: 'button',
      tone: 'success',
      label: 'Turn support into a listener',
      helper: 'The same moment can turn into the next listen.',
    },
    showSubscriptionConfirmedBanner: false,
    previewOverlay: {
      kind: 'email-preview',
      title: 'Thanks for the tip',
      body: "Here's my latest song.",
      accentLabel: 'Follow-up',
    },
  },
  contact: {
    id: 'contact',
    drawerView: 'contact',
    latestReleaseKey: 'none',
    notifications: {
      kind: 'button',
      tone: 'quiet',
      label: 'Never miss a booking',
      helper:
        'If a talent buyer wants to book you, the contact is right there.',
    },
    showSubscriptionConfirmedBanner: false,
    previewOverlay: null,
  },
  catalog: {
    id: 'catalog',
    drawerView: null,
    latestReleaseKey: 'live',
    releaseActionLabel: 'Listen',
    notifications: {
      kind: 'button',
      tone: 'quiet',
      label: 'One profile',
      helper: 'One place for songs, videos, shows, and business.',
    },
    showSubscriptionConfirmedBanner: false,
    previewOverlay: null,
  },
} as const;
