export const LEGACY_STATSIG_GATE_KEYS = {
  PROFILE_V2: 'feature_profile_v2',
  CLAIM_HANDLE: 'feature_claim_handle',
  HERO_SPOTIFY_CLAIM_FLOW: 'feature_hero_spotify_claim_flow',
  BILLING_UPGRADE_DIRECT: 'billing.upgradeDirect',
  SUBSCRIBE_TWO_STEP: 'feature_subscribe_two_step',
  LATEST_RELEASE_CARD: 'feature_latest_release_card',
  SMARTLINK_PRE_SAVE: 'smartlink_pre_save_campaigns',
  IOS_APPLE_MUSIC_PRIORITY: 'feature_ios_apple_music_priority',
  SUBSCRIBE_CTA_EXPERIMENT: 'experiment_subscribe_cta_variant',
  SPOTIFY_OAUTH: 'feature_spotify_oauth',
  STRIPE_CONNECT_ENABLED: 'stripe-connect-enabled',
  SHOW_EXAMPLE_PROFILES_CAROUSEL: 'show_example_profiles_carousel',
  ENABLE_LIGHT_MODE: 'enable_light_mode',
  SHOW_AUDIENCE_CRM_SECTION: 'show_audience_crm_section',
  SHOW_SEE_IT_IN_ACTION: 'show_see_it_in_action',
} as const;

export type StatsigGateKey =
  (typeof LEGACY_STATSIG_GATE_KEYS)[keyof typeof LEGACY_STATSIG_GATE_KEYS];

export type SubscribeCTAVariant = 'two_step' | 'inline';
export interface StatsigFeatureFlagsBootstrap {
  gates: Record<string, boolean>;
}

export const APP_FLAG_DEFAULTS = {
  PROFILE_V2: true,
  CLAIM_HANDLE: false,
  HERO_SPOTIFY_CLAIM_FLOW: false,
  BILLING_UPGRADE_DIRECT: false,
  SUBSCRIBE_TWO_STEP: false,
  LATEST_RELEASE_CARD: true,
  SMARTLINK_PRE_SAVE: false,
  IOS_APPLE_MUSIC_PRIORITY: false,
  SPOTIFY_OAUTH: false,
  STRIPE_CONNECT_ENABLED: false,
  ENABLE_LIGHT_MODE: false,
  SHOW_AUDIENCE_CRM_SECTION: false,
  THREADS_ENABLED: false,
  PWA_INSTALL_BANNER: false,
  SHOW_RELEASE_TOOLBAR_EXTRAS: false,
  PLAYLIST_ENGINE: false,
  ALBUM_ART_GENERATION: true,
  VIRAL_REEL_MVP: false,
} as const;

export type AppFlagName = keyof typeof APP_FLAG_DEFAULTS;
export type AppFlagSnapshot = Record<AppFlagName, boolean>;

export const APP_FLAG_KEYS = {
  PROFILE_V2: LEGACY_STATSIG_GATE_KEYS.PROFILE_V2,
  CLAIM_HANDLE: LEGACY_STATSIG_GATE_KEYS.CLAIM_HANDLE,
  HERO_SPOTIFY_CLAIM_FLOW: LEGACY_STATSIG_GATE_KEYS.HERO_SPOTIFY_CLAIM_FLOW,
  BILLING_UPGRADE_DIRECT: LEGACY_STATSIG_GATE_KEYS.BILLING_UPGRADE_DIRECT,
  SUBSCRIBE_TWO_STEP: LEGACY_STATSIG_GATE_KEYS.SUBSCRIBE_TWO_STEP,
  LATEST_RELEASE_CARD: LEGACY_STATSIG_GATE_KEYS.LATEST_RELEASE_CARD,
  SMARTLINK_PRE_SAVE: LEGACY_STATSIG_GATE_KEYS.SMARTLINK_PRE_SAVE,
  IOS_APPLE_MUSIC_PRIORITY: LEGACY_STATSIG_GATE_KEYS.IOS_APPLE_MUSIC_PRIORITY,
  SPOTIFY_OAUTH: LEGACY_STATSIG_GATE_KEYS.SPOTIFY_OAUTH,
  STRIPE_CONNECT_ENABLED: LEGACY_STATSIG_GATE_KEYS.STRIPE_CONNECT_ENABLED,
  ENABLE_LIGHT_MODE: LEGACY_STATSIG_GATE_KEYS.ENABLE_LIGHT_MODE,
  SHOW_AUDIENCE_CRM_SECTION: LEGACY_STATSIG_GATE_KEYS.SHOW_AUDIENCE_CRM_SECTION,
  THREADS_ENABLED: 'threads_enabled',
  PWA_INSTALL_BANNER: 'pwa_install_banner',
  SHOW_RELEASE_TOOLBAR_EXTRAS: 'show_release_toolbar_extras',
  PLAYLIST_ENGINE: 'playlist_engine',
  ALBUM_ART_GENERATION: 'album_art_generation',
  VIRAL_REEL_MVP: 'viral_reel_mvp',
} as const satisfies Record<AppFlagName, string>;

export const APP_FLAG_OVERRIDE_KEYS = {
  PROFILE_V2: 'code:PROFILE_V2',
  CLAIM_HANDLE: 'code:CLAIM_HANDLE',
  HERO_SPOTIFY_CLAIM_FLOW: 'code:HERO_SPOTIFY_CLAIM_FLOW',
  BILLING_UPGRADE_DIRECT: 'code:BILLING_UPGRADE_DIRECT',
  SUBSCRIBE_TWO_STEP: 'code:SUBSCRIBE_TWO_STEP',
  LATEST_RELEASE_CARD: 'code:LATEST_RELEASE_CARD',
  SMARTLINK_PRE_SAVE: 'code:SMARTLINK_PRE_SAVE',
  IOS_APPLE_MUSIC_PRIORITY: 'code:IOS_APPLE_MUSIC_PRIORITY',
  SPOTIFY_OAUTH: 'code:SPOTIFY_OAUTH',
  STRIPE_CONNECT_ENABLED: 'code:STRIPE_CONNECT_ENABLED',
  ENABLE_LIGHT_MODE: 'code:ENABLE_LIGHT_MODE',
  SHOW_AUDIENCE_CRM_SECTION: 'code:SHOW_AUDIENCE_CRM_SECTION',
  THREADS_ENABLED: 'code:THREADS_ENABLED',
  PWA_INSTALL_BANNER: 'code:PWA_INSTALL_BANNER',
  SHOW_RELEASE_TOOLBAR_EXTRAS: 'code:SHOW_RELEASE_TOOLBAR_EXTRAS',
  PLAYLIST_ENGINE: 'code:PLAYLIST_ENGINE',
  ALBUM_ART_GENERATION: 'code:ALBUM_ART_GENERATION',
  VIRAL_REEL_MVP: 'code:VIRAL_REEL_MVP',
} as const satisfies Record<AppFlagName, string>;

export const APP_FLAG_TO_STATSIG_GATE = {
  PROFILE_V2: LEGACY_STATSIG_GATE_KEYS.PROFILE_V2,
  CLAIM_HANDLE: LEGACY_STATSIG_GATE_KEYS.CLAIM_HANDLE,
  HERO_SPOTIFY_CLAIM_FLOW: LEGACY_STATSIG_GATE_KEYS.HERO_SPOTIFY_CLAIM_FLOW,
  BILLING_UPGRADE_DIRECT: LEGACY_STATSIG_GATE_KEYS.BILLING_UPGRADE_DIRECT,
  SUBSCRIBE_TWO_STEP: LEGACY_STATSIG_GATE_KEYS.SUBSCRIBE_TWO_STEP,
  LATEST_RELEASE_CARD: LEGACY_STATSIG_GATE_KEYS.LATEST_RELEASE_CARD,
  SMARTLINK_PRE_SAVE: LEGACY_STATSIG_GATE_KEYS.SMARTLINK_PRE_SAVE,
  IOS_APPLE_MUSIC_PRIORITY: LEGACY_STATSIG_GATE_KEYS.IOS_APPLE_MUSIC_PRIORITY,
  SPOTIFY_OAUTH: LEGACY_STATSIG_GATE_KEYS.SPOTIFY_OAUTH,
  STRIPE_CONNECT_ENABLED: LEGACY_STATSIG_GATE_KEYS.STRIPE_CONNECT_ENABLED,
  ENABLE_LIGHT_MODE: LEGACY_STATSIG_GATE_KEYS.ENABLE_LIGHT_MODE,
  SHOW_AUDIENCE_CRM_SECTION: LEGACY_STATSIG_GATE_KEYS.SHOW_AUDIENCE_CRM_SECTION,
} as const satisfies Partial<Record<AppFlagName, StatsigGateKey>>;

export type StatsigBackedAppFlagName = keyof typeof APP_FLAG_TO_STATSIG_GATE;

export const APP_FLAG_DESCRIPTIONS = {
  PROFILE_V2: 'Profile V2 layout',
  CLAIM_HANDLE: 'Handle claiming flow',
  HERO_SPOTIFY_CLAIM_FLOW: 'Hero Spotify claim flow',
  BILLING_UPGRADE_DIRECT: 'Direct billing upgrade',
  SUBSCRIBE_TWO_STEP: 'Two-step subscribe flow',
  LATEST_RELEASE_CARD: 'Latest release card on profile',
  SMARTLINK_PRE_SAVE: 'Spotify pre-save campaigns',
  IOS_APPLE_MUSIC_PRIORITY: 'Prefer Apple Music on iOS',
  SPOTIFY_OAUTH: 'Spotify OAuth login',
  STRIPE_CONNECT_ENABLED: 'Stripe Connect payouts',
  ENABLE_LIGHT_MODE: 'Light mode theme option',
  SHOW_AUDIENCE_CRM_SECTION: 'Audience CRM section',
  THREADS_ENABLED: 'Threads in sidebar chat history',
  PWA_INSTALL_BANNER: 'PWA install banner in the sidebar',
  SHOW_RELEASE_TOOLBAR_EXTRAS: 'Extra releases toolbar controls',
  PLAYLIST_ENGINE: 'Playlist engine surfaces',
  ALBUM_ART_GENERATION: 'AI-generated release artwork via chat',
  VIRAL_REEL_MVP:
    'Phase 2 MVP: generate a silent 9:16 teaser reel for a release',
} as const satisfies Record<AppFlagName, string>;
