/**
 * Static-only marketing flags.
 *
 * These flags must remain build-time constants so homepage and marketing routes
 * stay fully static.
 */
const IS_VERCEL_PRODUCTION = process.env.VERCEL_ENV === 'production';
const SHOW_FORGEUI_MARKETING_UPDATES =
  process.env.NEXT_PUBLIC_SHOW_FORGEUI_MARKETING_UPDATES === 'true' ||
  !IS_VERCEL_PRODUCTION;
const SHOW_HOME_REFRESH_2026 =
  process.env.NEXT_PUBLIC_SHOW_HOME_REFRESH_2026 === 'true';
const SHOW_MARKETING_CENTER_NAV =
  process.env.NEXT_PUBLIC_SHOW_MARKETING_CENTER_NAV === 'true' ||
  process.env.NEXT_PUBLIC_SHOW_HOMEPAGE_CENTER_NAV === 'true' ||
  !IS_VERCEL_PRODUCTION;
const SHOW_HOMEPAGE_CENTER_NAV =
  process.env.NEXT_PUBLIC_SHOW_HOMEPAGE_CENTER_NAV === 'true' ||
  SHOW_MARKETING_CENTER_NAV;
const SHOW_HOMEPAGE_UNLOCKED_SECTIONS =
  process.env.NEXT_PUBLIC_SHOW_HOMEPAGE_UNLOCKED_SECTIONS === 'true' ||
  !IS_VERCEL_PRODUCTION;
const SHOW_HOMEPAGE_FRIDAY_RHYTHM =
  process.env.NEXT_PUBLIC_SHOW_HOMEPAGE_FRIDAY_RHYTHM === 'true';
const SHOW_HOMEPAGE_AI_COMPOSER_SECTION =
  process.env.NEXT_PUBLIC_SHOW_HOMEPAGE_AI_COMPOSER_SECTION === 'true';

export const FEATURE_FLAGS = {
  SHOW_EXAMPLE_PROFILES_CAROUSEL: false,
  SHOW_SEE_IT_IN_ACTION: false,
  SHOW_REPLACES_SECTION: false,
  SHOW_PHONE_TOUR: true,
  SHOW_LOGO_BAR: true,
  SHOW_FEATURE_SHOWCASE: false,
  SHOW_FINAL_CTA: true,
  SHOW_HOMEPAGE_SECTIONS: false,
  SHOW_HOMEPAGE_V2_SOCIAL_PROOF: false,
  SHOW_HOMEPAGE_V2_TRUST: false,
  SHOW_HOMEPAGE_V2_SYSTEM_OVERVIEW: true,
  SHOW_HOMEPAGE_V2_SPOTLIGHT: true,
  SHOW_HOMEPAGE_V2_CAPTURE_REACTIVATE: true,
  SHOW_HOMEPAGE_V2_POWER_GRID: false,
  SHOW_HOMEPAGE_V2_PRICING: true,
  SHOW_HOMEPAGE_V2_FINAL_CTA: true,
  SHOW_HOMEPAGE_V2_FOOTER_LINKS: false,
  SHOW_ARTIST_PROFILE_PAY_FLOW_VIDEO: true,
  SHOW_FORGEUI_MARKETING_UPDATES,
  SHOW_HOMEPAGE_AI_COMPOSER_SECTION,
  SHOW_HOMEPAGE_CENTER_NAV,
  SHOW_HOMEPAGE_FRIDAY_RHYTHM,
  SHOW_HOMEPAGE_UNLOCKED_SECTIONS,
  SHOW_HOME_REFRESH_2026,
  SHOW_MARKETING_CENTER_NAV,
  SHOW_HOME_V1_DESIGN: false,
  SHOW_PUBLIC_PROFILE_V1_DESIGN: false,
} as const;

export type MarketingStaticFlagName = keyof typeof FEATURE_FLAGS;
