/**
 * Unit tests for classifyYouTubeVideo (JOV-5136)
 */

import { describe, expect, it } from 'vitest';
import { classifyYouTubeVideo } from '@/lib/youtube-library/classify';

describe('classifyYouTubeVideo', () => {
  it('classifies <= 60s videos as short', () => {
    const result = classifyYouTubeVideo({
      title: 'Quick teaser',
      description: null,
      durationSeconds: 60,
    });
    expect(result.contentType).toBe('short');
    expect(result.confidence).toBe(0.9);
    expect(result.rationale).toContain('duration 60s');
  });

  it('does not classify 61s videos as short (boundary)', () => {
    const result = classifyYouTubeVideo({
      title: 'Slightly longer teaser',
      description: null,
      durationSeconds: 61,
    });
    expect(result.contentType).toBe('other');
    expect(result.confidence).toBe(0.5);
    expect(result.rationale).toBe('no signals matched');
  });

  it('classifies #shorts tag as short regardless of duration', () => {
    const result = classifyYouTubeVideo({
      title: 'My song snippet #Shorts',
      description: null,
      durationSeconds: 300,
    });
    expect(result.contentType).toBe('short');
    expect(result.rationale).toContain('#shorts');
  });

  it('short precedence wins over a music-video title', () => {
    const result = classifyYouTubeVideo({
      title: 'Track (Official Music Video) #shorts',
      description: null,
      durationSeconds: 45,
    });
    expect(result.contentType).toBe('short');
  });

  it('classifies lyric videos', () => {
    const result = classifyYouTubeVideo({
      title: 'Artist - Song (Official Lyric Video)',
      description: null,
      durationSeconds: 210,
    });
    expect(result.contentType).toBe('lyric_video');
    expect(result.confidence).toBe(0.85);
  });

  it('classifies live performances', () => {
    for (const title of [
      'Song (Live at Red Rocks)',
      'Song - live from the studio session',
      'Song (Live)',
      'Song live performance',
    ]) {
      const result = classifyYouTubeVideo({
        title,
        description: null,
        durationSeconds: 240,
      });
      expect(result.contentType).toBe('live_performance');
      expect(result.confidence).toBe(0.8);
    }
  });

  it('classifies distributor-block descriptions as music_video (strongest signal)', () => {
    const result = classifyYouTubeVideo({
      title: 'Song',
      description: 'Provided to YouTube by DistroKid\n\nSong · Artist\n',
      durationSeconds: 200,
    });
    expect(result.contentType).toBe('music_video');
    expect(result.confidence).toBe(0.85);
    expect(result.rationale).toContain('provided to youtube by');
  });

  it('bumps confidence when distributor block and music-video title combine', () => {
    const result = classifyYouTubeVideo({
      title: 'Song (Official Video)',
      description: 'Auto-generated by YouTube.',
      durationSeconds: 200,
    });
    expect(result.contentType).toBe('music_video');
    expect(result.confidence).toBe(0.9);
  });

  it('classifies official/music-video titles as music_video at lower confidence', () => {
    const result = classifyYouTubeVideo({
      title: 'Artist - Song (Official Music Video)',
      description: null,
      durationSeconds: 200,
    });
    expect(result.contentType).toBe('music_video');
    expect(result.confidence).toBe(0.7);
  });

  it('lyric video precedence wins over a music-video title', () => {
    const result = classifyYouTubeVideo({
      title: 'Song (Lyric Video)',
      description: null,
      durationSeconds: 200,
    });
    expect(result.contentType).toBe('lyric_video');
  });

  it('classifies vlogs', () => {
    const result = classifyYouTubeVideo({
      title: 'Tour Vlog ep. 4',
      description: null,
      durationSeconds: 600,
    });
    expect(result.contentType).toBe('vlog');
    expect(result.confidence).toBe(0.7);
  });

  it('falls back to other with a no-signals rationale', () => {
    const result = classifyYouTubeVideo({
      title: 'Behind the scenes',
      description: 'Just hanging out',
      durationSeconds: 400,
    });
    expect(result.contentType).toBe('other');
    expect(result.confidence).toBe(0.5);
    expect(result.rationale).toBe('no signals matched');
  });

  it('handles null description and null duration safely', () => {
    const result = classifyYouTubeVideo({
      title: '',
      description: null,
      durationSeconds: null,
    });
    expect(result.contentType).toBe('other');
  });
});
