/** Public Chartmetric endpoint index. Names and admission only; no schemas or scores. */
export const CHARTMETRIC_ENDPOINT_COUNT = 155;

export type ChartmetricAdmission =
  | 'access-blocked'
  | 'vendor-only-opaque-metric';

export const CHARTMETRIC_ENDPOINTS: readonly (readonly [
  method: string,
  path: string,
  admission: ChartmetricAdmission,
])[] = [
  ['POST', '/api/token', 'access-blocked'],
  ['GET', '/api/search', 'access-blocked'],
  ['GET', '/api/search/social', 'access-blocked'],
  ['GET', '/api/genres', 'access-blocked'],
  ['GET', '/api/genres/{id}', 'access-blocked'],
  ['GET', '/api/genre', 'access-blocked'],
  ['GET', '/api/cities', 'access-blocked'],
  ['GET', '/api/city/{id}/{domain}/top-artists', 'access-blocked'],
  ['GET', '/api/city/{id}/{domain}/top-tracks', 'access-blocked'],
  ['GET', '/api/album/{id}/{type}/charts', 'access-blocked'],
  ['GET', '/api/album/{type}/{id}/get-ids', 'access-blocked'],
  ['GET', '/api/album/{id}', 'access-blocked'],
  ['GET', '/api/album/{id}/tracks', 'access-blocked'],
  ['GET', '/api/album/{id}/{platform}/{stats}', 'access-blocked'],
  ['GET', '/api/album/{id}/{platform}/{status}/playlists', 'access-blocked'],
  ['GET', '/api/artist/anr/by/playlists', 'access-blocked'],
  ['GET', '/api/artist/{id}/riaa', 'access-blocked'],
  ['GET', '/api/artist/anr/by/social-index', 'access-blocked'],
  ['GET', '/api/artist/{id}/cpp', 'access-blocked'],
  ['GET', '/api/artist/{id}/{type}/charts', 'access-blocked'],
  ['GET', '/api/artist/{type}/{id}/get-ids', 'access-blocked'],
  ['GET', '/api/artist/{type}/list', 'access-blocked'],
  ['GET', '/api/artist/list/filter', 'access-blocked'],
  ['GET', '/api/artist/{id}', 'access-blocked'],
  ['GET', '/api/artist/{id}/relatedartists', 'access-blocked'],
  ['GET', '/api/artist/{id}/where-people-listen', 'access-blocked'],
  ['GET', '/api/artist/{id}/{platform}/{status}/playlists', 'access-blocked'],
  ['GET', '/api/artist/{id}/albums', 'access-blocked'],
  ['GET', '/api/artist/{id}/tracks', 'access-blocked'],
  ['GET', '/api/artist/{id}/urls', 'access-blocked'],
  ['GET', '/api/artist/{id}/stat/{source}', 'access-blocked'],
  ['GET', '/api/artist/{id}/instagram-audience-stats', 'access-blocked'],
  ['GET', '/api/artist/{id}/instagram-audience-stats/dates', 'access-blocked'],
  ['GET', '/api/artist/{id}/social-audience-stats', 'access-blocked'],
  ['GET', '/api/artist/{id}/youtube-audience-stats', 'access-blocked'],
  ['GET', '/api/artist/{id}/tiktok-top-videos', 'access-blocked'],
  ['GET', '/api/artist/{id}/tiktok-top-influencers', 'access-blocked'],
  ['GET', '/api/artist/{id}/tiktok-influencer-stats', 'access-blocked'],
  ['GET', '/api/artist/{id}/tiktok-audience-stats', 'access-blocked'],
  ['GET', '/api/artist/{id}/top-tracks/{source}', 'access-blocked'],
  ['GET', '/api/artist/{id}/artist-rank', 'access-blocked'],
  ['GET', '/api/artist/{id}/past-artist-rank', 'access-blocked'],
  ['GET', '/api/artist/{id}/neighboring-artists', 'access-blocked'],
  ['GET', '/api/artist/{id}/market-coverage-views/youtube', 'access-blocked'],
  ['GET', '/api/artist/{id}/tvmaze', 'access-blocked'],
  ['GET', '/api/artist/{id}/career', 'access-blocked'],
  ['GET', '/api/artist/{id}/milestones', 'access-blocked'],
  ['GET', '/api/artist/{id}/noteworthy-insights', 'access-blocked'],
  ['GET', '/api/artist/{id}/{status}/events', 'access-blocked'],
  ['GET', '/api/artist/{id}/news', 'access-blocked'],
  ['GET', '/api/artist/{id}/venues', 'access-blocked'],
  [
    'GET',
    '/api/artist/{id}/similar-artists/by-configurations',
    'access-blocked',
  ],
  ['GET', '/api/artist/{id}/cmStats', 'access-blocked'],
  ['GET', '/api/brand/list', 'access-blocked'],
  ['GET', '/api/brand/list/by/interest', 'access-blocked'],
  ['GET', '/api/brand/v2/list', 'access-blocked'],
  ['GET', '/api/brand/v2/list/by/category', 'access-blocked'],
  ['GET', '/api/brand/v2/list/by/subcategory', 'access-blocked'],
  ['GET', '/api/brand/v2/{brandId}/audience', 'access-blocked'],
  ['GET', '/api/brand/v2/{brandId}', 'access-blocked'],
  ['GET', '/api/brand/{brandId}', 'access-blocked'],
  [
    'GET',
    '/api/charts/{byType}/{id}/{chartType}/cm-score',
    'vendor-only-opaque-metric',
  ],
  ['GET', '/api/charts/spotify', 'access-blocked'],
  ['GET', '/api/charts/spotify/artists', 'access-blocked'],
  ['GET', '/api/charts/spotify/freshfind', 'access-blocked'],
  ['GET', '/api/charts/deezer', 'access-blocked'],
  ['GET', '/api/charts/qq', 'access-blocked'],
  ['GET', '/api/charts/amazon/tracks', 'access-blocked'],
  ['GET', '/api/charts/amazon/albums', 'access-blocked'],
  ['GET', '/api/charts/applemusic/tracks', 'access-blocked'],
  ['GET', '/api/charts/applemusic/albums', 'access-blocked'],
  ['GET', '/api/charts/applemusic/videos', 'access-blocked'],
  ['GET', '/api/charts/itunes/tracks', 'access-blocked'],
  ['GET', '/api/charts/itunes/albums', 'access-blocked'],
  ['GET', '/api/charts/itunes/videos', 'access-blocked'],
  ['GET', '/api/charts/shazam', 'access-blocked'],
  ['GET', '/api/charts/shazam/{country_code}/cities', 'access-blocked'],
  ['GET', '/api/charts/soundcloud', 'access-blocked'],
  ['GET', '/api/charts/beatport', 'access-blocked'],
  ['GET', '/api/charts/tiktok/tracks', 'access-blocked'],
  ['GET', '/api/charts/tiktok/videos', 'access-blocked'],
  ['GET', '/api/charts/tiktok/users', 'access-blocked'],
  ['GET', '/api/charts/tiktok/sounds', 'access-blocked'],
  ['GET', '/api/charts/tiktok/tracks/{chart_type}', 'access-blocked'],
  ['GET', '/api/charts/youtube/shorts/{chartType}', 'access-blocked'],
  ['GET', '/api/charts/youtube/tracks', 'access-blocked'],
  ['GET', '/api/charts/youtube/videos', 'access-blocked'],
  ['GET', '/api/charts/youtube/trends', 'access-blocked'],
  ['GET', '/api/charts/youtube/artists', 'access-blocked'],
  ['GET', '/api/charts/airplay/tracks', 'access-blocked'],
  ['GET', '/api/charts/airplay/artists', 'access-blocked'],
  ['GET', '/api/charts/twitch/users', 'access-blocked'],
  ['GET', '/api/charts/melon/track/{chartType}', 'access-blocked'],
  ['GET', '/api/charts/hanteo/{entityType}/{chartType}', 'access-blocked'],
  ['GET', '/api/charts/circle/{entityType}/{chartType}', 'access-blocked'],
  ['GET', '/api/charts/line_music/{entityType}/{chartType}', 'access-blocked'],
  ['GET', '/api/charts/pandora/track/{chartType}', 'access-blocked'],
  ['GET', '/api/charts/anghami/track/{chartType}', 'access-blocked'],
  ['GET', '/api/charts/soundcloud/track/{chartType}', 'access-blocked'],
  ['GET', '/api/charts/{platform}/countries', 'access-blocked'],
  ['GET', '/api/charts/{streamingType}/dates', 'access-blocked'],
  ['GET', '/api/charts/genres/{platform}', 'access-blocked'],
  [
    'GET',
    '/api/country/{code2}/artist-rankings/{area}/{type}/{subArea}',
    'access-blocked',
  ],
  ['GET', '/api/curator/deezer/lists', 'access-blocked'],
  ['GET', '/api/curator/itunes/lists', 'access-blocked'],
  ['GET', '/api/curator/applemusic/lists', 'access-blocked'],
  ['GET', '/api/curator/spotify/lists', 'access-blocked'],
  ['GET', '/api/curator/youtube/lists', 'access-blocked'],
  ['GET', '/api/curator/amazon/lists', 'access-blocked'],
  ['GET', '/api/curator/{platform}/lists', 'access-blocked'],
  ['GET', '/api/curator/{platform}/{id}', 'access-blocked'],
  ['GET', '/api/curator/{platform}/{id}/playlists', 'access-blocked'],
  ['GET', '/api/curator/{platform}/{id}/urls', 'access-blocked'],
  ['GET', '/api/curator/{platform}/{id}/stat/{source}', 'access-blocked'],
  ['GET', '/api/playlist/amazon/lists', 'access-blocked'],
  ['GET', '/api/playlist/itunes/lists', 'access-blocked'],
  ['GET', '/api/playlist/deezer/lists', 'access-blocked'],
  ['GET', '/api/playlist/spotify/lists', 'access-blocked'],
  ['GET', '/api/playlist/youtube/lists', 'access-blocked'],
  ['GET', '/api/playlist/soundcloud/lists', 'access-blocked'],
  ['GET', '/api/playlist/{platform}/lists', 'access-blocked'],
  ['GET', '/api/playlist/{platform}/{id}', 'access-blocked'],
  ['GET', '/api/playlist/{platform}/{id}/stats', 'access-blocked'],
  ['GET', '/api/playlist/{platform}/{id}/snapshot', 'access-blocked'],
  ['GET', '/api/playlist/{platform}/{id}/similarplaylists', 'access-blocked'],
  ['GET', '/api/playlist/{platform}/{id}/{span}/tracks', 'access-blocked'],
  ['GET', '/api/playlist/by/{type}/{id}/evolution', 'access-blocked'],
  [
    'GET',
    '/api/playlist/{platform}/{id}/journey-progression/{type}',
    'access-blocked',
  ],
  ['GET', '/api/playlist/{platform}/{id}/updated', 'access-blocked'],
  ['GET', '/api/radio/{type}/{id}/airplay-totals', 'access-blocked'],
  ['GET', '/api/radio/{type}/{id}/airplay-totals/{entity}', 'access-blocked'],
  ['GET', '/api/radio/{type}/{id}/airplays', 'access-blocked'],
  ['GET', '/api/radio/{type}/{id}/broadcast-markets', 'access-blocked'],
  ['GET', '/api/radio/station-list', 'access-blocked'],
  ['POST', '/api/track/playlist-stream-estimates', 'access-blocked'],
  ['GET', '/api/track/{id}/playlist-stream-estimates', 'access-blocked'],
  ['GET', '/api/track/{id}/video-trends', 'access-blocked'],
  ['GET', '/api/track/{id}/{type}/charts', 'access-blocked'],
  ['GET', '/api/track/{type}/{id}/get-ids', 'access-blocked'],
  ['GET', '/api/track/{id}', 'access-blocked'],
  ['GET', '/api/track/{id}/{platform}/playlists/snapshot', 'access-blocked'],
  ['GET', '/api/track/{id}/{platform}/stats/{mode}', 'access-blocked'],
  ['GET', '/api/track/youtube/{id}/topShorts', 'access-blocked'],
  ['GET', '/api/track/{id}/tiktok-top-influencers', 'access-blocked'],
  ['GET', '/api/track/{id}/tiktok-influencer-stats', 'access-blocked'],
  ['GET', '/api/track/{id}/tiktok-top-sounds', 'access-blocked'],
  ['GET', '/api/track/{id}/topVideos', 'access-blocked'],
  ['GET', '/api/track/{id}/relatedTracks', 'access-blocked'],
  ['GET', '/api/track/{id}/{platform}/{status}/playlists', 'access-blocked'],
  ['GET', '/api/track/{id}/milestones', 'access-blocked'],
  ['GET', '/api/track/list/filter', 'access-blocked'],
  ['GET', '/api/festival/list', 'access-blocked'],
  ['GET', '/api/event/venue/{id}', 'access-blocked'],
  ['GET', '/api/SNS/deepSocial/cm_artist/{id}/instagram', 'access-blocked'],
  ['GET', '/api/venue', 'access-blocked'],
];
