name: 'Setup Node.js and pnpm'
description: 'Sets up Node.js, pnpm, and installs dependencies with optimal caching'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      
    - name: Setup Node.js with pnpm cache
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '24'
        cache: pnpm
        cache-dependency-path: '**/pnpm-lock.yaml'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
