name: 'Setup Node.js and pnpm'
description: 'Sets up Node.js, pnpm, and installs dependencies with optimal caching'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      
    - name: Setup Node.js with pnpm cache
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
        cache-dependency-path: '**/pnpm-lock.yaml'
        
    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile