import { describe, expect, it } from 'vitest';
import { InMemoryReleaseCommunicationsAdapter, localCalendarDay } from './index';
const event = (overrides: Record<string, unknown> = {}) => ({ repository: 'JovieInc/Jovie', pullRequestNumber: 5787, mergeSha: 'abc123', mergedAt: new Date('2026-09-06T23:30:00Z'), app: 'web' as const, product: 'jovie', title: 'Release communications core', verified: true as const, ...overrides });
describe('release communications adapter contract', () => {
  it('deduplicates replay and appends same-day events', async () => { const adapter = new InMemoryReleaseCommunicationsAdapter('America/Los_Angeles'); const first = await adapter.ingest(event()); expect((await adapter.ingest(event())).entries).toHaveLength(1); const appended = await adapter.ingest(event({ mergeSha: 'def456', pullRequestNumber: 5788 })); expect(appended.id).toBe(first.id); expect(appended.entries).toHaveLength(2); });
  it('splits posts on the local calendar day', async () => { const adapter = new InMemoryReleaseCommunicationsAdapter('America/Los_Angeles'); const prior = await adapter.ingest(event()); const next = await adapter.ingest(event({ mergeSha: 'def456', pullRequestNumber: 5788, mergedAt: new Date('2026-09-07T07:30:00Z') })); expect(prior.localDate).toBe('2026-09-06'); expect(next.localDate).toBe('2026-09-07'); expect(localCalendarDay(new Date('2026-09-07T07:30:00Z'), 'America/Los_Angeles')).toBe('2026-09-07'); });
  it('keeps materiality separate from audience eligibility', async () => { const post = await new InMemoryReleaseCommunicationsAdapter().ingest(event({ material: false, audienceEligible: true })); expect(post.entries[0]).toMatchObject({ material: false, audienceEligible: true }); });
  it('persists whole-post dismissal per user', async () => { const adapter = new InMemoryReleaseCommunicationsAdapter(); const post = await adapter.ingest(event()); await adapter.dismissPost({ postId: post.id, userId: 'user-1' }); expect(await adapter.isPostDismissed({ postId: post.id, userId: 'user-1' })).toBe(true); expect(await adapter.isPostDismissed({ postId: post.id, userId: 'user-2' })).toBe(false); });
});
