/** Human-readable labels for streaming platform provider keys */
export const PROVIDER_LABELS: Record<string, string> = {
  spotify: 'Spotify',
  apple_music: 'Apple Music',
  youtube: 'YouTube',
  youtube_music: 'YouTube Music',
  soundcloud: 'SoundCloud',
  deezer: 'Deezer',
  tidal: 'Tidal',
  amazon: 'Amazon Music',
  amazon_music: 'Amazon Music',
  bandcamp: 'Bandcamp',
  beatport: 'Beatport',
  pandora: 'Pandora',
  napster: 'Napster',
  audiomack: 'Audiomack',
  qobuz: 'Qobuz',
  anghami: 'Anghami',
  boomplay: 'Boomplay',
  iheartradio: 'iHeartRadio',
  tiktok: 'TikTok',
  flo: 'FLO',
  gaana: 'Gaana',
  kkbox: 'KKBOX',
  line_music: 'LINE MUSIC',
  netease: 'NetEase Music',
  qq_music: 'QQ Music',
  trebel: 'Trebel',
  yandex: 'Yandex Music',
  audius: 'Audius',
  joox: 'JOOX',
  awa: 'AWA',
};
