import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { FLEET_ACTIONS } from './actions/fleet';

const target = resolve(
  import.meta.dirname,
  '../jovie-cli/src/fleet-contract.generated.ts'
);
const records = FLEET_ACTIONS.map(a => ({
  id: a.id,
  path: a.id.split('.'),
  tool: a.id.replace('.', '_'),
  summary: `Invoke canonical ${a.id} with a scoped worker identity.`,
  readOnly: a.id === 'fleet.status' || a.id === 'fleet.directory',
  inputSchema: a.inputSchema.toJSONSchema(),
}));
const source = `// Generated by @jovie/action-contracts/generate-fleet-cli.ts; do not edit.\nexport const FLEET_COMMANDS = ${JSON.stringify(records, null, 2)} as const;\n`;
const contents = execFileSync(
  process.execPath,
  [
    resolve(import.meta.dirname, '../../node_modules/@biomejs/biome/bin/biome'),
    'format',
    '--stdin-file-path',
    target,
  ],
  { input: source, encoding: 'utf8' }
);
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== contents)
    throw new Error('fleet CLI contract drift');
} else writeFileSync(target, contents);

import { execFileSync } from 'node:child_process';
