/**
 * YouTube video content classification (JOV-5136)
 *
 * Pure, deterministic heuristic classifier. Signals are checked in priority
 * order; the first match wins and the rationale lists every matched signal.
 * Confidence bands follow `lib/dsp-enrichment/matching/confidence.ts`
 * (very_high >= 0.85, high >= 0.75, medium >= 0.5).
 */

export type YouTubeVideoContentType =
  | 'music_video'
  | 'live_performance'
  | 'lyric_video'
  | 'short'
  | 'vlog'
  | 'other';

export interface ClassifyInput {
  readonly title: string;
  readonly description: string | null;
  readonly durationSeconds: number | null;
}

export interface ClassificationResult {
  readonly contentType: YouTubeVideoContentType;
  readonly confidence: number;
  readonly rationale: string;
}

const SHORT_MAX_SECONDS = 60;
const LYRIC_VIDEO_PATTERN = /lyric(s)?\s*video|lyric video/i;
const LIVE_PATTERN = /\blive\b.*(at|from|session)|\(live\)|live performance/i;
const DISTRIBUTOR_BLOCK_PATTERNS = [
  'provided to youtube by',
  'auto-generated by youtube',
] as const;
const MUSIC_VIDEO_TITLE_PATTERN = /official (music )?video|music video/i;
const VLOG_PATTERN = /vlog/i;

/**
 * Classify a channel video into a content type.
 *
 * Precedence: short > lyric_video > live_performance > music_video > vlog > other.
 */
export function classifyYouTubeVideo(
  video: ClassifyInput
): ClassificationResult {
  const title = video.title ?? '';
  const description = video.description ?? '';

  // 1. Shorts: duration <= 60s or a #shorts tag anywhere in title/description.
  const hasShortsTag = /#shorts/i.test(title) || /#shorts/i.test(description);
  const isShortDuration =
    video.durationSeconds !== null &&
    video.durationSeconds <= SHORT_MAX_SECONDS;
  if (isShortDuration || hasShortsTag) {
    const signals: string[] = [];
    if (isShortDuration)
      signals.push(
        `duration ${video.durationSeconds}s <= ${SHORT_MAX_SECONDS}s`
      );
    if (hasShortsTag) signals.push('#shorts tag');
    return {
      contentType: 'short',
      confidence: 0.9,
      rationale: `short: ${signals.join('; ')}`,
    };
  }

  // 2. Lyric videos.
  if (LYRIC_VIDEO_PATTERN.test(title)) {
    return {
      contentType: 'lyric_video',
      confidence: 0.85,
      rationale: 'lyric_video: title matches lyric-video pattern',
    };
  }

  // 3. Live performances.
  if (LIVE_PATTERN.test(title)) {
    return {
      contentType: 'live_performance',
      confidence: 0.8,
      rationale: 'live_performance: title matches live-performance pattern',
    };
  }

  // 4. Music videos: distributor block in description (strongest) or an
  //    "official (music) video" title.
  const matchedDistributorBlock = DISTRIBUTOR_BLOCK_PATTERNS.find(block =>
    description.toLowerCase().includes(block)
  );
  const hasMusicVideoTitle = MUSIC_VIDEO_TITLE_PATTERN.test(title);
  if (matchedDistributorBlock || hasMusicVideoTitle) {
    const signals: string[] = [];
    if (matchedDistributorBlock)
      signals.push(`description contains "${matchedDistributorBlock}"`);
    if (hasMusicVideoTitle)
      signals.push('title matches official/music-video pattern');
    // Distributor block is YouTube's own auto-generated art-track marker.
    const confidence = matchedDistributorBlock
      ? hasMusicVideoTitle
        ? 0.9
        : 0.85
      : 0.7;
    return {
      contentType: 'music_video',
      confidence,
      rationale: `music_video: ${signals.join('; ')}`,
    };
  }

  // 5. Vlogs.
  if (VLOG_PATTERN.test(title)) {
    return {
      contentType: 'vlog',
      confidence: 0.7,
      rationale: 'vlog: title matches vlog pattern',
    };
  }

  return {
    contentType: 'other',
    confidence: 0.5,
    rationale: 'no signals matched',
  };
}
