name: 'Create Neon Branch with Retry'
description: 'Create Neon branch with automatic cleanup and retry on limit errors'

inputs:
  project_id:
    description: 'Neon project ID'
    required: true
  branch_name:
    description: 'Sanitized branch name'
    required: true
  parent_branch:
    description: 'Parent branch name (optional)'
    required: false
  role:
    description: 'Database role (optional, defaults to neondb_owner)'
    required: false
    default: 'neondb_owner'
  api_key:
    description: 'Neon API key'
    required: true
  branch_limit:
    description: 'Total branch limit (default: 10)'
    required: false
    default: '10'
  protected_branches:
    description: 'Comma-separated list of protected branches'
    required: false
    default: 'main,development,preview,br-main,br-production'
  cleanup_threshold:
    description: 'Aggressive cleanup threshold (default: 3)'
    required: false
    default: '3'

outputs:
  branch_id:
    description: 'Created branch ID'
    value: ${{ steps.set-outputs.outputs.branch_id }}
  db_url:
    description: 'Database URL'
    value: ${{ steps.set-outputs.outputs.db_url }}
  db_url_pooled:
    description: 'Pooled database URL'
    value: ${{ steps.set-outputs.outputs.db_url_pooled }}

runs:
  using: 'composite'
  steps:
    - name: Create Neon branch (attempt 1)
      id: create-branch-attempt-1
      continue-on-error: true
      uses: neondatabase/create-branch-action@72ed4f69a12b6be9c16aebfad893f6a21e9aba8b # v6.4.0
      with:
        project_id: ${{ inputs.project_id }}
        branch_name: ${{ inputs.branch_name }}
        parent_branch: ${{ inputs.parent_branch }}
        role: ${{ inputs.role }}
        api_key: ${{ inputs.api_key }}

    - name: Aggressive cleanup on limit error
      if: steps.create-branch-attempt-1.outcome == 'failure'
      uses: ./.github/actions/neon-branch-cleanup
      with:
        neon_api_key: ${{ inputs.api_key }}
        neon_project_id: ${{ inputs.project_id }}
        branch_limit: ${{ inputs.branch_limit }}
        protected_branches: ${{ inputs.protected_branches }}
        cleanup_threshold: ${{ inputs.cleanup_threshold }}

    - name: Create Neon branch (attempt 2)
      id: create-branch-attempt-2
      if: steps.create-branch-attempt-1.outcome == 'failure'
      uses: neondatabase/create-branch-action@72ed4f69a12b6be9c16aebfad893f6a21e9aba8b # v6.4.0
      with:
        project_id: ${{ inputs.project_id }}
        branch_name: ${{ inputs.branch_name }}
        parent_branch: ${{ inputs.parent_branch }}
        role: ${{ inputs.role }}
        api_key: ${{ inputs.api_key }}

    - name: Set outputs from successful attempt
      id: set-outputs
      shell: bash
      run: |
        if [ "${{ steps.create-branch-attempt-1.outcome }}" == "success" ]; then
          echo "branch_id=${{ steps.create-branch-attempt-1.outputs.branch_id }}" >> $GITHUB_OUTPUT
          echo "db_url=${{ steps.create-branch-attempt-1.outputs.db_url }}" >> $GITHUB_OUTPUT
          echo "db_url_pooled=${{ steps.create-branch-attempt-1.outputs.db_url_pooled }}" >> $GITHUB_OUTPUT
        else
          echo "branch_id=${{ steps.create-branch-attempt-2.outputs.branch_id }}" >> $GITHUB_OUTPUT
          echo "db_url=${{ steps.create-branch-attempt-2.outputs.db_url }}" >> $GITHUB_OUTPUT
          echo "db_url_pooled=${{ steps.create-branch-attempt-2.outputs.db_url_pooled }}" >> $GITHUB_OUTPUT
        fi

    - name: Report Neon branch status
      if: always()
      shell: bash
      run: |
        ATTEMPT_1_OUTCOME='${{ steps.create-branch-attempt-1.outcome }}'
        ATTEMPT_1_CONCLUSION='${{ steps.create-branch-attempt-1.conclusion }}'
        ATTEMPT_2_OUTCOME='${{ steps.create-branch-attempt-2.outcome }}'
        ATTEMPT_2_CONCLUSION='${{ steps.create-branch-attempt-2.conclusion }}'
        BRANCH_ID='${{ steps.set-outputs.outputs.branch_id }}'

        if [ "$ATTEMPT_1_OUTCOME" == "success" ]; then
          echo "✅ Branch created on first attempt: $BRANCH_ID" >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi

        if [ "$ATTEMPT_2_OUTCOME" == "success" ]; then
          echo "⚠️ First attempt failed - ran aggressive cleanup and retried" >> "$GITHUB_STEP_SUMMARY"
          echo "✅ Branch created on retry: $BRANCH_ID" >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi

        echo "❌ Failed to create Neon branch after 2 attempts" >> "$GITHUB_STEP_SUMMARY"
        echo "Attempt 1 outcome: $ATTEMPT_1_OUTCOME" >> "$GITHUB_STEP_SUMMARY"
        echo "Attempt 1 conclusion: $ATTEMPT_1_CONCLUSION" >> "$GITHUB_STEP_SUMMARY"
        echo "Attempt 2 outcome: $ATTEMPT_2_OUTCOME" >> "$GITHUB_STEP_SUMMARY"
        echo "Attempt 2 conclusion: $ATTEMPT_2_CONCLUSION" >> "$GITHUB_STEP_SUMMARY"
        echo "Attempt 1 branch_id: ${{ steps.create-branch-attempt-1.outputs.branch_id }}" >> "$GITHUB_STEP_SUMMARY"
        echo "Attempt 2 branch_id: ${{ steps.create-branch-attempt-2.outputs.branch_id }}" >> "$GITHUB_STEP_SUMMARY"
        echo "set-outputs branch_id: $BRANCH_ID" >> "$GITHUB_STEP_SUMMARY"
        echo "See the 'Create Neon branch' step logs above for Neon API error details." >> "$GITHUB_STEP_SUMMARY"
