import type { CommercialSnapshot } from '../agent/lib/summer-commercial-projection';
export const NOW = new Date('2026-09-04T18:00:00Z');
export const m = (value: number) => ({ value, sourceId: 'record-1' });
export function snapshot(): CommercialSnapshot {
  return {
    schema: 'jovie.summer-commercial.snapshot/v2',
    objective: {
      issue: 'JOV-6065',
      product: 'logyourbody',
      outcome: 'shipped-and-5000-usd-mrr',
      targetRecurringMrrCents: 500000,
      deadline: '2026-10-05',
      revision: 'founder-2026-09-05',
    },
    bottleneck: { stage: 'prospects', sourceId: 'record-1' },
    funnel: {
      prospects: m(0),
      conversations: m(0),
      activated: m(0),
      paid: m(0),
      retained: m(0),
      mrrCents: m(0),
    },
    capacity: {
      agentMinutesPerDay: m(480),
      ciMinutesPerDay: m(240),
      founderMinutesPerDay: m(240),
      availableCashCents: m(0),
    },
    sources: [
      {
        id: 'record-1',
        reference: 'https://records.example/receipt/1',
        revision: 'revision-1',
        observedAt: NOW.toISOString(),
        basis: 'observed',
      },
    ],
    candidates: [
      {
        id: 'lyb-sales',
        product: 'logyourbody',
        kind: 'commercial',
        objectiveClass: 'direct',
        causalPath: 'Prospecting creates LYB customer conversations.',
        targetFunnelStage: 'prospects',
        boundedInvariant: null,
        stopShip: false,
        expectedObjectiveImpact: m(10),
        agentMinutes: m(60),
        ciMinutes: m(0),
        safetyCleared: true,
        held: false,
        noAuto: false,
        consentCleared: true,
        readinessCleared: true,
        lybCanaryPassed: true,
        gateSourceId: 'record-1',
        paidValueCompletions: m(1),
        collectedCashCents: m(50000),
        contributionMarginCents: m(30000),
        additionalFounderMinutesPerDay: m(30),
        daysToCash: m(1),
        incrementalSpendCents: m(0),
        repeatedUsefulJobs: null,
        founderMinutesSaved: null,
        usefulJobsPerWeekGain: null,
        reliabilityBasisPointsGain: null,
        reusedProductCount: null,
        implementationCostCents: null,
        ongoingCostCents: null,
        daysToBenefit: null,
      },
    ],
    activeCommercialId: null,
    recurringMrrCents: null,
    collectedCashCents: m(500000),
    committedOperatingCostCents: m(120000),
    employerCompensationCostCents: null,
    availableCashAfterObligationsCents: null,
    recordedFounderMinutesPerDay: m(60),
  };
}
