// Generated by @jovie/action-contracts/generate-fleet-cli.ts; do not edit.
export const FLEET_COMMANDS = [
  {
    id: 'fleet.register',
    path: ['fleet', 'register'],
    tool: 'fleet_register',
    summary: 'Invoke canonical fleet.register with a scoped worker identity.',
    readOnly: false,
    inputSchema: {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      type: 'object',
      properties: {
        workerId: {
          type: 'string',
          pattern: '^[a-z][a-z0-9-]{2,63}$',
        },
        runtimeClass: {
          type: 'string',
          minLength: 1,
          maxLength: 100,
        },
        capabilities: {
          maxItems: 32,
          type: 'array',
          items: {
            type: 'string',
            minLength: 1,
            maxLength: 100,
          },
        },
        tools: {
          maxItems: 32,
          type: 'array',
          items: {
            type: 'string',
            minLength: 1,
            maxLength: 100,
          },
        },
        connectors: {
          maxItems: 32,
          type: 'array',
          items: {
            type: 'string',
            minLength: 1,
            maxLength: 100,
          },
        },
        availability: {
          type: 'string',
          enum: ['available', 'busy', 'offline'],
        },
        specialization: {
          type: 'string',
          minLength: 1,
          maxLength: 100,
        },
      },
      required: [
        'workerId',
        'runtimeClass',
        'capabilities',
        'tools',
        'connectors',
        'availability',
      ],
      additionalProperties: false,
    },
  },
  {
    id: 'fleet.status',
    path: ['fleet', 'status'],
    tool: 'fleet_status',
    summary: 'Invoke canonical fleet.status with a scoped worker identity.',
    readOnly: true,
    inputSchema: {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      type: 'object',
      properties: {
        requestsAfter: {
          type: 'string',
          format: 'uuid',
          pattern:
            '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
        },
        historyAfter: {
          type: 'integer',
          minimum: 0,
          maximum: 9007199254740991,
        },
        historyLimit: {
          type: 'integer',
          minimum: 1,
          maximum: 100,
        },
      },
      additionalProperties: false,
    },
  },
  {
    id: 'work.next',
    path: ['work', 'next'],
    tool: 'work_next',
    summary: 'Invoke canonical work.next with a scoped worker identity.',
    readOnly: false,
    inputSchema: {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      type: 'object',
      properties: {},
      additionalProperties: false,
    },
  },
  {
    id: 'work.claim',
    path: ['work', 'claim'],
    tool: 'work_claim',
    summary: 'Invoke canonical work.claim with a scoped worker identity.',
    readOnly: false,
    inputSchema: {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      type: 'object',
      properties: {
        leaseId: {
          type: 'string',
          format: 'uuid',
          pattern:
            '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
        },
      },
      required: ['leaseId'],
      additionalProperties: false,
    },
  },
  {
    id: 'work.report',
    path: ['work', 'report'],
    tool: 'work_report',
    summary: 'Invoke canonical work.report with a scoped worker identity.',
    readOnly: false,
    inputSchema: {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      type: 'object',
      properties: {
        leaseId: {
          type: 'string',
          format: 'uuid',
          pattern:
            '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
        },
        outcome: {
          type: 'string',
          enum: ['completed', 'failed', 'blocked'],
        },
        summary: {
          type: 'string',
          minLength: 1,
          maxLength: 2000,
        },
        evidence: {
          minItems: 1,
          maxItems: 10,
          type: 'array',
          items: {
            type: 'object',
            properties: {
              ref: {
                type: 'string',
                minLength: 1,
                maxLength: 500,
              },
              summary: {
                type: 'string',
                minLength: 1,
                maxLength: 1000,
              },
            },
            required: ['ref', 'summary'],
            additionalProperties: false,
          },
        },
      },
      required: ['leaseId', 'outcome', 'summary', 'evidence'],
      additionalProperties: false,
    },
  },
  {
    id: 'defect.report',
    path: ['defect', 'report'],
    tool: 'defect_report',
    summary: 'Invoke canonical defect.report with a scoped worker identity.',
    readOnly: false,
    inputSchema: {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      type: 'object',
      properties: {
        leaseId: {
          type: 'string',
          format: 'uuid',
          pattern:
            '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
        },
        title: {
          type: 'string',
          minLength: 1,
          maxLength: 200,
        },
        command: {
          type: 'string',
          minLength: 1,
          maxLength: 100,
        },
        apiCode: {
          type: 'string',
          minLength: 1,
          maxLength: 100,
        },
        details: {
          type: 'string',
          minLength: 1,
          maxLength: 4000,
        },
        evidence: {
          minItems: 1,
          maxItems: 10,
          type: 'array',
          items: {
            type: 'object',
            properties: {
              ref: {
                type: 'string',
                minLength: 1,
                maxLength: 500,
              },
              summary: {
                type: 'string',
                minLength: 1,
                maxLength: 1000,
              },
            },
            required: ['ref', 'summary'],
            additionalProperties: false,
          },
        },
      },
      required: [
        'leaseId',
        'title',
        'command',
        'apiCode',
        'details',
        'evidence',
      ],
      additionalProperties: false,
    },
  },
  {
    id: 'fleet.directory',
    path: ['fleet', 'directory'],
    tool: 'fleet_directory',
    summary: 'Invoke canonical fleet.directory with a scoped worker identity.',
    readOnly: true,
    inputSchema: {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      type: 'object',
      properties: {},
      additionalProperties: false,
    },
  },
  {
    id: 'work.request',
    path: ['work', 'request'],
    tool: 'work_request',
    summary: 'Invoke canonical work.request with a scoped worker identity.',
    readOnly: false,
    inputSchema: {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      type: 'object',
      properties: {
        requestId: {
          type: 'string',
          format: 'uuid',
          pattern:
            '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
        },
        kind: {
          type: 'string',
          enum: ['help', 'dogfood', 'research'],
        },
        proposal: {
          type: 'object',
          properties: {
            issueId: {
              type: 'string',
              pattern: '^JOV-[1-9][0-9]*$',
            },
            title: {
              type: 'string',
              minLength: 1,
              maxLength: 200,
            },
            acceptanceCriteria: {
              minItems: 1,
              maxItems: 10,
              type: 'array',
              items: {
                type: 'string',
                minLength: 1,
                maxLength: 500,
              },
            },
            existingWorkRefs: {
              maxItems: 10,
              type: 'array',
              items: {
                type: 'string',
                minLength: 1,
                maxLength: 500,
              },
            },
            command: {
              type: 'string',
              enum: ['artist.get', 'artist.llms', 'api.openapi', 'docs.llms'],
            },
            argument: {
              type: 'string',
              minLength: 1,
              maxLength: 100,
            },
            requiredTools: {
              maxItems: 32,
              type: 'array',
              items: {
                type: 'string',
                minLength: 1,
                maxLength: 100,
              },
            },
            requiredConnectors: {
              maxItems: 32,
              type: 'array',
              items: {
                type: 'string',
                minLength: 1,
                maxLength: 100,
              },
            },
            targetWorkerId: {
              type: 'string',
              pattern: '^[a-z][a-z0-9-]{2,63}$',
            },
            maxDurationSeconds: {
              type: 'integer',
              minimum: 30,
              maximum: 3600,
            },
            notAfter: {
              type: 'string',
              format: 'date-time',
              pattern:
                '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$',
            },
          },
          required: [
            'issueId',
            'title',
            'acceptanceCriteria',
            'existingWorkRefs',
            'command',
            'requiredTools',
            'requiredConnectors',
            'maxDurationSeconds',
            'notAfter',
          ],
          additionalProperties: false,
        },
      },
      required: ['requestId', 'kind', 'proposal'],
      additionalProperties: false,
    },
  },
] as const;
