INSERT INTO "ba_oauth_clients" (
	"id",
	"client_id",
	"disabled",
	"skip_consent",
	"enable_end_session",
	"scopes",
	"name",
	"uri",
	"redirect_uris",
	"post_logout_redirect_uris",
	"token_endpoint_auth_method",
	"grant_types",
	"response_types",
	"public",
	"type",
	"require_pkce"
) VALUES
(
	'logyourbody-ios',
	'logyourbody-ios',
	false,
	true,
	true,
	'["openid","profile","email","offline_access"]'::jsonb,
	'LogYourBody for iOS',
	'https://logyourbody.com',
	'["logyourbody://oauth"]'::jsonb,
	'["logyourbody://signed-out"]'::jsonb,
	'none',
	'["authorization_code","refresh_token"]'::jsonb,
	'["code"]'::jsonb,
	true,
	'public',
	true
),
(
	'logyourbody-web',
	'logyourbody-web',
	false,
	true,
	true,
	'["openid","profile","email","offline_access"]'::jsonb,
	'LogYourBody for Web',
	'https://logyourbody.com',
	'["https://logyourbody.com/api/auth/callback","https://dev.logyourbody.com/api/auth/callback","http://localhost:3000/api/auth/callback"]'::jsonb,
	'["https://logyourbody.com/","https://dev.logyourbody.com/","http://localhost:3000/"]'::jsonb,
	'none',
	'["authorization_code","refresh_token"]'::jsonb,
	'["code"]'::jsonb,
	true,
	'public',
	true
)
ON CONFLICT ("client_id") DO UPDATE SET
	"disabled" = EXCLUDED."disabled",
	"skip_consent" = EXCLUDED."skip_consent",
	"enable_end_session" = EXCLUDED."enable_end_session",
	"scopes" = EXCLUDED."scopes",
	"name" = EXCLUDED."name",
	"uri" = EXCLUDED."uri",
	"redirect_uris" = EXCLUDED."redirect_uris",
	"post_logout_redirect_uris" = EXCLUDED."post_logout_redirect_uris",
	"token_endpoint_auth_method" = EXCLUDED."token_endpoint_auth_method",
	"grant_types" = EXCLUDED."grant_types",
	"response_types" = EXCLUDED."response_types",
	"public" = EXCLUDED."public",
	"type" = EXCLUDED."type",
	"require_pkce" = EXCLUDED."require_pkce",
	"updated_at" = now();
