/**
 * YouTube Revival Queue — Types
 *
 * Identifies underperforming evergreen videos that are candidates for
 * thumbnail + title packaging experiments.
 *
 * Pure types — no DB access. Storage is caller's responsibility.
 */

/** Traffic source from which a video's impressions originated */
export type TrafficSource =
  | 'browse_features'
  | 'suggested_videos'
  | 'search'
  | 'external'
  | 'channel_pages'
  | 'notifications'
  | 'playlists'
  | 'other';

/** Channel-level baseline metrics for a given traffic source */
export interface ChannelBaseline {
  readonly trafficSource: TrafficSource;
  /** Median CTR (0–1) for all videos in this traffic source */
  readonly medianCtr: number;
  /** Median watch-minutes-per-impression across all videos */
  readonly medianWatchMinPerImpression: number;
}

/** Per-video metrics consumed by the revival queue scorer */
export interface VideoMetrics {
  readonly videoId: string;
  readonly title: string;
  readonly thumbnailUrl?: string;
  /** ISO publish date */
  readonly publishedAt: string;
  readonly trafficSource: TrafficSource;
  /** Total impressions across the measurement window */
  readonly impressions: number;
  /** Click-through rate (0–1) */
  readonly ctr: number;
  /** Total views */
  readonly views: number;
  /** Total watch minutes generated by this video */
  readonly watchMinutes: number;
  /**
   * Reach trend: negative = declining, 0 = flat, positive = growing.
   * Computed as (recentImpressions - olderImpressions) / olderImpressions.
   */
  readonly reachTrend: number;
  /**
   * True if this video is classified as evergreen content
   * (not news, events, or time-sensitive).
   */
  readonly isEvergreen: boolean;
}

/** Why a video was flagged as a revival candidate */
export type RevivalFlag =
  | 'ctr_below_median'
  | 'watch_min_per_impression_below_baseline'
  | 'high_impressions_low_views'
  | 'evergreen_declining_reach';

/** A challenger set recommended for a revival experiment */
export interface ChallengerSet {
  /** Human-readable description of what this challenger tests */
  readonly hypothesis: string;
  /**
   * Key packaging element to swap.
   * 'face' = face-in-thumbnail test, 'title_hook' = new headline copy,
   * 'color' = high-contrast color palette change.
   */
  readonly packagingElement: 'face' | 'title_hook' | 'color' | 'combined';
  /** Short rationale for this challenger based on niche priors */
  readonly rationale: string;
}

/** A single video identified as a revival candidate */
export interface RevivalCandidate {
  readonly videoId: string;
  readonly title: string;
  readonly thumbnailUrl?: string;
  readonly publishedAt: string;
  /** All underperformance flags that triggered this candidate */
  readonly flags: RevivalFlag[];
  /** Opportunity score (0–100): higher = more upside from a packaging swap */
  readonly opportunityScore: number;
  /** Recommended challenger sets for the experiment */
  readonly challengers: ChallengerSet[];
  /** Snapshot of the metrics used for scoring */
  readonly metrics: {
    readonly impressions: number;
    readonly ctr: number;
    readonly views: number;
    readonly watchMinPerImpression: number;
    readonly reachTrend: number;
    readonly trafficSource: TrafficSource;
  };
}

/** Status of a packaging experiment */
export type ExperimentStatus =
  | 'pending'
  | 'running'
  | 'concluded_winner'
  | 'concluded_no_winner'
  | 'rolled_back';

/** A packaging experiment record */
export interface ExperimentRecord {
  readonly experimentId: string;
  readonly videoId: string;
  readonly videoTitle: string;
  readonly status: ExperimentStatus;
  /** ISO timestamp when the experiment started */
  readonly startedAt: string;
  /** ISO timestamp when the experiment concluded (if concluded) */
  readonly concludedAt?: string;
  readonly baseline: {
    readonly ctr: number;
    readonly watchMinPerImpression: number;
  };
  readonly challenger: {
    readonly ctr: number;
    readonly watchMinPerImpression: number;
  };
  /** Whether the challenger won (null while running) */
  readonly challengerWon: boolean | null;
}

/** Quota usage for the YouTube thumbnails.set API */
export interface QuotaUsage {
  /**
   * Quota units consumed today.
   * thumbnails.set costs ~50 units/call.
   */
  readonly usedToday: number;
  /** Daily budget cap in quota units */
  readonly dailyCap: number;
  /** Number of thumbnail swaps performed today */
  readonly swapsToday: number;
  /** Maximum swaps allowed per day */
  readonly maxSwapsPerDay: number;
}

/** The complete revival queue and dashboard data */
export interface RevivalQueue {
  /** Flagged candidates sorted by opportunityScore descending */
  readonly candidates: RevivalCandidate[];
  /** Active and concluded experiments */
  readonly experiments: ExperimentRecord[];
  /** Quota usage snapshot */
  readonly quota: QuotaUsage;
}
