/**
 * Database Schema - Explicit Named Re-exports
 *
 * This file re-exports all schema definitions from domain-focused modules
 * using explicit named exports for deterministic tree-shaking.
 */

// Admin
export {
  type AdminAuditLog,
  type AdminSystemSettings,
  adminAuditLog,
  adminSystemSettings,
  type CampaignSettings,
  campaignSettings,
  insertAdminAuditLogSchema,
  insertAdminSystemSettingsSchema,
  insertCampaignSettingsSchema,
  type NewAdminAuditLog,
  type NewAdminSystemSettings,
  type NewCampaignSettings,
  selectAdminAuditLogSchema,
  selectAdminSystemSettingsSchema,
  selectCampaignSettingsSchema,
} from './admin';

// Agent runs, steps, usage, credit grants
export {
  type AgentRun,
  type AgentRunStatus,
  type AgentRunStep,
  type AgentRunStepStatus,
  agentRunSteps,
  agentRuns,
  insertAgentRunSchema,
  insertAgentRunStepSchema,
  insertUserCreditGrantSchema,
  insertUserMonthlyUsageSchema,
  type NewAgentRun,
  type NewAgentRunStep,
  type NewUserCreditGrant,
  type NewUserMonthlyUsage,
  selectAgentRunSchema,
  selectAgentRunStepSchema,
  selectUserCreditGrantSchema,
  selectUserMonthlyUsageSchema,
  type UserCreditGrant,
  type UserMonthlyUsage,
  userCreditGrants,
  userMonthlyUsage,
} from './agent-runs';

// Analytics (Clicks, Audience, Tips, Blocks)
export {
  type AudienceAction,
  type AudienceBlock,
  type AudienceMember,
  type AudienceSourceGroup,
  type AudienceSourceLink,
  audienceActions,
  audienceBlocks,
  audienceMembers,
  audienceSourceGroups,
  audienceSourceLinks,
  type ClickEvent,
  clickEvents,
  type DailyProfileView,
  dailyProfileViews,
  FAN_NOTIFICATION_CONTENT_TYPES,
  type FanNotificationContentType,
  type FanNotificationPreferences,
  insertAudienceBlockSchema,
  insertClickEventSchema,
  insertNotificationSubscriptionSchema,
  insertTipSchema,
  type NewAudienceAction,
  type NewAudienceBlock,
  type NewAudienceMember,
  type NewAudienceSourceGroup,
  type NewAudienceSourceLink,
  type NewClickEvent,
  type NewDailyProfileView,
  type NewNotificationSubscription,
  type NewTip,
  type NotificationSubscription,
  notificationSubscriptions,
  selectAudienceBlockSchema,
  selectClickEventSchema,
  selectNotificationSubscriptionSchema,
  selectTipSchema,
  type Tip,
  tips,
} from './analytics';

// Audit (Ingest Audit Logs)
export {
  type IngestAuditLog,
  ingestAuditLogs,
  insertIngestAuditLogSchema,
  type NewIngestAuditLog,
  selectIngestAuditLogSchema,
} from './audit';
// Auth & Users
export {
  insertUserSchema,
  type NewUser,
  type NewUserSettings,
  selectUserSchema,
  type User,
  type UserSettings,
  userSettings,
  users,
} from './auth';
// Billing (Stripe, Audit)
export {
  type BillingAuditLog,
  billingAuditLog,
  insertBillingAuditLogSchema,
  insertStripeWebhookEventSchema,
  type NewBillingAuditLog,
  type NewStripeWebhookEvent,
  type StripeWebhookEvent,
  selectBillingAuditLogSchema,
  selectStripeWebhookEventSchema,
  stripeWebhookEvents,
} from './billing';
// Chat (Conversations, Messages, Audit)
export {
  type ChatAuditLog,
  type ChatConversation,
  type ChatMessage,
  chatAuditLog,
  chatConversations,
  chatMessages,
  insertChatAuditLogSchema,
  insertChatConversationSchema,
  insertChatMessageSchema,
  type NewChatAuditLog,
  type NewChatConversation,
  type NewChatMessage,
  selectChatAuditLogSchema,
  selectChatConversationSchema,
  selectChatMessageSchema,
} from './chat';
// Content (Providers, Releases, Recordings, Tracks)
export {
  type Artist,
  type ArtistRole,
  type ArtistType,
  artists,
  type ContentSlugRedirect,
  contentSlugRedirects,
  type DiscogRecording,
  type DiscogRelease,
  type DiscogReleaseTrack,
  type DiscogTrack,
  discogRecordings,
  discogReleases,
  discogReleaseTracks,
  discogTracks,
  insertArtistSchema,
  insertContentSlugRedirectSchema,
  insertDiscogRecordingSchema,
  insertDiscogReleaseSchema,
  insertDiscogReleaseTrackSchema,
  insertDiscogTrackSchema,
  insertProviderLinkSchema,
  insertProviderSchema,
  insertRecordingArtistSchema,
  insertReleaseArtistSchema,
  insertSmartLinkTargetSchema,
  insertTrackArtistSchema,
  type NewArtist,
  type NewContentSlugRedirect,
  type NewDiscogRecording,
  type NewDiscogRelease,
  type NewDiscogReleaseTrack,
  type NewDiscogTrack,
  type NewProvider,
  type NewProviderLink,
  type NewRecordingArtist,
  type NewReleaseArtist,
  type NewSmartLinkTarget,
  type NewTrackArtist,
  type Provider,
  type ProviderLink,
  providerLinks,
  providers,
  type RecordingArtist,
  type ReleaseArtist,
  recordingArtists,
  releaseArtists,
  type SmartLinkTarget,
  selectArtistSchema,
  selectContentSlugRedirectSchema,
  selectDiscogRecordingSchema,
  selectDiscogReleaseSchema,
  selectDiscogReleaseTrackSchema,
  selectDiscogTrackSchema,
  selectProviderLinkSchema,
  selectProviderSchema,
  selectRecordingArtistSchema,
  selectReleaseArtistSchema,
  selectSmartLinkTargetSchema,
  selectTrackArtistSchema,
  smartLinkTargets,
  type TrackArtist,
  trackArtists,
} from './content';
// DSP Bio Sync (Bio update pushes to DSPs)
export {
  type DspBioSyncMetadata,
  type DspBioSyncRequest,
  dspBioSyncRequests,
  insertDspBioSyncRequestSchema,
  type NewDspBioSyncRequest,
  selectDspBioSyncRequestSchema,
} from './dsp-bio-sync';
// DSP Catalog Scan (Discography mismatch detection)
export {
  type DspCatalogMismatch,
  type DspCatalogScan,
  dspCatalogMismatches,
  dspCatalogScans,
  insertDspCatalogMismatchSchema,
  insertDspCatalogScanSchema,
  type NewDspCatalogMismatch,
  type NewDspCatalogScan,
  selectDspCatalogMismatchSchema,
  selectDspCatalogScanSchema,
} from './dsp-catalog-scan';
// DSP Enrichment (Cross-platform matches, enrichment data)
export {
  type DspArtistMatch,
  type DspExternalUrls,
  type DspImageUrls,
  type DspMatchConfidenceBreakdown,
  dspArtistMatches,
  type FanReleaseNotification,
  fanReleaseNotifications,
  insertDspArtistMatchSchema,
  insertFanReleaseNotificationSchema,
  insertSocialLinkSuggestionSchema,
  type NewDspArtistMatch,
  type NewFanReleaseNotification,
  type NewSocialLinkSuggestion,
  type SocialLinkSuggestion,
  type SocialSuggestionConfidenceBreakdown,
  selectDspArtistMatchSchema,
  selectFanReleaseNotificationSchema,
  selectSocialLinkSuggestionSchema,
  socialLinkSuggestions,
} from './dsp-enrichment';
// Email Engagement (Opens, Clicks, Drip Campaigns)
export {
  type CampaignEnrollment,
  type CampaignSequence,
  type CampaignStep,
  type CampaignStepCondition,
  campaignEnrollments,
  campaignSequences,
  type EmailEngagement,
  type EmailEngagementEventType,
  type EmailEngagementMetadata,
  emailEngagement,
  insertCampaignEnrollmentSchema,
  insertCampaignSequenceSchema,
  insertEmailEngagementSchema,
  type NewCampaignEnrollment,
  type NewCampaignSequence,
  type NewEmailEngagement,
  selectCampaignEnrollmentSchema,
  selectCampaignSequenceSchema,
  selectEmailEngagementSchema,
  type TrackedEmailType,
} from './email-engagement';
// Enums
export {
  artistRoleEnum,
  artistTypeEnum,
  audienceDeviceTypeEnum,
  audienceIntentLevelEnum,
  audienceMemberTypeEnum,
  catalogMismatchStatusEnum,
  catalogMismatchTypeEnum,
  catalogScanStatusEnum,
  chatMessageRoleEnum,
  claimInviteStatusEnum,
  contactChannelEnum,
  contactRoleEnum,
  contentSlugTypeEnum,
  creatorDistributionEventTypeEnum,
  creatorDistributionPlatformEnum,
  creatorTypeEnum,
  currencyCodeEnum,
  deliveryStatusEnum,
  discogReleaseTypeEnum,
  dspBioSyncMethodEnum,
  dspBioSyncStatusEnum,
  dspMatchStatusEnum,
  inboxEmailCategoryEnum,
  inboxOutboundSentByEnum,
  inboxThreadPriorityEnum,
  inboxThreadStatusEnum,
  ingestionJobStatusEnum,
  ingestionSourceTypeEnum,
  ingestionStatusEnum,
  insightCategoryEnum,
  insightPriorityEnum,
  insightRunStatusEnum,
  insightStatusEnum,
  insightTypeEnum,
  leadAttributionStatusEnum,
  leadDiscoverySourceEnum,
  leadOutreachRouteEnum,
  leadOutreachStatusEnum,
  leadRampModeEnum,
  leadSourcePlatformEnum,
  leadStatusEnum,
  linkTypeEnum,
  metadataSubmissionIssueStatusEnum,
  metadataSubmissionStatusEnum,
  notificationChannelEnum,
  outreachChannelEnum,
  outreachStatusEnum,
  photoStatusEnum,
  pixelEventTypeEnum,
  pixelForwardStatusEnum,
  playlistStatusEnum,
  profileClaimRoleEnum,
  profileOwnershipActionEnum,
  providerKindEnum,
  providerLinkOwnerEnum,
  referralCommissionStatusEnum,
  referralStatusEnum,
  releaseNotificationStatusEnum,
  releaseNotificationTypeEnum,
  releaseTaskAssigneeTypeEnum,
  releaseTaskPriorityEnum,
  releaseTaskStatusEnum,
  scraperStrategyEnum,
  senderStatusEnum,
  socialAccountStatusEnum,
  socialLinkStateEnum,
  socialSuggestionStatusEnum,
  subscriptionPlanEnum,
  subscriptionStatusEnum,
  suppressionReasonEnum,
  taskAgentStatusEnum,
  taskAssigneeKindEnum,
  themeModeEnum,
  tipStatusEnum,
  userStatusLifecycleEnum,
  waitlistInviteStatusEnum,
  waitlistStatusEnum,
} from './enums';
// Feedback
export {
  type FeedbackItem,
  feedbackItems,
  feedbackStatusEnumValues,
  insertFeedbackItemSchema,
  type NewFeedbackItem,
  selectFeedbackItemSchema,
} from './feedback';
// Identity (Cross-platform artist identity links)
export {
  type ArtistIdentityLink,
  artistIdentityLinks,
  insertArtistIdentityLinkSchema,
  type NewArtistIdentityLink,
  selectArtistIdentityLinkSchema,
} from './identity';
// Inbox (Inbound emails, Threads, Outbound routing replies)
export {
  type EmailThread,
  emailThreads,
  type InboundEmail,
  inboundEmails,
  insertEmailThreadSchema,
  insertInboundEmailSchema,
  insertOutboundReplySchema,
  type NewEmailThread,
  type NewInboundEmail,
  type NewOutboundReply,
  type OutboundReply,
  outboundReplies,
  selectEmailThreadSchema,
  selectInboundEmailSchema,
  selectOutboundReplySchema,
} from './inbox';
// Ingestion
export {
  type IngestionJob,
  ingestionJobs,
  insertIngestionJobSchema,
  insertScraperConfigSchema,
  type NewIngestionJob,
  type NewScraperConfig,
  type ScraperConfig,
  scraperConfigs,
  selectIngestionJobSchema,
  selectScraperConfigSchema,
} from './ingestion';
// AI Insights (AI-generated analytics insights)
export {
  aiInsights,
  insertAiInsightSchema,
  insertInsightGenerationRunSchema,
  insightGenerationRuns,
  selectAiInsightSchema,
  selectInsightGenerationRunSchema,
} from './insights';
// Investor Portal (investors.jov.ie)
export {
  type InvestorLink,
  type InvestorSettings,
  type InvestorView,
  insertInvestorLinkSchema,
  insertInvestorSettingsSchema,
  insertInvestorViewSchema,
  investorLinks,
  investorSettings,
  investorStageEnum,
  investorViews,
  type NewInvestorLink,
  type NewInvestorSettings,
  type NewInvestorView,
  selectInvestorLinkSchema,
  selectInvestorSettingsSchema,
  selectInvestorViewSchema,
} from './investors';
// Leads (Discovery Pipeline)
export {
  type DiscoveryKeyword,
  discoveryKeywords,
  insertDiscoveryKeywordSchema,
  insertLeadFunnelEventSchema,
  insertLeadPipelineSettingsSchema,
  insertLeadSchema,
  insertLeadSearchResultSchema,
  type Lead,
  type LeadFunnelEvent,
  type LeadGuardrailThresholds,
  type LeadPipelineSettings,
  type LeadSearchResult,
  type LeadSignalSnapshot,
  leadFunnelEvents,
  leadPipelineSettings,
  leadSearchResults,
  leads,
  type NewDiscoveryKeyword,
  type NewLead,
  type NewLeadFunnelEvent,
  type NewLeadPipelineSettings,
  type NewLeadSearchResult,
  selectDiscoveryKeywordSchema,
  selectLeadFunnelEventSchema,
  selectLeadPipelineSettingsSchema,
  selectLeadSchema,
  selectLeadSearchResultSchema,
} from './leads';
// Links (Social, Wrapped, Signed)
export {
  type DashboardIdempotencyKey,
  dashboardIdempotencyKeys,
  insertSignedLinkAccessSchema,
  insertSocialAccountSchema,
  insertSocialLinkSchema,
  insertWrappedLinkSchema,
  type NewDashboardIdempotencyKey,
  type NewSignedLinkAccess,
  type NewSocialAccount,
  type NewSocialLink,
  type NewWrappedLink,
  type SignedLinkAccess,
  type SocialAccount,
  type SocialLink,
  selectSignedLinkAccessSchema,
  selectSocialAccountSchema,
  selectSocialLinkSchema,
  selectWrappedLinkSchema,
  signedLinkAccess,
  socialAccounts,
  socialLinks,
  type WrappedLink,
  wrappedLinks,
} from './links';
export {
  insertMetadataSubmissionArtifactSchema,
  insertMetadataSubmissionIssueSchema,
  insertMetadataSubmissionRequestSchema,
  insertMetadataSubmissionSnapshotSchema,
  insertMetadataSubmissionTargetSchema,
  type MetadataSubmissionArtifact,
  type MetadataSubmissionIssue,
  type MetadataSubmissionRequest,
  type MetadataSubmissionSnapshot,
  type MetadataSubmissionSnapshotData,
  type MetadataSubmissionTarget,
  metadataSubmissionArtifacts,
  metadataSubmissionIssues,
  metadataSubmissionRequests,
  metadataSubmissionSnapshots,
  metadataSubmissionTargets,
  type NewMetadataSubmissionArtifact,
  type NewMetadataSubmissionIssue,
  type NewMetadataSubmissionRequest,
  type NewMetadataSubmissionSnapshot,
  type NewMetadataSubmissionTarget,
  selectMetadataSubmissionArtifactSchema,
  selectMetadataSubmissionIssueSchema,
  selectMetadataSubmissionRequestSchema,
  selectMetadataSubmissionSnapshotSchema,
  selectMetadataSubmissionTargetSchema,
} from './metadata-submissions';
// Pixel Tracking (Events, Creator Configs)
export {
  type CreatorPixel,
  creatorPixels,
  insertCreatorPixelSchema,
  insertPixelEventSchema,
  type NewCreatorPixel,
  type NewPixelEvent,
  type PixelEvent,
  type PixelEventData,
  type PixelForwardingStatus,
  pixelEvents,
  selectCreatorPixelSchema,
  selectPixelEventSchema,
} from './pixels';
// Playlists (Jovie-curated playlists)
export {
  insertJoviePlaylistSchema,
  insertJoviePlaylistTrackSchema,
  type JoviePlaylist,
  type JoviePlaylistTrack,
  joviePlaylists,
  joviePlaylistTracks,
  type NewJoviePlaylist,
  type NewJoviePlaylistTrack,
  selectJoviePlaylistSchema,
  selectJoviePlaylistTrackSchema,
} from './playlists';
// Pre-save campaigns (Spotify, Apple Music)
export {
  type NewPreSaveToken,
  type PreSaveToken,
  preSaveTokens,
} from './pre-save';
// Product Update Subscribers
export {
  insertProductUpdateSubscriberSchema,
  type NewProductUpdateSubscriber,
  type ProductUpdateSubscriber,
  productUpdateSubscribers,
  selectProductUpdateSubscriberSchema,
} from './product-update-subscribers';
// Creator Profiles
export {
  type CreatorAvatarCandidate,
  type CreatorClaimInvite,
  type CreatorContact,
  type CreatorDistributionEvent,
  type CreatorDistributionEventMetadata,
  type CreatorProfile,
  type CreatorProfileAttribute,
  creatorAvatarCandidates,
  creatorClaimInvites,
  creatorContacts,
  creatorDistributionEvents,
  creatorProfileAttributes,
  creatorProfiles,
  type FitScoreBreakdown,
  insertCreatorAvatarCandidateSchema,
  insertCreatorClaimInviteSchema,
  insertCreatorContactSchema,
  insertCreatorDistributionEventSchema,
  insertCreatorProfileAttributeSchema,
  insertCreatorProfileSchema,
  insertProfileOwnershipLogSchema,
  insertProfilePhotoSchema,
  insertUserProfileClaimSchema,
  type NewCreatorAvatarCandidate,
  type NewCreatorClaimInvite,
  type NewCreatorContact,
  type NewCreatorDistributionEvent,
  type NewCreatorProfile,
  type NewCreatorProfileAttribute,
  type NewProfileOwnershipLog,
  type NewProfilePhoto,
  type NewUserProfileClaim,
  type NotificationPreferences,
  // Profile ownership audit log
  type ProfileOwnershipLog,
  type ProfilePhoto,
  profileOwnershipLog,
  profilePhotos,
  selectCreatorAvatarCandidateSchema,
  selectCreatorClaimInviteSchema,
  selectCreatorContactSchema,
  selectCreatorDistributionEventSchema,
  selectCreatorProfileAttributeSchema,
  selectCreatorProfileSchema,
  selectProfileOwnershipLogSchema,
  selectProfilePhotoSchema,
  selectUserProfileClaimSchema,
  // User-profile claims (ownership)
  type UserProfileClaim,
  userProfileClaims,
} from './profiles';
// Promo Downloads
export {
  insertPromoDownloadEventSchema,
  insertPromoDownloadSchema,
  type NewPromoDownload,
  type NewPromoDownloadEvent,
  type PromoDownload,
  type PromoDownloadEvent,
  promoDownloadEvents,
  promoDownloads,
  selectPromoDownloadEventSchema,
  selectPromoDownloadSchema,
} from './promo-downloads';
// Referral Program (Codes, Referrals, Commissions)
export {
  insertReferralCodeSchema,
  insertReferralCommissionSchema,
  insertReferralSchema,
  type NewReferral,
  type NewReferralCode,
  type NewReferralCommission,
  type Referral,
  type ReferralCode,
  type ReferralCommission,
  referralCodes,
  referralCommissions,
  referrals,
  selectReferralCodeSchema,
  selectReferralCommissionSchema,
  selectReferralSchema,
} from './referrals';
// Release Tasks (Templates, Template Items, Tasks)
export {
  insertReleaseTaskSchema,
  insertReleaseTaskTemplateItemSchema,
  insertReleaseTaskTemplateSchema,
  type NewReleaseTask,
  type NewReleaseTaskTemplate,
  type NewReleaseTaskTemplateItem,
  type ReleaseTask,
  type ReleaseTaskTemplate,
  type ReleaseTaskTemplateItem,
  releaseTasks,
  releaseTaskTemplateItems,
  releaseTaskTemplates,
  selectReleaseTaskSchema,
  selectReleaseTaskTemplateItemSchema,
  selectReleaseTaskTemplateSchema,
} from './release-tasks';
// Sender (Email Quotas, Sending Reputation, Send Attribution)
export {
  type CreatorEmailQuota,
  type CreatorSendingReputation,
  creatorEmailQuotas,
  creatorSendingReputation,
  type EmailSendAttribution,
  emailSendAttribution,
  insertCreatorEmailQuotaSchema,
  insertCreatorSendingReputationSchema,
  insertEmailSendAttributionSchema,
  type NewCreatorEmailQuota,
  type NewCreatorSendingReputation,
  type NewEmailSendAttribution,
  type QuotaMetadata,
  type ReputationMetadata,
  selectCreatorEmailQuotaSchema,
  selectCreatorSendingReputationSchema,
  selectEmailSendAttributionSchema,
} from './sender';
// Suppression (Email Suppressions, Webhook Events, Delivery Logs)
export {
  type CategorySubscription,
  categorySubscriptions,
  type DeliveryLogMetadata,
  type EmailSuppression,
  emailSuppressions,
  insertCategorySubscriptionSchema,
  insertEmailSuppressionSchema,
  insertNotificationDeliveryLogSchema,
  insertUnsubscribeTokenSchema,
  insertWebhookEventSchema,
  type NewCategorySubscription,
  type NewEmailSuppression,
  type NewNotificationDeliveryLog,
  type NewUnsubscribeToken,
  type NewWebhookEvent,
  type NotificationDeliveryLog,
  notificationDeliveryLog,
  type SuppressionMetadata,
  selectCategorySubscriptionSchema,
  selectEmailSuppressionSchema,
  selectNotificationDeliveryLogSchema,
  selectUnsubscribeTokenSchema,
  selectWebhookEventSchema,
  type UnsubscribeToken,
  unsubscribeTokens,
  type WebhookEvent,
  webhookEvents,
} from './suppression';
// Tasks
export {
  insertTaskSchema,
  type NewTask,
  selectTaskSchema,
  type Task,
  tasks,
} from './tasks';
// Tip Audience (Fan notifications from tips)
export {
  insertTipAudienceSchema,
  type NewTipAudienceMember,
  selectTipAudienceSchema,
  type TipAudienceMember,
  tipAudience,
  tipAudienceSourceEnum,
} from './tip-audience';
// Tour (Tour Dates)
export {
  insertTourDateSchema,
  type NewTourDate,
  selectTourDateSchema,
  type TourDate,
  ticketStatusEnum,
  tourDateProviderEnum,
  tourDates,
} from './tour';

// Waitlist
export {
  insertWaitlistEntrySchema,
  insertWaitlistInviteSchema,
  insertWaitlistSettingsSchema,
  type NewWaitlistEntry,
  type NewWaitlistInvite,
  selectWaitlistEntrySchema,
  selectWaitlistInviteSchema,
  selectWaitlistSettingsSchema,
  type WaitlistEntry,
  type WaitlistInvite,
  type WaitlistSettings,
  waitlistEntries,
  waitlistInvites,
  waitlistSettings,
} from './waitlist';
