/**
 * Database Schema - Explicit Named Re-exports
 *
 * This file re-exports all schema definitions from domain-focused modules
 * using explicit named exports for deterministic tree-shaking.
 */

// Admin
export {
  type AdminAuditLog,
  type AdminCost,
  type AdminSystemSettings,
  adminAuditLog,
  adminCosts,
  adminSystemSettings,
  type CampaignSettings,
  campaignSettings,
  insertAdminAuditLogSchema,
  insertAdminCostsSchema,
  insertAdminSystemSettingsSchema,
  insertCampaignSettingsSchema,
  type NewAdminAuditLog,
  type NewAdminCost,
  type NewAdminSystemSettings,
  type NewCampaignSettings,
  selectAdminAuditLogSchema,
  selectAdminCostsSchema,
  selectAdminSystemSettingsSchema,
  selectCampaignSettingsSchema,
} from './admin';
// Agent Registry (Skills Catalog, Tools Catalog, Retouch Jobs)
export {
  insertRetouchJobSchema,
  insertSkillsCatalogSchema,
  insertToolsCatalogSchema,
  type NewRetouchJob,
  type NewSkillRunEventRow,
  type NewSkillsCatalogRow,
  type NewSkillsCatalogVersionRow,
  type NewToolsCatalogRow,
  type RetouchJob,
  retouchJobs,
  type SkillRunEventRow,
  type SkillsCatalogRow,
  type SkillsCatalogVersionRow,
  selectRetouchJobSchema,
  selectSkillsCatalogSchema,
  selectToolsCatalogSchema,
  skillRunEvents,
  skillsCatalog,
  skillsCatalogVersions,
  type ToolsCatalogRow,
  toolsCatalog,
} from './agents';
// AI crawler analytics snapshots
export { aiCrawlerAnalyticsSnapshots } from './ai-crawler-analytics';
// Analytics (Clicks, Audience, Tips, Blocks)
export {
  type AudienceAction,
  type AudienceBlock,
  type AudienceMember,
  type AudienceSourceGroup,
  type AudienceSourceLink,
  audienceActions,
  audienceBlocks,
  audienceMembers,
  audienceSourceGroups,
  audienceSourceLinks,
  type ClickEvent,
  clickEvents,
  type DailyProfileView,
  dailyProfileViews,
  FAN_NOTIFICATION_CONTENT_TYPES,
  type FanNotificationContentType,
  type FanNotificationPreferences,
  insertAudienceBlockSchema,
  insertClickEventSchema,
  insertNotificationSubscriptionSchema,
  insertTipSchema,
  type NewAudienceAction,
  type NewAudienceBlock,
  type NewAudienceMember,
  type NewAudienceSourceGroup,
  type NewAudienceSourceLink,
  type NewClickEvent,
  type NewDailyProfileView,
  type NewNotificationSubscription,
  type NewTip,
  type NotificationSubscription,
  notificationSubscriptions,
  publicProfileCaptureDismissals,
  selectAudienceBlockSchema,
  selectClickEventSchema,
  selectNotificationSubscriptionSchema,
  selectTipSchema,
  type Tip,
  tips,
} from './analytics';
// Audit (Ingest Audit Logs)
export {
  type IngestAuditLog,
  ingestAuditLogs,
  insertIngestAuditLogSchema,
  type NewIngestAuditLog,
  selectIngestAuditLogSchema,
} from './audit';
// Auth & Users
export {
  insertUserSchema,
  type NewUser,
  type NewUserSettings,
  selectUserSchema,
  type User,
  type UserSettings,
  userSettings,
  users,
} from './auth';
// Better Auth (self-hosted auth core tables)
export {
  type BaAccount,
  type BaSession,
  type BaUser,
  type BaVerification,
  baAccounts,
  baJwks,
  baOauthAccessTokens,
  baOauthClients,
  baOauthConsents,
  baOauthRefreshTokens,
  baSessions,
  baUsers,
  baVerifications,
  type NewBaAccount,
  type NewBaSession,
  type NewBaUser,
  type NewBaVerification,
} from './better-auth';
// Billing (Stripe, Audit)
export {
  type BillingAuditLog,
  billingAuditLog,
  insertBillingAuditLogSchema,
  insertStripeWebhookEventSchema,
  type NewBillingAuditLog,
  type NewStripeWebhookEvent,
  type StripeWebhookEvent,
  selectBillingAuditLogSchema,
  selectStripeWebhookEventSchema,
  stripeWebhookEvents,
} from './billing';
// Chat (Conversations, Messages, Audit)
export {
  type ChatAuditLog,
  type ChatConversation,
  type ChatMessage,
  type ChatTurn,
  chatAuditLog,
  chatConversations,
  chatMessages,
  chatTurns,
  insertChatAuditLogSchema,
  insertChatConversationSchema,
  insertChatMessageSchema,
  insertChatTurnSchema,
  type NewChatAuditLog,
  type NewChatConversation,
  type NewChatMessage,
  type NewChatTurn,
  selectChatAuditLogSchema,
  selectChatConversationSchema,
  selectChatMessageSchema,
  selectChatTurnSchema,
} from './chat';
// AI Connectors (v1)
export {
  type AgentRun,
  agentRuns,
  type ConnectorAccount,
  type ConnectorSyncState,
  type ContextFact,
  connectorAccounts,
  connectorSyncStates,
  contextFacts,
  type ExternalObject,
  externalObjects,
  insertAgentRunSchema,
  insertConnectorAccountSchema,
  insertConnectorSyncStateSchema,
  insertContextFactSchema,
  insertExternalObjectSchema,
  insertSuggestedActionSchema,
  insertWebhookDeliverySchema,
  insertWorkflowRunOutcomeSchema,
  insertWorkflowRunSchema,
  type NewAgentRun,
  type NewConnectorAccount,
  type NewConnectorSyncState,
  type NewContextFact,
  type NewExternalObject,
  type NewSuggestedAction,
  type NewWebhookDelivery,
  type NewWorkflowRun,
  type NewWorkflowRunOutcome,
  type SuggestedAction,
  selectAgentRunSchema,
  selectConnectorAccountSchema,
  selectConnectorSyncStateSchema,
  selectContextFactSchema,
  selectExternalObjectSchema,
  selectSuggestedActionSchema,
  selectWebhookDeliverySchema,
  selectWorkflowRunOutcomeSchema,
  selectWorkflowRunSchema,
  suggestedActions,
  type WebhookDelivery,
  type WorkflowRun,
  type WorkflowRunOutcome,
  webhookDeliveries,
  workflowRunOutcomes,
  workflowRuns,
} from './connectors';
// Content (Providers, Releases, Recordings, Tracks)
export {
  type Artist,
  type ArtistRole,
  type ArtistType,
  artists,
  type ContentSlugRedirect,
  contentSlugRedirects,
  type DiscogRecording,
  type DiscogRelease,
  type DiscogReleaseTrack,
  type DiscogTrack,
  discogRecordings,
  discogReleases,
  discogReleaseTracks,
  discogTracks,
  insertArtistSchema,
  insertContentSlugRedirectSchema,
  insertDiscogRecordingSchema,
  insertDiscogReleaseSchema,
  insertDiscogReleaseTrackSchema,
  insertDiscogTrackSchema,
  insertProviderLinkSchema,
  insertProviderSchema,
  insertRecordingArtistSchema,
  insertReleaseArtistSchema,
  insertSmartLinkTargetSchema,
  insertTrackArtistSchema,
  type NewArtist,
  type NewContentSlugRedirect,
  type NewDiscogRecording,
  type NewDiscogRelease,
  type NewDiscogReleaseTrack,
  type NewDiscogTrack,
  type NewProvider,
  type NewProviderLink,
  type NewRecordingArtist,
  type NewReleaseArtist,
  type NewSmartLinkTarget,
  type NewTrackArtist,
  type Provider,
  type ProviderLink,
  providerLinks,
  providers,
  type RecordingArtist,
  type ReleaseArtist,
  recordingArtists,
  releaseArtists,
  type SmartLinkTarget,
  selectArtistSchema,
  selectContentSlugRedirectSchema,
  selectDiscogRecordingSchema,
  selectDiscogReleaseSchema,
  selectDiscogReleaseTrackSchema,
  selectDiscogTrackSchema,
  selectProviderLinkSchema,
  selectProviderSchema,
  selectRecordingArtistSchema,
  selectReleaseArtistSchema,
  selectSmartLinkTargetSchema,
  selectTrackArtistSchema,
  smartLinkTargets,
  type TrackArtist,
  trackArtists,
} from './content';
// DSP Bio Sync (Bio update pushes to DSPs)
export {
  type DspBioSyncMetadata,
  type DspBioSyncRequest,
  dspBioSyncRequests,
  insertDspBioSyncRequestSchema,
  type NewDspBioSyncRequest,
  selectDspBioSyncRequestSchema,
} from './dsp-bio-sync';
// DSP Catalog Scan (Discography mismatch detection)
export {
  type DspCatalogMismatch,
  type DspCatalogScan,
  dspCatalogMismatches,
  dspCatalogScans,
  insertDspCatalogMismatchSchema,
  insertDspCatalogScanSchema,
  type NewDspCatalogMismatch,
  type NewDspCatalogScan,
  selectDspCatalogMismatchSchema,
  selectDspCatalogScanSchema,
} from './dsp-catalog-scan';
// DSP Enrichment (Cross-platform matches, enrichment data)
export {
  type DspArtistMatch,
  type DspExternalUrls,
  type DspImageUrls,
  type DspMatchConfidenceBreakdown,
  dspArtistMatches,
  type FanReleaseNotification,
  fanReleaseNotifications,
  insertDspArtistMatchSchema,
  insertFanReleaseNotificationSchema,
  insertSocialLinkSuggestionSchema,
  type NewDspArtistMatch,
  type NewFanReleaseNotification,
  type NewSocialLinkSuggestion,
  type SocialLinkSuggestion,
  type SocialSuggestionConfidenceBreakdown,
  selectDspArtistMatchSchema,
  selectFanReleaseNotificationSchema,
  selectSocialLinkSuggestionSchema,
  socialLinkSuggestions,
} from './dsp-enrichment';
// Email Engagement (Opens, Clicks, Drip Campaigns)
export {
  type CampaignEnrollment,
  type CampaignSequence,
  type CampaignStep,
  type CampaignStepCondition,
  campaignEnrollments,
  campaignSequences,
  type EmailEngagement,
  type EmailEngagementEventType,
  type EmailEngagementMetadata,
  emailEngagement,
  insertCampaignEnrollmentSchema,
  insertCampaignSequenceSchema,
  insertEmailEngagementSchema,
  type NewCampaignEnrollment,
  type NewCampaignSequence,
  type NewEmailEngagement,
  selectCampaignEnrollmentSchema,
  selectCampaignSequenceSchema,
  selectEmailEngagementSchema,
  type TrackedEmailType,
} from './email-engagement';
// Enums
export {
  agentRunStatusEnum,
  artistRoleEnum,
  artistTypeEnum,
  audienceDeviceTypeEnum,
  audienceIntentLevelEnum,
  audienceMemberTypeEnum,
  catalogMismatchStatusEnum,
  catalogMismatchTypeEnum,
  catalogScanStatusEnum,
  chatMessageRoleEnum,
  claimInviteStatusEnum,
  connectorProviderEnum,
  connectorStatusEnum,
  contactChannelEnum,
  contactRoleEnum,
  contentSlugTypeEnum,
  contextFactKindEnum,
  creatorDistributionEventTypeEnum,
  creatorDistributionPlatformEnum,
  creatorTypeEnum,
  currencyCodeEnum,
  deliveryStatusEnum,
  discogReleaseTypeEnum,
  dspBioSyncMethodEnum,
  dspBioSyncStatusEnum,
  dspMatchStatusEnum,
  inboxEmailCategoryEnum,
  inboxOutboundSentByEnum,
  inboxThreadPriorityEnum,
  inboxThreadStatusEnum,
  ingestionJobStatusEnum,
  ingestionSourceTypeEnum,
  ingestionStatusEnum,
  insightCategoryEnum,
  insightPriorityEnum,
  insightRunStatusEnum,
  insightStatusEnum,
  insightTypeEnum,
  leadAttributionStatusEnum,
  leadDiscoverySourceEnum,
  leadOutreachRouteEnum,
  leadOutreachStatusEnum,
  leadRampModeEnum,
  leadSourcePlatformEnum,
  leadStatusEnum,
  libraryAssetApprovalStatusEnum,
  libraryAssetVisibilityEnum,
  linkTypeEnum,
  merchCardStatusEnum,
  merchDesignLaneEnum,
  merchDesignOptionStatusEnum,
  merchFulfillmentJobStatusEnum,
  merchGenerationStatusEnum,
  merchOrderStatusEnum,
  merchPayoutStatusEnum,
  merchTechniqueEnum,
  metadataSubmissionIssueStatusEnum,
  metadataSubmissionStatusEnum,
  notificationChannelEnum,
  outreachChannelEnum,
  outreachStatusEnum,
  photoStatusEnum,
  pixelEventTypeEnum,
  pixelForwardStatusEnum,
  playlistStatusEnum,
  profileClaimRoleEnum,
  profileOwnershipActionEnum,
  providerKindEnum,
  providerLinkOwnerEnum,
  referralCommissionStatusEnum,
  referralStatusEnum,
  releaseNotificationStatusEnum,
  releaseNotificationTypeEnum,
  releaseTaskAssigneeTypeEnum,
  releaseTaskPriorityEnum,
  releaseTaskStatusEnum,
  retouchJobStatusEnum,
  scraperStrategyEnum,
  senderStatusEnum,
  skillKindEnum,
  skillLifecycleEnum,
  socialAccountStatusEnum,
  socialLinkStateEnum,
  socialSuggestionStatusEnum,
  subscriptionPlanEnum,
  subscriptionStatusEnum,
  suggestedActionStatusEnum,
  suppressionReasonEnum,
  taskAgentStatusEnum,
  taskAssigneeKindEnum,
  themeModeEnum,
  tipStatusEnum,
  userStatusLifecycleEnum,
  waitlistInviteStatusEnum,
  waitlistStatusEnum,
  webhookProviderEnum,
  workflowRunStatusEnum,
} from './enums';
// Feature flag per-environment overrides
export {
  type FeatureFlagOverrideRow,
  featureFlagOverrides,
} from './feature-flags';
// Feedback
export {
  type FeedbackItem,
  type FeedbackVote,
  feedbackItems,
  feedbackStatusEnumValues,
  feedbackVoteEnumValues,
  insertFeedbackItemSchema,
  type NewFeedbackItem,
  selectFeedbackItemSchema,
} from './feedback';
// Identity (Cross-platform artist identity links)
export {
  type ArtistIdentityLink,
  artistIdentityLinks,
  insertArtistIdentityLinkSchema,
  type NewArtistIdentityLink,
  selectArtistIdentityLinkSchema,
} from './identity';
// Inbox (Inbound emails, Threads, Outbound routing replies)
export {
  type EmailThread,
  emailThreads,
  type InboundEmail,
  inboundEmails,
  insertEmailThreadSchema,
  insertInboundEmailSchema,
  insertOutboundReplySchema,
  type NewEmailThread,
  type NewInboundEmail,
  type NewOutboundReply,
  type OutboundReply,
  outboundReplies,
  selectEmailThreadSchema,
  selectInboundEmailSchema,
  selectOutboundReplySchema,
} from './inbox';
// Ingestion
export {
  type IngestionJob,
  ingestionJobs,
  insertIngestionJobSchema,
  insertScraperConfigSchema,
  type NewIngestionJob,
  type NewScraperConfig,
  type ScraperConfig,
  scraperConfigs,
  selectIngestionJobSchema,
  selectScraperConfigSchema,
} from './ingestion';
// AI Insights (AI-generated analytics insights)
export {
  aiInsights,
  insertAiInsightSchema,
  insertInsightGenerationRunSchema,
  insightGenerationRuns,
  selectAiInsightSchema,
  selectInsightGenerationRunSchema,
} from './insights';
// Investor Portal (investors.jov.ie)
export {
  type InvestorLink,
  type InvestorSettings,
  type InvestorView,
  insertInvestorLinkSchema,
  insertInvestorSettingsSchema,
  insertInvestorViewSchema,
  investorLinks,
  investorSettings,
  investorStageEnum,
  investorViews,
  type NewInvestorLink,
  type NewInvestorSettings,
  type NewInvestorView,
  selectInvestorLinkSchema,
  selectInvestorSettingsSchema,
  selectInvestorViewSchema,
} from './investors';
// Leads (Discovery Pipeline)
export {
  type DiscoveryKeyword,
  discoveryKeywords,
  insertDiscoveryKeywordSchema,
  insertLeadFunnelEventSchema,
  insertLeadPipelineSettingsSchema,
  insertLeadSchema,
  insertLeadSearchResultSchema,
  type Lead,
  type LeadFunnelEvent,
  type LeadGuardrailThresholds,
  type LeadPipelineSettings,
  type LeadSearchResult,
  type LeadSignalSnapshot,
  leadFunnelEvents,
  leadPipelineSettings,
  leadSearchResults,
  leads,
  type NewDiscoveryKeyword,
  type NewLead,
  type NewLeadFunnelEvent,
  type NewLeadPipelineSettings,
  type NewLeadSearchResult,
  selectDiscoveryKeywordSchema,
  selectLeadFunnelEventSchema,
  selectLeadPipelineSettingsSchema,
  selectLeadSchema,
  selectLeadSearchResultSchema,
} from './leads';
// Library asset approval workflow (JOV-2932)
export {
  insertLibraryAssetApprovalStatusSchema,
  type LibraryAssetApprovalStatusRow,
  type LibraryAssetApprovalStatusValue,
  libraryAssetApprovalStatuses,
  type NewLibraryAssetApprovalStatusRow,
  selectLibraryAssetApprovalStatusSchema,
} from './library';
// Library Asset Share (per-asset public/private URLs)
export {
  insertLibraryAssetShareSettingsSchema,
  type LibraryAssetShareSettingsRow,
  type LibraryAssetVisibilityValue,
  libraryAssetShareSettings,
  type NewLibraryAssetShareSettingsRow,
  selectLibraryAssetShareSettingsSchema,
} from './library-asset-share';
// Library Share Drops (press kit / label review portals)
export {
  insertLibraryShareDropItemSchema,
  insertLibraryShareDropSchema,
  type LibraryShareDrop,
  type LibraryShareDropItem,
  type LibraryShareDropLayout,
  libraryShareDropItems,
  libraryShareDropLayoutEnum,
  libraryShareDrops,
  type NewLibraryShareDrop,
  type NewLibraryShareDropItem,
  selectLibraryShareDropItemSchema,
  selectLibraryShareDropSchema,
} from './library-share-drops';
// Links (Social, Wrapped, Signed)
export {
  type DashboardIdempotencyKey,
  dashboardIdempotencyKeys,
  insertSignedLinkAccessSchema,
  insertSocialAccountSchema,
  insertSocialLinkSchema,
  insertWrappedLinkSchema,
  type NewDashboardIdempotencyKey,
  type NewSignedLinkAccess,
  type NewSocialAccount,
  type NewSocialLink,
  type NewWrappedLink,
  type SignedLinkAccess,
  type SocialAccount,
  type SocialLink,
  selectSignedLinkAccessSchema,
  selectSocialAccountSchema,
  selectSocialLinkSchema,
  selectWrappedLinkSchema,
  signedLinkAccess,
  socialAccounts,
  socialLinks,
  type WrappedLink,
  wrappedLinks,
} from './links';
// Memory Core v0 (evidence-backed entity graph) — gh-9872 / JOV-2706
export {
  // drizzle-zod schemas (all 12 tables)
  insertMemoryAssetEntityMentionSchema,
  insertMemoryAssetSchema,
  insertMemoryEnrichmentJobSchema,
  insertMemoryEntityAliasSchema,
  insertMemoryEntityEdgeSchema,
  insertMemoryEntityIdentitySchema,
  insertMemoryEntitySchema,
  insertMemoryEventParticipantSchema,
  insertMemoryEventSchema,
  insertMemoryObservationSchema,
  insertMemoryOpportunitySchema,
  insertMemorySourceRecordSchema,
  // inferred types (all 12 tables)
  type MemoryAsset,
  type MemoryAssetEntityMention,
  type MemoryEnrichmentJob,
  type MemoryEntity,
  type MemoryEntityAlias,
  type MemoryEntityEdge,
  type MemoryEntityIdentity,
  type MemoryEntityStatus,
  type MemoryEntityType,
  type MemoryEvent,
  type MemoryEventParticipant,
  type MemoryObservation,
  type MemoryObservationStatus,
  type MemoryOpportunity,
  type MemoryOpportunityStatus,
  type MemorySourceRecord,
  type MemorySourceType,
  // tables
  memoryAssetEntityMentions,
  memoryAssets,
  memoryEnrichmentJobs,
  memoryEntities,
  memoryEntityAliases,
  memoryEntityEdges,
  memoryEntityIdentities,
  // enums (pgEnum + values arrays + TS types per patterns in user-interviews/feedback/etc)
  memoryEntityStatusEnum,
  memoryEntityStatusEnumValues,
  memoryEntityTypeEnum,
  memoryEntityTypeEnumValues,
  memoryEventParticipants,
  memoryEvents,
  memoryObservationStatusEnum,
  memoryObservationStatusEnumValues,
  memoryObservations,
  memoryOpportunities,
  memoryOpportunityStatusEnum,
  memoryOpportunityStatusEnumValues,
  memorySourceRecords,
  memorySourceTypeEnum,
  memorySourceTypeEnumValues,
  type NewMemoryAsset,
  type NewMemoryAssetEntityMention,
  type NewMemoryEnrichmentJob,
  type NewMemoryEntity,
  type NewMemoryEntityAlias,
  type NewMemoryEntityEdge,
  type NewMemoryEntityIdentity,
  type NewMemoryEvent,
  type NewMemoryEventParticipant,
  type NewMemoryObservation,
  type NewMemoryOpportunity,
  type NewMemorySourceRecord,
  selectMemoryAssetEntityMentionSchema,
  selectMemoryAssetSchema,
  selectMemoryEnrichmentJobSchema,
  selectMemoryEntityAliasSchema,
  selectMemoryEntityEdgeSchema,
  selectMemoryEntityIdentitySchema,
  selectMemoryEntitySchema,
  selectMemoryEventParticipantSchema,
  selectMemoryEventSchema,
  selectMemoryObservationSchema,
  selectMemoryOpportunitySchema,
  selectMemorySourceRecordSchema,
} from './memory';
// Merch (Jovie-owned storefront products, orders, fulfillment, payout ledger)
export {
  insertMerchCardSchema,
  insertMerchDesignOptionSchema,
  insertMerchFulfillmentJobSchema,
  insertMerchGenerationBatchSchema,
  insertMerchOrderSchema,
  insertMerchPayoutLedgerEntrySchema,
  type MerchArtistBrief,
  type MerchCard,
  type MerchDesignOption,
  type MerchFulfillmentJob,
  type MerchGenerationBatch,
  type MerchLearningSnapshot,
  type MerchOrder,
  type MerchPayoutLedgerEntry,
  type MerchPricingSnapshot,
  type MerchPrintfulSnapshot,
  type MerchShippingAddress,
  type MerchVariantMap,
  type MerchVisibilityRules,
  merchCards,
  merchDesignOptions,
  merchFulfillmentJobs,
  merchGenerationBatches,
  merchOrders,
  merchPayoutLedgerEntries,
  type NewMerchCard,
  type NewMerchDesignOption,
  type NewMerchFulfillmentJob,
  type NewMerchGenerationBatch,
  type NewMerchOrder,
  type NewMerchPayoutLedgerEntry,
  selectMerchCardSchema,
  selectMerchDesignOptionSchema,
  selectMerchFulfillmentJobSchema,
  selectMerchGenerationBatchSchema,
  selectMerchOrderSchema,
  selectMerchPayoutLedgerEntrySchema,
} from './merch';
export {
  insertMetadataSubmissionArtifactSchema,
  insertMetadataSubmissionIssueSchema,
  insertMetadataSubmissionRequestSchema,
  insertMetadataSubmissionSnapshotSchema,
  insertMetadataSubmissionTargetSchema,
  type MetadataSubmissionArtifact,
  type MetadataSubmissionIssue,
  type MetadataSubmissionRequest,
  type MetadataSubmissionSnapshot,
  type MetadataSubmissionSnapshotData,
  type MetadataSubmissionTarget,
  metadataSubmissionArtifacts,
  metadataSubmissionIssues,
  metadataSubmissionRequests,
  metadataSubmissionSnapshots,
  metadataSubmissionTargets,
  type NewMetadataSubmissionArtifact,
  type NewMetadataSubmissionIssue,
  type NewMetadataSubmissionRequest,
  type NewMetadataSubmissionSnapshot,
  type NewMetadataSubmissionTarget,
  selectMetadataSubmissionArtifactSchema,
  selectMetadataSubmissionIssueSchema,
  selectMetadataSubmissionRequestSchema,
  selectMetadataSubmissionSnapshotSchema,
  selectMetadataSubmissionTargetSchema,
} from './metadata-submissions';
// Model experiments (per-workflow A/B bake-off + cost-aware promotion, GH #11462)
export {
  insertModelExperimentSchema,
  type ModelExperiment,
  type ModelExperimentCandidate,
  type ModelExperimentStatus,
  type ModelPromotion,
  type ModelUsageEvent,
  modelExperimentStatusEnumValues,
  modelExperiments,
  modelPromotions,
  modelUsageEvents,
  type NewModelExperiment,
  type NewModelPromotion,
  type NewModelUsageEvent,
  selectModelExperimentSchema,
} from './model-experiments';
// Notifications (SMS subscribe intents, cross-artist contact identity)
export {
  insertNotificationContactSchema,
  insertSmsSubscribeIntentSchema,
  type NewNotificationContact,
  type NewSmsSubscribeIntent,
  type NotificationContact,
  notificationContacts,
  type SmsContactStatus,
  type SmsIntentStatus,
  type SmsSubscribeIntent,
  selectNotificationContactSchema,
  selectSmsSubscribeIntentSchema,
  smsSubscribeIntents,
} from './notifications';
// Onboarding deterministic script lines (JOV-3806)
export {
  insertOnboardingScriptLineSchema,
  type NewOnboardingScriptLine,
  type OnboardingScriptLine,
  onboardingScriptLines,
  selectOnboardingScriptLineSchema,
} from './onboarding-script';
// Pixel Tracking (Events, Creator Configs)
export {
  type CreatorPixel,
  creatorPixels,
  insertCreatorPixelSchema,
  insertPixelEventSchema,
  type NewCreatorPixel,
  type NewPixelEvent,
  type PixelEvent,
  type PixelEventData,
  type PixelForwardingStatus,
  pixelEvents,
  selectCreatorPixelSchema,
  selectPixelEventSchema,
} from './pixels';
// Playlists (Jovie-curated playlists)
export {
  insertJoviePlaylistSchema,
  insertJoviePlaylistTrackSchema,
  type JoviePlaylist,
  type JoviePlaylistTrack,
  joviePlaylists,
  joviePlaylistTracks,
  type NewJoviePlaylist,
  type NewJoviePlaylistTrack,
  selectJoviePlaylistSchema,
  selectJoviePlaylistTrackSchema,
} from './playlists';
// Pre-save campaigns (Spotify, Apple Music)
export {
  type NewPreSaveToken,
  type PreSaveToken,
  preSaveTokens,
} from './pre-save';
// Product Update Subscribers
export {
  insertProductUpdateSubscriberSchema,
  type NewProductUpdateSubscriber,
  type ProductUpdateSubscriber,
  productUpdateSubscribers,
  selectProductUpdateSubscriberSchema,
} from './product-update-subscribers';
// Unified public profile surface registry
export {
  insertProfileSurfaceSchema,
  insertProfileSurfaceSourceSchema,
  type NewProfileSurface,
  type NewProfileSurfaceSource,
  type ProfileSurface,
  type ProfileSurfaceMonitoringPreference,
  type ProfileSurfaceQualificationEvent,
  type ProfileSurfaceSource,
  profileSurfaceMonitoringPreferences,
  profileSurfaceQualificationEvents,
  profileSurfaceSources,
  profileSurfaces,
  selectProfileSurfaceSchema,
  selectProfileSurfaceSourceSchema,
} from './profile-surfaces';
// Creator Profiles
export {
  type CreatorAvatarCandidate,
  type CreatorClaimInvite,
  type CreatorContact,
  type CreatorDistributionEvent,
  type CreatorDistributionEventMetadata,
  type CreatorProfile,
  type CreatorProfileAttribute,
  creatorAvatarCandidates,
  creatorClaimInvites,
  creatorContacts,
  creatorDistributionEvents,
  creatorProfileAttributes,
  creatorProfiles,
  type FitScoreBreakdown,
  insertCreatorAvatarCandidateSchema,
  insertCreatorClaimInviteSchema,
  insertCreatorContactSchema,
  insertCreatorDistributionEventSchema,
  insertCreatorProfileAttributeSchema,
  insertCreatorProfileSchema,
  insertProfileOwnershipLogSchema,
  insertProfilePhotoSchema,
  insertUserProfileClaimSchema,
  type NewCreatorAvatarCandidate,
  type NewCreatorClaimInvite,
  type NewCreatorContact,
  type NewCreatorDistributionEvent,
  type NewCreatorProfile,
  type NewCreatorProfileAttribute,
  type NewProfileOwnershipLog,
  type NewProfilePhoto,
  type NewUserProfileClaim,
  type NotificationPreferences,
  // Profile ownership audit log
  type ProfileOwnershipLog,
  type ProfilePhoto,
  profileOwnershipLog,
  profilePhotos,
  selectCreatorAvatarCandidateSchema,
  selectCreatorClaimInviteSchema,
  selectCreatorContactSchema,
  selectCreatorDistributionEventSchema,
  selectCreatorProfileAttributeSchema,
  selectCreatorProfileSchema,
  selectProfileOwnershipLogSchema,
  selectProfilePhotoSchema,
  selectUserProfileClaimSchema,
  // User-profile claims (ownership)
  type UserProfileClaim,
  userProfileClaims,
} from './profiles';
// Promo Downloads
export {
  insertPromoDownloadEventSchema,
  insertPromoDownloadSchema,
  type NewPromoDownload,
  type NewPromoDownloadEvent,
  type PromoDownload,
  type PromoDownloadEvent,
  promoDownloadEvents,
  promoDownloads,
  selectPromoDownloadEventSchema,
  selectPromoDownloadSchema,
} from './promo-downloads';
// Referral Program (Codes, Referrals, Commissions)
export {
  insertReferralCodeSchema,
  insertReferralCommissionSchema,
  insertReferralSchema,
  type NewReferral,
  type NewReferralCode,
  type NewReferralCommission,
  type Referral,
  type ReferralCode,
  type ReferralCommission,
  referralCodes,
  referralCommissions,
  referrals,
  selectReferralCodeSchema,
  selectReferralCommissionSchema,
  selectReferralSchema,
} from './referrals';
// Release Tasks (Templates, Template Items, Tasks, Catalog, Clusters, Snapshots, Telemetry)
export {
  type CustomTaskTelemetry,
  customTaskTelemetry,
  insertCustomTaskTelemetrySchema,
  insertReleaseSkillClusterSchema,
  insertReleaseTaskCatalogSchema,
  insertReleaseTaskSchema,
  insertReleaseTaskSnapshotSchema,
  insertReleaseTaskTemplateItemSchema,
  insertReleaseTaskTemplateSchema,
  type NewCustomTaskTelemetry,
  type NewReleaseSkillCluster,
  type NewReleaseTask,
  type NewReleaseTaskCatalog,
  type NewReleaseTaskSnapshot,
  type NewReleaseTaskTemplate,
  type NewReleaseTaskTemplateItem,
  type ReleaseSkillCluster,
  type ReleaseTask,
  type ReleaseTaskCatalog,
  type ReleaseTaskSnapshot,
  type ReleaseTaskTemplate,
  type ReleaseTaskTemplateItem,
  releaseSkillClusters,
  releaseTaskCatalog,
  releaseTaskSnapshots,
  releaseTasks,
  releaseTaskTemplateItems,
  releaseTaskTemplates,
  selectCustomTaskTelemetrySchema,
  selectReleaseSkillClusterSchema,
  selectReleaseTaskCatalogSchema,
  selectReleaseTaskSchema,
  selectReleaseTaskSnapshotSchema,
  selectReleaseTaskTemplateItemSchema,
  selectReleaseTaskTemplateSchema,
} from './release-tasks';
// Revenue Cohorts (IRPAA cohort tags + pre-Jovie baselines) — gh-12141
export {
  ARTIST_REVENUE_COHORTS,
  type ArtistCohortMatchCriteria,
  type ArtistRevenueCohort,
  type ArtistRevenueCohortRow,
  artistRevenueCohorts,
  insertArtistRevenueCohortSchema,
  type NewArtistRevenueCohortRow,
  selectArtistRevenueCohortSchema,
} from './revenue-cohorts';
// Sender (Email Quotas, Sending Reputation, Send Attribution)
export {
  type CreatorEmailQuota,
  type CreatorSendingReputation,
  creatorEmailQuotas,
  creatorSendingReputation,
  type EmailSendAttribution,
  emailSendAttribution,
  insertCreatorEmailQuotaSchema,
  insertCreatorSendingReputationSchema,
  insertEmailSendAttributionSchema,
  type NewCreatorEmailQuota,
  type NewCreatorSendingReputation,
  type NewEmailSendAttribution,
  type QuotaMetadata,
  type ReputationMetadata,
  selectCreatorEmailQuotaSchema,
  selectCreatorSendingReputationSchema,
  selectEmailSendAttributionSchema,
} from './sender';
// Suppression (Email Suppressions, Webhook Events, Delivery Logs)
export {
  type CategorySubscription,
  categorySubscriptions,
  type DeliveryLogMetadata,
  type EmailSuppression,
  emailSuppressions,
  insertCategorySubscriptionSchema,
  insertEmailSuppressionSchema,
  insertNotificationDeliveryLogSchema,
  insertUnsubscribeTokenSchema,
  insertWebhookEventSchema,
  type NewCategorySubscription,
  type NewEmailSuppression,
  type NewNotificationDeliveryLog,
  type NewUnsubscribeToken,
  type NewWebhookEvent,
  type NotificationDeliveryLog,
  notificationDeliveryLog,
  type SuppressionMetadata,
  selectCategorySubscriptionSchema,
  selectEmailSuppressionSchema,
  selectNotificationDeliveryLogSchema,
  selectUnsubscribeTokenSchema,
  selectWebhookEventSchema,
  type UnsubscribeToken,
  unsubscribeTokens,
  type WebhookEvent,
  webhookEvents,
} from './suppression';
// Tasks
export {
  insertTaskSchema,
  type NewTask,
  selectTaskSchema,
  type Task,
  tasks,
} from './tasks';
// Tip Audience (Fan notifications from tips)
export {
  insertTipAudienceSchema,
  type NewTipAudienceMember,
  selectTipAudienceSchema,
  type TipAudienceMember,
  tipAudience,
  tipAudienceSourceEnum,
} from './tip-audience';
// Tour (Tour Dates)
export {
  insertTourDateSchema,
  type NewTourDate,
  selectTourDateSchema,
  type TourDate,
  ticketStatusEnum,
  tourDateProviderEnum,
  tourDates,
} from './tour';
// User Interviews (Mom Test interviews post-onboarding)
export {
  type InterviewMetadata,
  type InterviewSummaryStructured,
  type InterviewTranscriptEntry,
  insertUserInterviewSchema,
  type NewUserInterview,
  selectUserInterviewSchema,
  type UserInterview,
  type UserInterviewStatus,
  userInterviewStatusEnumValues,
  userInterviews,
} from './user-interviews';
// Waitlist
export {
  insertWaitlistAuditLogSchema,
  insertWaitlistEntrySchema,
  insertWaitlistInviteSchema,
  insertWaitlistSettingsSchema,
  type NewWaitlistAuditLog,
  type NewWaitlistEntry,
  type NewWaitlistInvite,
  selectWaitlistAuditLogSchema,
  selectWaitlistEntrySchema,
  selectWaitlistInviteSchema,
  selectWaitlistSettingsSchema,
  type WaitlistAuditLog,
  type WaitlistEntry,
  type WaitlistInvite,
  type WaitlistSettings,
  waitlistAuditLogs,
  waitlistEntries,
  waitlistInvites,
  waitlistSettings,
} from './waitlist';
// Apple Wallet profile passes
export {
  type AppleWalletPassDevice,
  type AppleWalletPassRegistration,
  type AppleWalletProfilePass,
  appleWalletPassDevices,
  appleWalletPassRegistrations,
  appleWalletProfilePasses,
  insertAppleWalletPassDeviceSchema,
  insertAppleWalletPassRegistrationSchema,
  insertAppleWalletProfilePassSchema,
  type NewAppleWalletPassDevice,
  type NewAppleWalletPassRegistration,
  type NewAppleWalletProfilePass,
  selectAppleWalletPassDeviceSchema,
  selectAppleWalletPassRegistrationSchema,
  selectAppleWalletProfilePassSchema,
} from './wallet';
