# Main Branch Protection Ruleset
#
# This ruleset enables the autonomous agent pipeline:
#
# For AGENT PRs (linear/*, claude/*, codegen-bot/*):
#   CI passes → scope-judge passes → auto-approve-agent-prs.yml submits review
#   → 1 approval satisfied → auto-merge enters merge queue → merge
#
# For HUMAN PRs:
#   CI passes → human reviews and approves → 1 approval satisfied → merge
#
# KEY DESIGN DECISIONS:
#
# 1. required_approving_review_count: 1
#    This is what makes auto-approve meaningful. The auto-approve workflow
#    submits a review that counts as the required approval. Without this,
#    any PR passing CI could merge with zero review.
#
# 2. require_code_owner_review: false
#    CODEOWNERS auto-requests reviewers (so humans get notified) but
#    doesn't hard-gate. This allows the github-actions[bot] review from
#    auto-approve to satisfy the approval requirement.
#
# 3. dismiss_stale_reviews_on_push: true
#    When agent-remediation pushes a fix, old approvals are dismissed.
#    This forces auto-approve to re-evaluate after each fix attempt,
#    ensuring the approval reflects the FINAL state of the code.
#
# 4. Simplified status checks: only PR Ready + Migration Guard
#    PR Ready already aggregates: ci-fast (typecheck + lint + knip +
#    guardrails) + unit tests + a11y + layout guard. Requiring individual
#    checks AND the aggregate is redundant and causes "pending" stuck
#    states when path-gated checks skip.
#
# 5. scope-judge is NOT a required status check here
#    It only runs on agent branches. If required here, non-agent PRs
#    would be stuck forever. Instead, auto-approve-agent-prs.yml checks
#    for scope-judge status internally before approving.
#
# 6. merge_queue enabled
#    PRs enter the merge queue after approval. The queue runs CI again
#    (merge_group trigger) to catch integration conflicts between
#    concurrent PRs.

name: 'Main Branch Protection'
enforcement: 'active'
target:
  ref_name:
    include:
      - 'refs/heads/main'
    exclude: []

rules:
  # ── Pull Request Reviews ──────────────────────────────────────────────
  - type: 'pull_request'
    parameters:
      # Require exactly 1 approval. For agent PRs, auto-approve-agent-prs.yml
      # provides this. For human PRs, a human reviewer provides this.
      required_approving_review_count: 1

      # Dismiss approvals when new commits are pushed. Critical for
      # agent-remediation: when the agent pushes a fix, the old approval
      # is dismissed, and auto-approve re-evaluates the new code.
      dismiss_stale_reviews_on_push: true

      # CODEOWNERS auto-requests reviewers but does NOT hard-gate.
      # This allows github-actions[bot] reviews to satisfy the approval.
      require_code_owner_review: false

      # Require the person who pushed the last commit to NOT be the approver.
      # Disabled because agent-remediation pushes fixes and auto-approve
      # reviews — both run as github-actions[bot].
      require_last_push_approval: false

  # ── Required Status Checks ────────────────────────────────────────────
  - type: 'required_status_checks'
    parameters:
      # Require branch to be up-to-date with main before merging.
      # The merge queue handles this automatically.
      strict_required_status_checks_policy: true
      required_status_checks:
        # PR Ready: The single aggregate gate for all CI checks.
        # Internally aggregates:
        #   ci-fast (typecheck + biome lint + eslint boundaries + knip + guardrails)
        #   + unit tests (sharded 2/2)
        #   + a11y (axe audit)
        #   + layout guard (overlap/touching detection)
        - context: 'CI / PR Ready'

        # Migration Guard: Separate from PR Ready because it's independently
        # path-gated (only runs when DB/schema files change). Prevents
        # dangerous migration patterns from reaching production.
        - context: 'CI / Migration Guard'

  # ── Merge Queue ────────────────────────────────────────────────────────
  - type: 'merge_queue'
    parameters:
      # Merge method: squash keeps history clean with one commit per PR
      merge_method: 'squash'

      # Min entries before queue starts processing. 1 = process immediately
      # (don't wait for batching). This maximizes speed for autonomous PRs.
      min_entries_to_merge: 1

      # Max entries to batch together. Small batches reduce blast radius
      # if something fails in the queue.
      max_entries_to_merge: 5

      # Minutes to wait for more PRs before processing a batch.
      # 0 = process immediately when min_entries_to_merge is met.
      min_entries_to_merge_wait_minutes: 0

      # Status checks that must pass in the merge queue context.
      # The CI workflow triggers on merge_group events and runs
      # the same checks as on pull_request.
      check_response_timeout_minutes: 30

  # ── Branch Integrity ───────────────────────────────────────────────────
  - type: 'non_fast_forward'
    # Block force pushes to main. Always.

# ── Bypass Actors ──────────────────────────────────────────────────────
# No bypass actors. Every PR — human or agent — must pass through
# the same gates. The auto-approve workflow provides the review,
# not a bypass.
bypass_actors: []
