name: 'Production Branch Protection (full gate)'
enforcement: 'active'
target:
  ref_name:
    include:
      - 'refs/heads/production'
    exclude: []
rules:
  - type: 'pull_request'
    parameters:
      dismiss_stale_reviews_on_push: false
      require_code_owner_review: false
      required_approving_review_count: 0
      require_last_push_approval: false
  - type: 'required_status_checks'
    parameters:
      strict_required_status_checks_policy: true
      required_status_checks:
        - context: 'CI / Typecheck'
        - context: 'CI / Lint'
        - context: 'CI / Migration Guard'
        - context: 'CI / AI Review Gate'
        - context: 'CI / Drizzle Check'
        - context: 'CI / Build'
        - context: 'CI / Unit Tests'
        - context: 'CI / E2E Tests'
        - context: 'CI / ci-fast'
bypass_actors: []
