name: 'Main Branch Protection'
enforcement: 'active'
target:
  ref_name:
    include:
      - 'refs/heads/main'
    exclude: []
rules:
  - type: 'pull_request'
    parameters:
      dismiss_stale_reviews_on_push: false
      require_code_owner_review: false
      required_approving_review_count: 0
      require_last_push_approval: false
  - type: 'required_status_checks'
    parameters:
      strict_required_status_checks_policy: true
      required_status_checks:
        - context: 'CI / Typecheck'
        - context: 'CI / Lint'
        - context: 'CI / Migration Guard'
        - context: 'CI / ci-fast'
        - context: 'CI / Unit Tests (1/2)'
        - context: 'CI / Unit Tests (2/2)'
        - context: 'CI / A11y (axe)'
        - context: 'CI / Layout Guard (blocking)'
        - context: 'CI / PR Ready'
bypass_actors: []
